### ISSUE TITLE
K7 - potíže s importem

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#1020]
Zdravím,

začaly nám v MKP padat importy s následující chybou:

```
Nov 28, 2023 3:11:00 PM org.kramerius.Import run
WARNING: POST http://localhost:8080/search/api/admin/v7.0/processes returned a response status of 500 Internal Server Error: {"message":"error scheduling new process"}
java.lang.RuntimeException: POST http://localhost:8080/search/api/admin/v7.0/processes returned a response status of 500 Internal Server Error: {"message":"error scheduling new process"}
at cz.incad.kramerius.processes.new_api.ProcessScheduler.schedule(ProcessScheduler.java:55)
at cz.incad.kramerius.processes.new_api.ProcessScheduler.scheduleIndexation(ProcessScheduler.java:70)
```

Zkoušel jsem restart dockeru, ale nepomohlo to. Poprvé se to stalo, když jsem pustil znova import těch samejch souborů.

PS: Píše to warning, ale import spadne, takže by to spíš měl bejt error.

**Comment by vlahoda** [comment]
@pavel-stastny 
V logu je tohle:
28-Nov-2023 15:10:57.743 INFO [cz.incad.kramerius.processes.impl.GCSchedulerImpl-thread] cz.incad.kramerius.processes.GCFindCandiatesTask.run process 0ce96e9a-8bac-4fa6-8fc4-57914cb7cb82 has no pid 
28-Nov-2023 15:10:57.749 INFO [cz.incad.kramerius.processes.impl.GCSchedulerImpl-thread] cz.incad.kramerius.processes.GCFindCandiatesTask.run process 94165335-5b9a-4a2a-b9cc-e35631d6da79 has no pid 
28-Nov-2023 15:10:57.749 INFO [cz.incad.kramerius.processes.impl.GCSchedulerImpl-thread] cz.incad.kramerius.processes.GCFindCandiatesTask.run process 7eec82f3-b3be-4409-91bd-f66ee1168e01 has no pid 
28-Nov-2023 15:10:57.749 INFO [cz.incad.kramerius.processes.impl.GCSchedulerImpl-thread] cz.incad.kramerius.processes.GCFindCandiatesTask.run process 0ff4c615-8101-4619-bed2-f88838432c35 has no pid 
28-Nov-2023 15:10:57.749 INFO [cz.incad.kramerius.processes.impl.GCSchedulerImpl-thread] cz.incad.kramerius.processes.GCFindCandiatesTask.run process fb8098b8-2532-4bdc-8b90-7c8527c47f01 has no pid 
28-Nov-2023 15:11:00.248 SEVERE [http-nio-8080-exec-4] cz.incad.kramerius.processes.impl.DatabaseProcessManager.registerLongRunningProcess ERROR: duplicate key value violates unique constraint "process_batch_pkey"
  Detail: Key (batch_token)=(47b9ba31-1901-4e56-a889-6d451eda0619) already exists.
  Where: SQL statement "INSERT into process_batch
    SELECT
        processes.token AS batch_token,
        batch_state(processes.status) AS batch_state,
        count(*) AS process_count,
        min(processes.process_id) AS first_process_id,
        min(processes.status) AS first_process_state,
        min(processes.uuid) AS first_process_uuid,
        min(processes.defid) AS first_process_defid,
        min(processes.name) AS first_process_name,
        min(processes.planned) AS planned,
        min(processes.started) AS started,
        max(processes.finished) AS finished,
        min(processes.owner_id) AS owner_id,
        min(processes.owner_name) AS owner_name
      FROM
        processes
      WHERE
        processes.token=rec.token
      GROUP BY
        processes.token
      ORDER BY
        first_process_id DESC"
PL/pgSQL function refresh_process_batch() line 17 at SQL statement
        org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "process_batch_pkey"
  Detail: Key (batch_token)=(47b9ba31-1901-4e56-a889-6d451eda0619) already exists.
  Where: SQL statement "INSERT into process_batch
    SELECT
        processes.token AS batch_token,
        batch_state(processes.status) AS batch_state,
        count(*) AS process_count,
        min(processes.process_id) AS first_process_id,
        min(processes.status) AS first_process_state,
        min(processes.uuid) AS first_process_uuid,
        min(processes.defid) AS first_process_defid,
        min(processes.name) AS first_process_name,
        min(processes.planned) AS planned,
        min(processes.started) AS started,
        max(processes.finished) AS finished,
        min(processes.owner_id) AS owner_id,
        min(processes.owner_name) AS owner_name
      FROM
        processes
      WHERE
        processes.token=rec.token
      GROUP BY
        processes.token
      ORDER BY
        first_process_id DESC"
PL/pgSQL function refresh_process_batch() line 17 at SQL statement
                at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
                at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
                at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
                at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
                at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
                at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
                at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
                at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
                at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
                at cz.incad.kramerius.processes.database.ProcessDatabaseUtils.registerProcess(ProcessDatabaseUtils.java:147)
                at cz.incad.kramerius.processes.impl.DatabaseProcessManager.registerLongRunningProcess(DatabaseProcessManager.java:126)
                at cz.incad.kramerius.processes.impl.AbstractLRProcessImpl.planMe(AbstractLRProcessImpl.java:129)
                at cz.incad.kramerius.rest.apiNew.admin.v70.ProcessSchedulingHelper.scheduleProcess(ProcessSchedulingHelper.java:69)
                at cz.incad.kramerius.rest.apiNew.admin.v70.processes.ProcessResource.scheduleProcess(ProcessResource.java:753)
                at cz.incad.kramerius.rest.apiNew.admin.v70.processes.ProcessResource.scheduleProcess(ProcessResource.java:718)

**Comment by vlahoda** [comment]
Importy v K7 obecne funguji, problem popsany v tomto issue s importem gramodesek nijak nesouvisi.

**Comment by katerinasirova** [comment]
Dobrý den, ano, importy v K7 možná obecně fungují, ale na naší instalaci je evidentně nějaký problém, který potřebujeme vyřešit. A to rychle právě proto, že do K7 potřebujeme importovat gramodesky z projektu, který je financován z programu VISK7. A tam je termín do konce roku. Děkuji.

**Comment by vlahoda** [comment]
@svetlym Procesy importu nepadaly, data se naimportovala vsechna, ale nedarilo se jim naplanovat vsechny nasledne procesy indexace, proto to je znacene jako warning. Proc se ta indexace nedarila spoustet zatim nevim. Pomohlo rozdeleni dat do mensich davek, ktere jsem importoval postupne, vsechna data z adresare .kramerius4/import jsou ted naimportovana a indexovana, zkontrolujte to prosim. Vycistil jsem take tabulky procesu, byly tam nejake nekonzistence, snad se tedy ten problem uz nebude opakovat.

**Comment by katerinasirova** [comment]
@vlahoda Díky moc, Michal Světlý má sice dovolenou, ale dám mu vědět. Kdyby se opakovalo, ozveme se.

**Comment by svetlym** [comment]
Ahoj,

přečetl jsem si, co k tomu psal Vláďa Lahoda. Je už naimportovaný 
všechno, co chybělo? Pokud ne, kde najdu zbytek?

Michal


Dne 06.12.2023 10:17, katerinasirova napsal:
