### ISSUE TITLE
K7 - chyby při indexování zvukového dokumentu

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#1070]
Testovali jsme import zvukového dokumentu (NDK balík). Import prošel, ale následná indexace hodila chyby. Jádro verze 7.0.35.

```
Jul 10, 2024 11:53:59 AM cz.kramerius.searchIndex.indexer.execution.Indexer reportError
SEVERE: object not found in repository (or found in inconsistent state), ignoring: uuid:8024b931-fb95-41bc-830f-1d94fc633dc3
object not found in repository (or found in inconsistent state), ignoring it's children: uuid:8024b931-fb95-41bc-830f-1d94fc633dc3
Jul 10, 2024 11:53:59 AM cz.kramerius.searchIndex.indexer.execution.Indexer reportError
SEVERE: object not found in repository (or found in inconsistent state), ignoring: uuid:d094180b-abb8-49df-bb2d-7af33c374097
object not found in repository (or found in inconsistent state), ignoring it's children: uuid:d094180b-abb8-49df-bb2d-7af33c374097
Jul 10, 2024 11:53:59 AM cz.kramerius.searchIndex.indexer.execution.Indexer reportError
SEVERE: object not found in repository (or found in inconsistent state), ignoring: uuid:a17d8769-a8ae-4dae-a5dd-0494f018e137
object not found in repository (or found in inconsistent state), ignoring it's children: uuid:a17d8769-a8ae-4dae-a5dd-0494f018e137
Jul 10, 2024 11:53:59 AM cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:132)
Caused by: java.lang.IllegalStateException: Indexation finished with errors; see error log
at cz.kramerius.searchIndex.indexer.execution.Indexer.indexByObjectPid(Indexer.java:145)
at cz.kramerius.searchIndex.NewIndexerProcessIndexObject.main(NewIndexerProcessIndexObject.java:129)
... 5 more
```

Odkaz na stažení NDK balíku vám pošlu do mailu.

**Comment by vlahoda** [comment]
Duplicita, resi se v #842

**Comment by svetlym** [comment]
Děkuju za informaci. Vyzkoušíme to, až to bude dodělaný.

Dobrá zpráva každopádně je, že audioserver funguje.
