### ISSUE TITLE
Problém METS konvertoru s nahráním NDK balíčku 

### ISSUE THREAD

**Issue by hosak** [ceskaexpedice/kramerius#1084]
Potřebujeme v Krameriovi nahradit stará čísla periodika s chybným OCR novými, které má OCR opravené. Při importu NDK balíčku ale Kramerius hodí chybu METS konvertoru:

zář 04, 2024 7:58:45 DOP. cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.IllegalAccessError: class org.kramerius.importmets.convertor.BaseConvertor (in unnamed module @0x3224f60b) cannot access class com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.jaxp.datatype to unnamed module @0x3224f60b
	at org.kramerius.importmets.convertor.BaseConvertor.getCurrentXMLGregorianCalendar(BaseConvertor.java:1910)
	at org.kramerius.importmets.convertor.BaseConvertor.createDublinCoreStream(BaseConvertor.java:554)
	at org.kramerius.importmets.convertor.BaseConvertor.setCommonStreams(BaseConvertor.java:377)
	at org.kramerius.importmets.convertor.BaseConvertor.createDigitalObject(BaseConvertor.java:2026)
	at org.kramerius.importmets.convertor.BaseConvertor.exportFoxml(BaseConvertor.java:2034)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.convert(MetsPeriodicalConvertor.java:72)
	at org.kramerius.importmets.MetsConvertor.convertOneDirectory(MetsConvertor.java:328)
	at org.kramerius.importmets.MetsConvertor.convert(MetsConvertor.java:194)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:119)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:115)
	at org.kramerius.importmets.MetsConvertor.main(MetsConvertor.java:66)
	at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:74)
	... 5 more

Prosíme o radu, jak číslo do Krameria dostat. 
Issue s podobným problémem se kdysi řešilo v souvislosti s K7, a to zde: https://github.com/ceskaexpedice/kramerius/issues/904

**Comment by vlahoda** [comment]
To vypada, ze proces importu je spusten  pod nejakou novejsi verzi Javy. Procesy se spousti pod defautlnim JDK, ktere je nakonfigurovane v operacnim systemu.
