### ISSUE TITLE
K7 / Selhává import PDF, který v K5 funguje

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius#1104]
Import NDK PSP s PDF nám na K7 (7.0.39) končí chybou. V K5 přitom prošel bez problému.

Jedná se o PDF, které není PDF/A - protože pokud ho převedeme na PDF/A, tak se mu ve firefoxu rozpadnou fonty, viz https://github.com/ceskaexpedice/kramerius-web-client/issues/672

Chyba: 
```
lis 18, 2024 2:50:38 ODP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font LiberationSans for Impact
lis 18, 2024 2:50:39 ODP. cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:132)
Caused by: java.lang.ExceptionInInitializerError
	at com.levigo.jbig2.JBIG2ImageReaderSpi.createReaderInstance(JBIG2ImageReaderSpi.java:118)
	at java.desktop/javax.imageio.spi.ImageReaderSpi.createReaderInstance(Unknown Source)
	at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(Unknown Source)
	at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(Unknown Source)
	at org.apache.pdfbox.filter.Filter.findImageReader(Filter.java:155)
	at org.apache.pdfbox.filter.JBIG2Filter.decode(JBIG2Filter.java:67)
	at org.apache.pdfbox.cos.COSInputStream.create(COSInputStream.java:101)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:175)
	at org.apache.pdfbox.pdmodel.common.PDStream.createInputStream(PDStream.java:243)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.createInputStream(PDImageXObject.java:933)
	at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.from1Bit(SampledImageReader.java:404)
	at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.getRGBImage(SampledImageReader.java:211)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getOpaqueImage(PDImageXObject.java:600)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:503)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:470)
	at org.apache.pdfbox.rendering.PageDrawer.drawImage(PageDrawer.java:1333)
	at org.apache.pdfbox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:67)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:959)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:532)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:507)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:151)
	at org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:292)
	at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:355)
	at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:272)
	at org.apache.pdfbox.rendering.PDFRenderer.renderImageWithDPI(PDFRenderer.java:258)
	at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:127)
	at org.kramerius.importmets.convertor.BaseConvertor.readImage(BaseConvertor.java:1947)
	at org.kramerius.importmets.convertor.BaseConvertor.addBase64Streams(BaseConvertor.java:753)
	at org.kramerius.importmets.convertor.BaseConvertor.setCommonStreams(BaseConvertor.java:391)
	at org.kramerius.importmets.convertor.BaseConvertor.createDigitalObject(BaseConvertor.java:2249)
	at org.kramerius.importmets.convertor.BaseConvertor.exportFoxml(BaseConvertor.java:2257)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.convert(MetsPeriodicalConvertor.java:64)
	at org.kramerius.importmets.MetsConvertor.convertOneDirectory(MetsConvertor.java:400)
	at org.kramerius.importmets.MetsConvertor.convert(MetsConvertor.java:277)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:217)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:213)
	at org.kramerius.importmets.MetsConvertor.run(MetsConvertor.java:161)
	at org.kramerius.importmets.MetsConvertor.main(MetsConvertor.java:137)
	... 3 more
Caused by: java.lang.IllegalArgumentException: com.levigo.jbig2.util.log.LoggerBridge is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(Unknown Source)
	at java.desktop/javax.imageio.spi.ServiceRegistry.lookupProviders(Unknown Source)
	at com.levigo.jbig2.util.ServiceLookup.getServices(ServiceLookup.java:31)
	at com.levigo.jbig2.util.log.LoggerFactory.getLogger(LoggerFactory.java:38)
	at com.levigo.jbig2.util.log.LoggerFactory.getLogger(LoggerFactory.java:50)
	at com.levigo.jbig2.JBIG2ImageReader.<clinit>(JBIG2ImageReader.java:49)
	... 41 more


```

**Comment by kerschfilip** [comment]
Doplním, že pokud stejný dokument importujeme jako FOXML, tak do K7 projde. Problém je tedy asi v NKD konvertoru?

**Comment by pavel-stastny** [comment]
@kerschfilip Nedošlo při převodu do FOXML ke konverzi obrázku ?

**Comment by kerschfilip** [comment]
@pavel-stastny předpokládám, že ne, ale můžu ověřit, co s tím ProArc vlastně dělá. 

Jen pro vysvětlení: máme prostě objekt zpracovaný v ProArcu - když se exportuje ven jako NDK PSP, tak do K7 neprojde, když bez jakékoli změny jako FOXML, tak je to OK.

**Comment by vlahoda** [comment]
@kerschfilip Prosim o ten NDK balicek, diky...

**Comment by kerschfilip** [comment]
odesláno mailem, díky
