### ISSUE TITLE
Issue 358:	Export do PDF (CD i DVD) s odhadem velikosti

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#13]
Reported by Martin.Barton@nkp.cz, Jun 22, 2012
K3 má funkcionalitu odhadu velikosti PDF. Myslím si, že by měla být k dispozici i v K4, protože je dost důležitá (a dá se to použít i jako potvrzovací dialog, který by byl při zadávání statického exportu na CD nebo DVD celkem dobrý).
Jedná-li se o velký titul a protože se PDF ukládá na server a ne někam na lokál (což by myslím bylo vhodnější), dopadne to při vyčerpání prostoru na disku takto:

INFO: i18n url =  http://localhost:8080/search//i18n?action=bundle&amp;amp;lang=cs&amp;amp;country=CZ&amp;amp;name=base
Apr 20, 2012 9:37:18 AM cz.incad.kramerius.lp.PDFExport generatePDFs
SEVERE: No space left on device
java.io.IOException: No space left on device
    at java.io.RandomAccessFile.writeBytes(Native Method)
    at java.io.RandomAccessFile.write(RandomAccessFile.java:482)
    at javax.imageio.stream.FileCacheImageOutputStream.write(FileCacheImageOutputStream.java:122)
    at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
    at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1034)
    at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:339)
    at javax.imageio.ImageWriter.write(ImageWriter.java:598)
    at javax.imageio.ImageIO.write(ImageIO.java:1479)
    at javax.imageio.ImageIO.write(ImageIO.java:1565)
    at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.writeImageToStream(KrameriusImageSupport.java:139)
    at cz.incad.kramerius.pdf.impl.AbstractPDFRenderSupport.insertJavaImage(AbstractPDFRenderSupport.java:45)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.insertImage(GeneratePDFServiceImpl.java:485)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.insertOutlinedImagePage(GeneratePDFServiceImpl.java:390)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.generateCustomPDF(GeneratePDFServiceImpl.java:151)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.fullPDFExport(GeneratePDFServiceImpl.java:286)
    at cz.incad.kramerius.lp.PDFExport.generatePDFs(PDFExport.java:220)
    at cz.incad.kramerius.lp.PDFExport.main(PDFExport.java:107)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:78)
Apr 20, 2012 9:37:18 AM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:78)
Caused by: java.io.IOException: No space left on device
    at java.io.RandomAccessFile.writeBytes(Native Method)
    at java.io.RandomAccessFile.write(RandomAccessFile.java:482)
    at javax.imageio.stream.FileCacheImageOutputStream.write(FileCacheImageOutputStream.java:122)
    at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
    at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1034)
    at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:339)
    at javax.imageio.ImageWriter.write(ImageWriter.java:598)
    at javax.imageio.ImageIO.write(ImageIO.java:1479)
    at javax.imageio.ImageIO.write(ImageIO.java:1565)
    at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.writeImageToStream(KrameriusImageSupport.java:139)
    at cz.incad.kramerius.pdf.impl.AbstractPDFRenderSupport.insertJavaImage(AbstractPDFRenderSupport.java:45)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.insertImage(GeneratePDFServiceImpl.java:485)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.insertOutlinedImagePage(GeneratePDFServiceImpl.java:390)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.generateCustomPDF(GeneratePDFServiceImpl.java:151)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.fullPDFExport(GeneratePDFServiceImpl.java:286)
    at cz.incad.kramerius.lp.PDFExport.generatePDFs(PDFExport.java:220)
    at cz.incad.kramerius.lp.PDFExport.main(PDFExport.java:107)
    ... 5 more

Jul 25, 2012 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
Neni aktualni
