### ISSUE TITLE
K5 (v. 5.0.2) - problem s javascriptem?

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#206]
Zdravim.

po upgradu K5 na verzi 5.0.2 lze pozorovat u nekterych rozsahlejsich struktur u periodik v levem stromecku problemy se zobrazenim v nekterych prohlizecich. Chyba/problem  spociva v tom, ze dojde k uplnemu vytizeni lokalniho procesoru pocitace uzivatele pri pristupu k titulu - nez se rozbali napr. prvni rocnik. V mem konkretnim pripade jsou zatizena obe jadra procesoru na 100%. Sledoval jsem soucasne vytizeni procesoru serveru a ten se ve stejnem okamziku v podstate "flaka", z cehoz usuzuji, ze jde o vykonavani javascriptu v prohlizeci uzivatele. Chrome vytizi lokalni procesor stanice na maximum, ale nakonec to "ustoji" a titul po nejake dobe zobrazi, IE a Firefox stejne vytizeni, ale krome toho take vyhodi varovnou hlasku o "neodpovidajicim skiptu". Pokud je potvrzena volba [Pockat], nasledne se strom nekdy rozbali a nekdy ne.

Priklad:
http://k4.kr-karlovarsky.cz/search/i.jsp?pid=uuid:8fb256cd-b7f5-482b-91ad-75fe89609db6#periodical-periodicalvolume-periodicalitem-page_uuid:542a99d8-e3c0-11e2-a287-0050568523b3

Chyba je pomerne neprijemna, jednak ma uzivatel pocit, ze server spadl a dale je vytizen jeho pocitac na maximum...

![kkv_02](https://cloud.githubusercontent.com/assets/8750622/5797258/b57f8ac2-9fb6-11e4-9d37-be860d78175f.png)

Diky, Duda

**Comment by vlahoda** [comment]
Problém se mi nedaří reprodukovat, načtení uvedeného URL sice trvá déle, cca 10 vteřin, ale v žádném prohlížeči nedochází k vyšší zátěži procesoru než 15%, ani k hlášení o neodpovídajícím skriptu. Domnívám se ale, že uvedený titul není správně naimportován, všechny stránky ve všech třech číslech jsou ve stromové struktuře uvedeny celekm 3x, pokaždé s jiným uuid, ale obsah je naprosto identický -předpokládám tedy, že struktura vazeb v RELS-EXT není úplně v pořádku a může způsobovat uvedené chování.

**Comment by mduda100871** [comment]
Bohuzel se instance K5 chova zvlastne i u jinych titulu. Kdyz odhledneme od vyse uvedeneho (ktery muze byt spatne naimportovany), tak jsem zkousenim zjistil, ze i dalsi tituly maji problem, ale tentokrat jen v IE (nove verze samozrejme, zkouseno na ruznych pocitacich s ruznymi verzemi OS Windows). Chyba se projevuje tak, ze klikanim v levem stromecku se nezobrazi vpravo nahled, pouze hlaska "Nahravam obrazek, prosim cekejte..." - viz screenshot v priloze. Ve firefoxu a Chromu bez problemu. V pripade techto titulu se neprojevuje zatizeni lokalniho procesoru.

![kv_02](https://cloud.githubusercontent.com/assets/8750622/5857452/371d73cc-a24c-11e4-8bd8-730a882fbc8f.png)
![kv_01](https://cloud.githubusercontent.com/assets/8750622/5857458/42e037f8-a24c-11e4-88a4-11b19a0beb6e.png)

Priklad titulu, kde se chyba v IE projevuje:

http://k4.kr-karlovarsky.cz/search/i.jsp?pid=uuid:d0c27253-e37c-49b3-ba68-0b062bb3f03e&q=&fq=dostupnost:%22public%22#monograph-page_uuid:c714e52a-c845-11e2-b493-0050568523b3

http://k4.kr-karlovarsky.cz/search/i.jsp?pid=uuid:5c03af5c-67f5-4707-a3e2-c770ae077edf&q=&fq=dostupnost:%22public%22#monograph-page_uuid:4b0dd6b0-c846-11e2-94af-0050568523b3

http://k4.kr-karlovarsky.cz/search/i.jsp?pid=uuid:1c1f3dc4-b509-4a68-8737-2e691f96ccc8&q=&fq=dostupnost:%22public%22#monograph-page_uuid:595e4706-becd-11e2-b582-0050568523b3

Sledoval jsem logy aplikace, ale zadnou relevantni informaci jsem neziskal. Pokud by to bylo zpusobeno treba pristupovymi pravy, tak by to nefungovalo v Chromu a Firefoxu...tam se ale nahled zobrazi bez problemu a hned.

Jedina "podezrela hlaska" z logu tomcatu je tato, ale cas zaznamenani nesedi s casem pristupu k objektu obrazku, takze si myslim, ze s tim nesouvisi (i s ohledem na zminku o Chromu a Firefoxu), ale pro jistotu:
...
22.1.2015 15:39:41 org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet jsp threw exception
cz.incad.kramerius.security.SecurityException: access denided
        at cz.incad.kramerius.security.SecuredFedoraAccessImpl.getDataStream(SecuredFedoraAccessImpl.java:219)
        at cz.incad.Kramerius.views.inc.details.tabs.LoadCustomViewObject.getContent(LoadCustomViewObject.java:111)
        at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:83)
        at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54)
        at org.apache.el.parser.AstValue.getValue(AstValue.java:123)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:182)
        at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:919)
        at org.apache.jsp.inc.details.tabs.loadCustom_jsp._jspService(loadCustom_jsp.java:81)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:394)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:450)
        at org.apache.coyote.ajp.AjpAprProtocol$AjpConnectionHandler.process(AjpAprProtocol.java:403)
        at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1774)
        at java.lang.Thread.run(Thread.java:662)
....

Popravde uz nevim, ceho se chytit, samotna instalace systemu je standardni, pred upgradem na 5.0.2 vse fungovalo bez problemu...

Diky, Duda

**Comment by vlahoda** [comment]
Ano, ten problém v IE11 opravdu nastává.

(Alberto, v konzoli IE11 je při otevření prvního z těch nefungujích odkazů k vidění toto: 

HTML1300: Navigation occurred.
File: i.jsp

HTML1524: Invalid HTML5 DOCTYPE. Consider using the interoperable form "<!DOCTYPE html>".
File: i.jsp, Line: 1, Column: 1

viewChanged event
changing view monograph-page_uuid:c7146ff6-c845-11e2-b493-0050568523b3
showing '#loadingDeepZoomImage'

SCRIPT1009: Expected '}'
File: jquery-1.5.1.min.js, Line: 16, Column: 13143
)

**Comment by mduda100871** [comment]
Zdravim,

chtel bych se zeptat, zda-li nastal nejaky posun v reseni vyse uvedeneho problemu? Da se ocekavat, ze krome knihovny, ktera na vyreseni ceka se objevi dalsi. Pokud by oprava trvala nejaky delsi cas, bylo by asi nutne pristoupit k downgradu na nejakou predchozi verzi...

Diky, Duda

**Comment by luckajirku** [comment]
Také bychom se přimlouvali za vyřešení, už nám to hlásí čtenáři.
