### ISSUE TITLE
K5.0.1 chyba při reindexaci všech monografií

### ISSUE THREAD

**Issue by jrihak** [ceskaexpedice/kramerius#253]
Dobrý den,

po spuštění reindexace celého modelu "monograph" (pomocí admin. menu) proces Reindex umírá s níže uvedenými chybami. Vypadá to, že Kramerius si myslí, že by měl reindexovat dokument, který již ve Fedoře není a proto umře. Snažil jsem se to napravit tím, že jsem rebuildnul Fedora Index a Fedora SQL DB (pomocí nástroje fedora-rebuild). To úplně nepomohlo, při pokusu reindexovat všechny monografie tímto způsobem celý proces umírá se stejnou chybou. 

Je nějaká cesta, jak vyloučit tento "chybový" (respektive již neexistující) objekt ze seznamu dokumentů určených k reindexaci? Jedná se například o smazání nějakých záznamů z psql db kramerius4 nebo něco takového? Nebo je problém někde úplně jinde?

Děkuji za informaci,

Jakub Řihák
NTK

===================
```
Jun 16, 2015 11:02:42 AM cz.incad.kramerius.indexer.FedoraOperations getFoxmlFromPid
SEVERE: Error getting object
javax.xml.ws.soap.SOAPFaultException: org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: no path in db registry for [uuid:ABA013-B72]
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at $Proxy34.export(Unknown Source)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
	at cz.incad.kramerius.indexer.SolrOperations.fromKrameriusModel(SolrOperations.java:351)
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:325)
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:341)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:126)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Jun 16, 2015 11:02:42 AM cz.incad.kramerius.indexer.SolrOperations krameriusModel
SEVERE: Error indexing model monograph
java.lang.Exception: Fedora Object uuid:ABA013-B72 not found. 
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:72)
	at cz.incad.kramerius.indexer.SolrOperations.fromKrameriusModel(SolrOperations.java:351)
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:325)
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:341)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:126)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Caused by: javax.xml.ws.soap.SOAPFaultException: org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: no path in db registry for [uuid:ABA013-B72]
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at $Proxy34.export(Unknown Source)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
	... 15 more
Jun 16, 2015 11:02:42 AM cz.incad.kramerius.indexer.SolrOperations updateIndex
SEVERE: Cant index. Action:krameriusModel Value: monograph
java.lang.Exception: java.lang.Exception: Fedora Object uuid:ABA013-B72 not found. 
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:334)
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:341)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:126)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Caused by: java.lang.Exception: Fedora Object uuid:ABA013-B72 not found. 
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:72)
	at cz.incad.kramerius.indexer.SolrOperations.fromKrameriusModel(SolrOperations.java:351)
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:325)
	... 13 more
Caused by: javax.xml.ws.soap.SOAPFaultException: org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: no path in db registry for [uuid:ABA013-B72]
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at $Proxy34.export(Unknown Source)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
	... 15 more
Jun 16, 2015 11:02:42 AM cz.incad.kramerius.indexer.Indexer update
SEVERE: Update failed
java.lang.Exception: java.lang.Exception: java.lang.Exception: Fedora Object uuid:ABA013-B72 not found. 
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:167)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Caused by: java.lang.Exception: java.lang.Exception: Fedora Object uuid:ABA013-B72 not found. 
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:334)
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:341)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:126)
	... 11 more
Caused by: java.lang.Exception: Fedora Object uuid:ABA013-B72 not found. 
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:72)
	at cz.incad.kramerius.indexer.SolrOperations.fromKrameriusModel(SolrOperations.java:351)
	at cz.incad.kramerius.indexer.SolrOperations.krameriusModel(SolrOperations.java:325)
	... 13 more
Caused by: javax.xml.ws.soap.SOAPFaultException: org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: no path in db registry for [uuid:ABA013-B72]
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at $Proxy34.export(Unknown Source)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
	... 15 more
Jun 16, 2015 11:02:42 AM cz.incad.kramerius.indexer.Indexer run
SEVERE: Run failed
java.lang.Exception: Index process failed
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:86)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Jun 16, 2015 11:02:42 AM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Caused by: java.lang.Exception: java.lang.Exception: Index process failed
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:95)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	... 5 more
Caused by: java.lang.Exception: Index process failed
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:86)
	... 6 more
```

**Comment by vlahoda** [comment]
Smazal jste před rebuildem resource indexu původní databázi riTriples a založil novou prázdnou?

**Comment by jrihak** [comment]
Bohužel ne... nicméně jdu to zkusit!

Děkuji!

JŘ



Dne 17. června 2015 15:03 vlahoda <notifications@github.com> napsal(a):

**Comment by jrihak** [comment]
Dobrý den,

právě jsem chtěl napsat, že děkuji, problém se podařilo vyřešit. Jednak 
tím rebuildem resource indexu a druhak vymazáním (purge) objektů, u 
kterých se vyskytl chybějící foxml objekt stránky, z Fedory.

Hezký den,

Jakub Řihák
