### ISSUE TITLE
Export do PDF

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#270]
Dobry den,
mame K4 vere 4.8.5 a pri snahach vyexportovat mono nebo perio do PDF nam to zacalo hlasit chyby.
Nejedna se o obri tituly, jsou to desitky MB, maximalne neco pres 100 MB. Dari se nam udelat export maximalne rocniku s cca 20 strankami, Kdyz to ma vic,tak nektere stranky stejne chybi. Ale ikdyz se PDF vytvori, tak proces se v K4 ukazuje, ze skoncil s chybou
1) WARNING (export rocniku)
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
Aug 07, 2015 8:57:07 AM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: system error file contains errors
cz.incad.kramerius.processes.WarningException: system error file contains errors
    at cz.incad.kramerius.processes.impl.ProcessStarter.checkErrorFile(ProcessStarter.java:183)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:125)

2) WARNING (export mono)
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?

3) WARNING (cele perio)
ile:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #66; Column #99; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
Aug 07, 2015 1:05:33 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: system error file contains errors
cz.incad.kramerius.processes.WarningException: system error file contains errors
    at cz.incad.kramerius.processes.impl.ProcessStarter.checkErrorFile(ProcessStarter.java:183)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStart

4) FAILED:
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
Aug 07, 2015 8:27:22 AM cz.incad.kramerius.lp.PDFExport generatePDFs
SEVERE: Read timed out
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1323)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
    at cz.incad.kramerius.impl.FedoraAccessImpl.getImageFULL(FedoraAccessImpl.java:427)
    at cz.incad.kramerius.impl.fedora.FedoraURLConnection.getInputStream(FedoraURLConnection.java:37)
    at java.net.URL.openStream(URL.java:1037)
    at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:63)
    at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:45)
    at cz.incad.kramerius.pdf.impl.ImageFetcher$2.fetch(ImageFetcher.java:32)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.insertImage(GeneratePDFServiceImpl.java:434)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.insertOutlinedImagePage(GeneratePDFServiceImpl.java:360)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.generateCustomPDF(GeneratePDFServiceImpl.java:137)
    at cz.incad.kramerius.pdf.impl.GeneratePDFServiceImpl.fullPDFExport(GeneratePDFServiceImpl.java:300)
    at cz.incad.kramerius.lp.PDFExport.generatePDFs(PDFExport.java:213)
    at cz.incad.kramerius.lp.PDFExport.main(PDFExport.java:105)
    at cz.incad.kramerius.lp.ParametrizedPDFExport.process(ParametrizedPDFExport.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:118)

Aug 07, 2015 8:27:22 AM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:118)
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1323)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
    at cz.incad.kramerius.impl.FedoraAccessImpl.getImageFULL(FedoraAccessImpl.java:427)
    at cz.incad.kramerius.impl.fedora.FedoraURLConnection.getInputStream(FedoraURLConnection.java:37)
    at java.net.URL.openStream(URL.java:1037)
    at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(Kramerius

**Comment by pavel-stastny** [comment]
Vyzkousime u nas, pripadne zahrneme do nasledujiciho buildu.   Vsechny veci tykajici se exportu pdf budou reseny v ramci issue #61.
