### ISSUE TITLE
Minimální verze JRE pro Krameria

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#306]
V dokumentaci https://github.com/ceskaexpedice/kramerius/wiki/Instalace se mluví o Oracle JDK 6, ale s touto není možné novou verzi Krameria zbuildit.

Dříve bylo v pom.xml přes maven definováno, že Kramerius se bude kompilovat do Javy 6 `<maven.compiler.target>1.6</maven.compiler.target>`
Tím bylo vynuceno, že se do kódu nezanese žádná nekompatibilita z vyšší verzy Javy.

Po přechodu na build pomocí gradlu už asi záleží pouze na verzi Javy, kterou má vývojář nainstalovanou. 

Řádek https://github.com/ceskaexpedice/kramerius/blob/master/common/src/main/java/cz/incad/kramerius/pdf/OutOfRangeException.java#L12 se nedá pomocí Oracle JDK 6 zkompilovat:
```
symbol  : constructor Exception(java.lang.String,java.lang.Throwable,boolean,boolean)

location: class java.lang.Exception

        super(message, cause, enableSuppression, writableStackTrace);
```
protože tento konstruktor podporuje až Java 7.

Mělo by se to opravit, nebo by bylo vhodné k popisu verze 5.2.0 připsat doporučení ohledně upgradu Javy na verzi 7 (což je ostatně rozumné, protože pro 6 nejsou už vydávané updaty).

**Comment by MartinRumanek** [comment]
Mnou popisovaná chyba byla opravena v commitu https://github.com/ceskaexpedice/kramerius/commit/2066add446422dc0bc90e43ec4b206f077d591ed

Ale při buildění přes Javu 6 se mi nyní vyskytuje tato chyba

```
* What went wrong:
Execution failed for task ':import-jaxb-dc:jaxbJaxbschemas'.
> java.lang.reflect.UndeclaredThrowableException

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':import-jaxb-dc:jaxbJaxbschemas'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: : java.lang.reflect.UndeclaredThrowableException
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:77)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:92)
	at org.gradle.XJCTask.generate(XJCTask.groovy:114)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 44 more
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy126.required(Unknown Source)
	at com.sun.tools.xjc.generator.bean.field.AbstractField.annotateReference(AbstractField.java:202)
	at com.sun.tools.xjc.generator.bean.field.AbstractField.annotate(AbstractField.java:161)
	at com.sun.tools.xjc.generator.bean.field.AbstractListField.generate(AbstractListField.java:129)
	at com.sun.tools.xjc.generator.bean.field.UntypedListField.<init>(UntypedListField.java:112)
	at com.sun.tools.xjc.generator.bean.field.UntypedListFieldRenderer.generate(UntypedListFieldRenderer.java:77)
	at com.sun.tools.xjc.generator.bean.field.DefaultFieldRenderer.generate(DefaultFieldRenderer.java:82)
	at com.sun.tools.xjc.generator.bean.BeanGenerator.generateFieldDecl(BeanGenerator.java:777)
	at com.sun.tools.xjc.generator.bean.BeanGenerator.generateClassBody(BeanGenerator.java:558)
	at com.sun.tools.xjc.generator.bean.BeanGenerator.<init>(BeanGenerator.java:261)
	at com.sun.tools.xjc.generator.bean.BeanGenerator.generate(BeanGenerator.java:169)
	at com.sun.tools.xjc.model.Model.generateCode(Model.java:290)
	at com.sun.tools.xjc.XJC2Task._doXJC(XJC2Task.java:524)
	at com.sun.tools.xjc.XJC2Task.doXJC(XJC2Task.java:457)
	at com.sun.tools.xjc.XJC2Task.execute(XJC2Task.java:380)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	... 55 more
Caused by: java.lang.NoSuchMethodException: javax.xml.bind.annotation.XmlElementRef.required()
	at com.sun.codemodel.TypedAnnotationWriter.invoke(TypedAnnotationWriter.java:112)
	... 72 more
```

**Comment by pavel-stastny** [comment]
Neni potreba to buildovat s jdk 1.6. Nastaveni pro 

Pro jakou verzi javy se ridi promennymi: 

```
sourceCompatibility = 1.6
targetCompatibility= 1.6
```

v hlavnim souboru build.gradle. Odpovida to prepinacum kompilatoru `-source` a `-target`. Je to stejny jako v pripade mavenu. 

Vami popisovana chyba odpovida nekompatibilite JAXB knihoven. V starsim JRE je pritomna verze JAXB 2.1 ale pri generovani a kompilaci jaxb stubu je potreba verze 2.2. Pokud chcete buildovat pod javou 1.6. musite pridat jaxb knihovny do adresare 
`jre/lib/endorsed`. 

V pripade krameria se jedna o nasledujici zavislosti: 

```
xjc - Xjc deps
\--- com.sun.xml.bind:jaxb-xjc:2.2.7
     \--- com.sun.xml.bind:jaxb-core:2.2.7
          +--- javax.xml.bind:jaxb-api:2.2.7
          \--- com.sun.istack:istack-commons-runtime:2.16
```


Podpora a nepodpora javy 1.6 je problematicka. Radi bychom ale bohuzel existuji jeste instance kvuli kterym musime dodrzovat zpetnou kompatibilitu.

**Comment by MartinRumanek** [comment]
Takže kompatibilita s JRE 6 je zachována, super. 

S Javou 1.6 si to nepotřebuji buildit, pouze jsem si chtěl nějakým způsobem ověřit, že nerozbiji zpětnou kompatibilitu pull-requestem, na kterém dělám. 

Díky za tip a issue je hádám vyřešeno :-)
