### ISSUE TITLE
K5.3.0 problem s automatickou indexaci po ingestu

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#331]
Zdravim,

po upgradu K5 z verze 5.2.0 na 5.3.0 nastal problem se spustenim automaticke indexace (Solr) po konverzi a importu do Fedory.

Titul se zkonvertuje a naimportuje, nicmene pokud je zaskrtnuta volba [Spustit indexacni proces], proces skonci jako FAILED. Nasledne, pokud se spusti indexace rucne pro dane UUID titulu, tak vse probehne dle ocekavani.

Chyba v catalina.log:
...
I 11, 2016 2:50:53 ODP. com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "parameters" (Class org.json.JSONObject), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@784b4b51; line: 1, column: 16] (through reference chain: org.json.JSONObject["parameters"])
        at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
        at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267)
        at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:649)
        at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:635)
        at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:1355)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:717)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
        at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1308)
        at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:419)
        at com.sun.jersey.json.impl.provider.entity.JacksonProviderProxy.readFrom(JacksonProviderProxy.java:139)
        at com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:488)
        at com.sun.jersey.server.impl.model.method.dispatch.EntityParamDispatchProvider$EntityInjectable.getValue(EntityParamDispatchProvider.java:123)
        at com.sun.jersey.server.impl.inject.InjectableValuesProvider.getInjectableValues(InjectableValuesProvider.java:46)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$EntityParamInInvoker.getParams(AbstractResourceMethodDispatchProvider.java:153)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:203)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at cz.incad.Kramerius.security.basicauth.AuthFilter.basicAuth(AuthFilter.java:111)
        at cz.incad.Kramerius.security.basicauth.AuthFilter.doFilter(AuthFilter.java:86)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:394)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:745)
...

Chyba z logu samotneho K5:
...
I 11, 2016 2:40:09 ODP. cz.incad.kramerius.service.impl.IndexerProcessStarter spawnIndexer
INFO: Spawn indexer: title: convert-converted pid: uuid:b2cdaf0d-2db7-47de-9513-f6dc9a0a5334
I 11, 2016 2:40:10 ODP. cz.incad.kramerius.service.impl.IndexerProcessStarter planIndexProcess
INFO: authToken :d8d6775f-b843-40cf-9726-7f783a8e22d0
I 11, 2016 2:40:10 ODP. cz.incad.kramerius.service.impl.IndexerProcessStarter planIndexProcess
INFO: token :5e053a18-f0e9-4065-9cdb-7d0b82a2248b
I 11, 2016 2:40:10 ODP. cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: POST http://localhost:8080/search/api/v4.6/processes?def=reindex returned a response status of 500 Internal Server Error
	at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:61)
	... 5 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: POST http://localhost:8080/search/api/v4.6/processes?def=reindex returned a response status of 500 Internal Server Error
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:558)
	at cz.incad.kramerius.service.impl.IndexerProcessStarter.planIndexProcess(IndexerProcessStarter.java:80)
	at cz.incad.kramerius.service.impl.IndexerProcessStarter.spawnIndexer(IndexerProcessStarter.java:105)
	at org.kramerius.Import.ingest(Import.java:189)
	at org.kramerius.importmets.MetsConvertor.main(MetsConvertor.java:66)
	at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:59)
	... 5 more
...

Stejne chyby se dopracuji, pokud proces zavolam prostrednictvim curl:

curl -vv -u krameriusAdmin:nejakeheslo -H "Content-Type: application/json" -d '{"parameters":["fromKrameriusModel","uuid:b2cdaf0d-2db7-47de-9513-f6dc9a0a5334"]}' -X POST http://localhost:8080/search/api/v4.6/processes?def=reindex 

Diky, Duda

**Comment by luckajirku** [comment]
A úplně stejně to (ne)funguje i při změně viditelnosti dokumentu, proces padne a je třeba zase spustit ručně indexaci, aby změna proběhla.

**Comment by FoxKyong** [comment]
Tak akorát jsem to chtěl taky už reportovat tady. Stejný problém, jenom v logu máme trochu jiný chybový výstup. V konzoli curl taky vyhodí stejný problém. Zrovna tohle je celkem závažná chyba, že vydali novou verzi bez testu.

29.12.2015 15:04:34 cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.RuntimeException: com.sun.jersey.api.client.UniformInterfaceException: POST http://localhost:8180/search/api/v4.6/processes?def=reindex returned a response status of 500 Internal Server Error
    at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:61)
    ... 5 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: POST http://localhost:8180/search/api/v4.6/processes?def=reindex returned a response status of 500 Internal Server Error
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)
    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
    at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:558)
    at cz.incad.kramerius.service.impl.IndexerProcessStarter.planIndexProcess(IndexerProcessStarter.java:80)
    at cz.incad.kramerius.service.impl.IndexerProcessStarter.spawnIndexer(IndexerProcessStarter.java:105)
    at org.kramerius.Import.ingest(Import.java:189)
    at org.kramerius.importmets.MetsConvertor.main(MetsConvertor.java:66)
    at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:59)
    ... 5 more

**Comment by pavel-stastny** [comment]
Zanesena chyba pri reseni issue #211 opravena komitem  6434fe6516835198fb177dec3690c30d66648fab 

Pripravujeme novy build.

**Comment by jrihak** [comment]
Minulý týden jsem také zkoušel verzi 5.3  a musím potvrdit stejný problém.

J.Ř.

**Comment by FoxKyong** [comment]
Tak upgradováno na verzi 5.3.1 a problém je vyřešen. Indexace už se spouští.
