### ISSUE TITLE
Chybový import u knihy dle RDA

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#344]
Pri importu jedne knihy zpracovane podle pravidel RDA konci import jako FAILED vyskakuje tato hlaska:
[Fatal Error] :36:59: The prefix &#034;xsi&#034; for attribute &#034;xsi:nil&#034; associated with an element type &#034;**mods:issuance&#034; is not bound.**
Feb 16, 2016 1:07:18 PM cz.incad.kramerius.impl.FedoraAccessImpl getBiblioMods
SEVERE: The prefix &#034;xsi&#034; for attribute &#034;xsi:nil&#034; associated with an element type &#034;mods:issuance&#034; is not bound.
org.xml.sax.SAXParseException; lineNumber: 36; columnNumber: 59; The prefix &#034;xsi&#034; for attribute &#034;xsi:nil&#034; associated with an element type &#034;mods:issuance&#034; is not bound.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at cz.incad.kramerius.utils.XMLUtils.parseDocument(XMLUtils.java:93)
	at cz.incad.kramerius.impl.FedoraAccessImpl.getBiblioMods(FedoraAccessImpl.java:198)
	at cz.incad.kramerius.indexer.ExtendedFields.setDate(ExtendedFields.java:270)
	at cz.incad.kramerius.indexer.ExtendedFields.setFields(ExtendedFields.java:97)
	at cz.incad.kramerius.indexer.SolrOperations.indexByPid(SolrOperations.java:443)
	at cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:252)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:142)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)

Feb 16, 2016 1:07:18 PM cz.incad.kramerius.indexer.SolrOperations indexByPid
SEVERE: Error indexing document uuid:fd2f7255-6b58-4ad8-843b-31ebcc60743d
java.io.IOException: org.xml.sax.SAXParseException; lineNumber: 36; columnNumber: 59; The prefix &#034;xsi&#034; for attribute &#034;xsi:nil&#034; associated with an element type &#034;mods:issuance&#034; is not bound.
	at cz.incad.kramerius.impl.FedoraAccessImpl.getBiblioMods(FedoraAccessImpl.java:204)
	at cz.incad.kramerius.indexer.ExtendedFields.setDate(ExtendedFields.java:270)
	at cz.incad.kramerius.indexer.ExtendedFields.setFields(ExtendedFields.java:97)
	at cz.incad.kramerius.indexer.SolrOperations.indexByPid(SolrOperations.java:443)
	at cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:252)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:142)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:111)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:102)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:75)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:122)
Caused by: org.xml.sax.SAXParseException; lineNumber: 36; columnNumber: 59; The prefix &#034;xsi&#034; for attribute &#034;xsi:nil&#034; associated with an element type &#034;mods:issuance&#034; is not bound.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at cz.incad.kramerius.utils.XMLUtils.parseDocument(XMLUtils.java:93)
	at cz.incad.kramerius.

Kdyz se divam do MODS (viz mets_x85), tak tam element issuance je jak u vydavatele, tak u tiskare. Jina kniha se stejnym slozenim elementu importem uz drive prosla (viz mets_x7f)

[mets_osa001-000x7f.zip](https://github.com/ceskaexpedice/kramerius/files/132522/mets_osa001-000x7f.zip)

[mets_osa001-000x85.zip](https://github.com/ceskaexpedice/kramerius/files/132425/mets_osa001-000x85.zip)

**Comment by vlahoda** [comment]
Oba přiložené METS soubory se na našem testovacím serveru naimportovaly bez problémů. Můžete prosím přiložit FOXML soubory, které při importu toho chybného balíčku vygeneroval konvertor (defaultně jsou v adresáři converted) ?

**Comment by Drahotussky** [comment]
[b4b953bb-2a85-4931-baa6-9aaef0949a49.zip](https://github.com/ceskaexpedice/kramerius/files/133954/b4b953bb-2a85-4931-baa6-9aaef0949a49.zip)

**Comment by vlahoda** [comment]
Přiložený soubor je v pořádku, identický s tím, který byl vygenerován při importu METS na našem  testovacím serveru. Podařilo se jej bez problémů naimportovat i zaindexovat (samozřejmě až na reference na neexstující objekty stránek). Váš problém nedokážu reprodukovat. Může být způsoben např. odlišnou verzí XML parseru, případně nějakými úpravami v indexační XSLT šabloně.
