### ISSUE TITLE
Po aktualizaci se neprovedla migrace databáze

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#421]
Po aktualizaci Krameria v MZK se nám log plní přiloženou hláškou. Pravděpodobně se měnilo schéma databáze a migrace se nepovedla. Přeskočili jsme verze 5.3.0, 5.3.1 a 5.3.2, ale to by dle mě nemělo být problémem.

```
SEVERE: ERROR: column p.ip_addr does not exist
  Pozice: 202
org.postgresql.util.PSQLException: ERROR: column p.ip_addr does not exist
  Pozice: 202
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:622)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:472)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:386)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at cz.incad.kramerius.utils.database.JDBCQueryTemplate.executeQuery(JDBCQueryTemplate.java:83)
	at cz.incad.kramerius.processes.impl.DatabaseProcessManager.getLongRunningProcesses(DatabaseProcessManager.java:528)
	at cz.incad.kramerius.processes.GCFindCandiatesTask.run(GCFindCandiatesTask.java:29)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

V 13, 2016 8:37:35 DOP. cz.incad.kramerius.utils.database.JDBCQueryTemplate executeQuery
SEVERE: ERROR: column p.ip_addr does not exist
  Pozice: 202
org.postgresql.util.PSQLException: ERROR: column p.ip_addr does not exist
  Pozice: 202
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:622)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:472)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:386)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at cz.incad.kramerius.utils.database.JDBCQueryTemplate.executeQuery(JDBCQueryTemplate.java:83)
	at cz.incad.kramerius.processes.impl.DatabaseProcessManager.getPlannedProcess(DatabaseProcessManager.java:404)
	at cz.incad.kramerius.processes.NextSchedulerTask.run(NextSchedulerTask.java:34)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by pavel-stastny** [comment]
Jaky byl posledni build, ktery jste meli ? ( pred migraci )

**Comment by MartinRumanek** [comment]
5.2.0, v databázi vidím 6.3.1

verze db, nevím jestli je to aktuální
```
 dbver_id |  ver  
        1 | 4.5.0
        2 | 4.9.0
        3 | 5.7.0
        4 | 6.2.0
        5 | 5.7.0
        6 | 6.2.0
        7 | 6.4.0
        8 | 6.5.0
        9 | 6.6.0
       10 | 6.6.1
       11 | 6.6.3

ale vypadá to, že ta migrace selže kvůli této chybě z logu

```
V 13, 2016 9:56:46 DOP. cz.incad.kramerius.processes.database.ProcessDatabaseInitializator initDatabase
SEVERE: ERROR: must be owner of relation processes
org.postgresql.util.PSQLException: ERROR: must be owner of relation processes
```

Permissions si upravím a snad to pomůže (issue pak zavřu).

**Comment by MartinRumanek** [comment]
Naše chyba. Databáze měla správného ownera, ale tabulky už ne.
