### ISSUE TITLE
Nevytvoření virtuální sbírky

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#442]
Dobrý den, máme K 5.3.3 a nedaří se nám založit virtuální sbírku. Po vyplnění názvu v češtině i angličtině vyskočí hlášení: error trying to create virtual collection.
Můžete nám poradit,kde je chyba, případně, kde lze nalézt log s podrobnějším popisem chyby?

Děkuji

A. Drahotušský, MSVK Ostrava

**Comment by pavel-stastny** [comment]
Chyba by mela byt videt v logu tomcatu.

**Comment by Drahotussky** [comment]
Muzete byt prosim konkretnejsi v kterem logu? Jsou tam catalina, fedora, localhost,...,ale nic v nich nevidim

**Comment by mduda100871** [comment]
Zdravim,

mame stejny problem u posledni stable verze K5. Pri pokusu zalozeni sbirky se v logu objevi nasledujici vyjimka (catalina):
...
III 17, 2017 2:38:53 ODP. cz.incad.kramerius.auth.thirdparty.ExtAuthFilter doFilter
SEVERE: Servlet execution threw an exception
javax.servlet.ServletException: Servlet execution threw an exception
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:313)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:421)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:223)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:311)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:793)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:722)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:915)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: java/util/Base64
	at cz.incad.kramerius.virtualcollections.CollectionUtils.create(CollectionUtils.java:95)
	at cz.incad.Kramerius.views.virtualcollection.VirtualCollectionServlet$Actions$7.doPerform(VirtualCollectionServlet.java:304)
	at cz.incad.Kramerius.views.virtualcollection.VirtualCollectionServlet.doGet(VirtualCollectionServlet.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	... 25 more
...

Mozna zajimavejsi je vyjimka v localhost logu:
...
III 17, 2017 2:38:53 ODP. org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet vc threw exception
java.lang.NoClassDefFoundError: java/util/Base64
        at cz.incad.kramerius.virtualcollections.CollectionUtils.create(CollectionUtils.java:95)
        at cz.incad.Kramerius.views.virtualcollection.VirtualCollectionServlet$Actions$7.doPerform(VirtualCollectionServlet.java:304)
        at cz.incad.Kramerius.views.virtualcollection.VirtualCollectionServlet.doGet(VirtualCollectionServlet.java:65)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:421)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:223)
        at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:311)
        at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:793)
        at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:722)
        at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:915)
        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
        at java.lang.Thread.run(Thread.java:745)
...

Vypada to, ze v CLASSPATH chybi knihovna pro Base64 kodovani.

MD

**Comment by vlahoda** [comment]
Ta třída Base64 totiž existuje až v Javě 8.

**Comment by mduda100871** [comment]
Aha, jasne, mame totiz nove jadro Krameria ale starsi verzi Fedory, ktera na jave 8 nebezi.

MD
