### ISSUE TITLE
K5 (5.3.4, 5.3.5) rozbite "tluste" rozhrani - asi urgentni problem

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#474]
Zdravim,

objevil se celkem neprijemny problem. Upgradoval jsem nekolik instanci Krameria na verzi 5.3.4 a jednu take na 5.3.5. Po importu dat (netyka se konkretnich titulu, na ruznych instancich Krameria, u ruznych dat, takze to asi nebude problem dat/metadat) se najednou rozsypalo "tluste" rozhrani Krameria pri pristupu ke konkretnimu titulu - viz screenshot:

![rozbite-01](https://cloud.githubusercontent.com/assets/8750622/21638072/f59ed10c-d269-11e6-8d3d-5f7f99354fd8.png)

V logu catalina.log vypadne vyjimka:
...
04-Jan-2017 10:24:14.261 SEVERE [ajp-bio-127.0.0.1-9009-exec-25] cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter An exception occurred processing JSP page /inc/details/tabs/image.jsp at line 109

106: 
107: 
108:     `<div id="securityError" class="ui-state-error-text" style="display:none;">`
109:         `${image.notAllowedMessageText}`
110:     `</div>`
111: 
112:     `<div id="loadingDeepZoomImage" class="view_div" style="display: `none;">`

Stacktrace:
 org.apache.jasper.JasperException: An exception occurred processing JSP page /inc/details/tabs/image.jsp at line 109

106: 
107: 
108:    `<div id="securityError" class="ui-state-error-text" style="display:none;">`
109:         `${image.notAllowedMessageText}`
110:     `</div>`
111: 
112:     `<div id="loadingDeepZoomImage" class="view_div" style="display: none;">`

Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:568)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:470)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:401)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:345)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:291)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.el.ELException: Error reading 'notAllowedMessageText' on type cz.incad.Kramerius.views.inc.details.tabs.ImageViewObject
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:101)
	at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:110)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:167)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:187)
	at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:933)
	at org.apache.jsp.i_jsp._jspService(i_jsp.java:2350)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	... 32 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:9180/solr/select?q=PID:"uuid:0c97c036-0a87-488f-942f-eabbd3e43c51"
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at cz.incad.kramerius.utils.RESTHelper.inputStream(RESTHelper.java:24)
	at cz.incad.kramerius.utils.solr.SolrUtils.getSolrDataInternal(SolrUtils.java:185)
	at cz.incad.kramerius.impl.SolrAccessImpl.getSolrDataDocument(SolrAccessImpl.java:59)
	at cz.incad.kramerius.impl.SolrAccessImpl.getPath(SolrAccessImpl.java:84)
	at cz.incad.Kramerius.views.inc.details.tabs.ImageViewObject.getNotAllowedMessageText(ImageViewObject.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:97)
	... 40 more

...

Vetsina instanci Krameria, kde se to objevilo, bezi na jave 8 a fedore 3.8.1, jedna instance na jave 7 a fedore 3.6.2, takze vyse uvedena chyba s verzemi JDK a fedory asi souviset nebude. Navic s verzi Krameria 5.3.3 tento problem nenastaval.

Zajimave je, ze chyba se neobjevi hned po upgradu, ale vypada to, ze az pote, co se v novejsi verzi provede import/indexace dat. Mozna se nakopne solr index?

Primy select do solru:

http://server.nekde/solr/select?q=PID:"uuid:0c97c036-0a87-488f-942f-eabbd3e43c51"

ale normalne vraci metadata - viz screenshot:

![rozbite-02](https://cloud.githubusercontent.com/assets/8750622/21638636/65cbdb30-d26c-11e6-9443-3866fe9b7112.png)

MD

**Comment by pavel-stastny** [comment]
Slo by vyzkouset co vraci primy dotaz do indexu ? 
http://localhost:9180/solr/select?q=PID:"uuid:0c97c036-0a87-488f-942f-eabbd3e43c51"

**Comment by mduda100871** [comment]
primy dotaz do indexu vraci vystup - viz screenshot v puvodni zprave, cely vypis zde:
...
`<response>`
`<lst name="responseHeader">`
`<int name="status">0</int>`
`<int name="QTime">1</int>`
`<lst name="params">`
`<str name="q">PID:"uuid:0c97c036-0a87-488f-942f-eabbd3e43c51"</str>`
`</lst>`
`</lst>`
`<result name="response" numFound="1" start="0">`
`<doc>`
`<str name="PID">uuid:0c97c036-0a87-488f-942f-eabbd3e43c51</str>`
`<date name="created_date">2016-10-20T14:05:56.475Z</date>`
`<int name="datum_begin">0</int>`
`<int name="datum_end">0</int>`
`<str name="datum_str">1964-</str>`
`<arr name="dc.identifier">`
`<str>uuid:0c97c036-0a87-488f-942f-eabbd3e43c51</str>`
`<str>ccnb:cnb000356317</str>`
`<str>issn:0014-1291</str>`
`<str>issn-l:0014-1291</str>`
`<str>0c97c036-0a87-488f-942f-eabbd3e43c51</str>`
`<str>cnb000356317</str>`
`<str>0014-1291</str>`
`<str>0014-1291</str>`
`</arr>`
`<str name="dc.title">`
Estetika: the Central European Journal of Aesthetics
`</str>`
`<str name="ddt"/>`
`<arr name="document_type">`
`<str>title</str>`
`<str>periodical</str>`
`<str>časopisy</str>`
`<str>journals</str>`
`<str>text</str>`
`<str>periodical</str>`
`</arr>`
`<str name="dostupnost">private</str>`
`<str name="fedora.model">periodical</str>`
`<str name="handle"/>`
`<str name="issn">0014-1291</str>`
`<arr name="keywords">`
`<str>Umění</str>`
`<str>teorie umění</str>`
`<str>estetika</str>`
`<str>theory of art</str>`
`<str>aesthetics</str>`
`</arr>`
`<int name="level">0</int>`
`<str name="mdt">7.01/09</str>`
`<arr name="model_path">`
`<str>periodical</str>`
`</arr>`
`<date name="modified_date">2016-12-06T09:20:24.542Z</date>`
`<int name="pages_count">0</int>`
`<arr name="parent_pid">`
`<str>uuid:0c97c036-0a87-488f-942f-eabbd3e43c51</str>`
`</arr>`
`<arr name="pid_path">`
`<str>uuid:0c97c036-0a87-488f-942f-eabbd3e43c51</str>`
`</arr>`
`<arr name="rels_ext_index">`
`<int>0</int>`
`</arr>`
`<int name="rok">0</int>`
`<str name="root_pid">uuid:0c97c036-0a87-488f-942f-eabbd3e43c51</str>`
`<str name="root_title">`
Estetika: the Central European Journal of Aesthetics
`</str>`
`<str name="status">Active</str>`
`<arr name="text">`
`<str>`
Estetika: the Central European Journal of Aesthetics
`</str>`
`<str>Umění</str>`
`<str>teorie umění</str>`
`<str>estetika</str>`
`<str>theory of art</str>`
`<str>aesthetics</str>`
`<str>0014-1291</str>`
`</arr>`
`<str name="title_sort">ESTETIKA</str>`
`<bool name="virtual">false</bool>`
`</doc>`
`</result>`
`</response>`

MD

**Comment by mduda100871** [comment]
Docasne reseni problemu spociva "vlozit" mezi jadro krameria a solr index apache + mod_proxy(_ajp). Existuje podezreni (neoverene), ze to souvisi s upgradem tomcatu(7/8).

Priklad konfigurace

apache (999-localhost.conf):
...
`<IfModule mod_proxy_ajp.c>`
`ProxyRequests Off`
`<Proxy ajp://127.0.0.1:9109>`
`Require all granted`
`</Proxy>`
`<Location /solr>`
`Require all denied`
`Require ip 127.0.0.1/32`
`ProxyPass ajp://127.0.0.1:9109/solr/ retry=5`
`ProxyPassReverse ajp://127.0.0.1:9109/solr/`
`</Location>`
`</IfModule>`
...

kramerius (configuration.properties):
...
`_solrTomcatHost=http://localhost`
`solrHost=${_solrTomcatHost}/solr`
...

**Comment by MartinRumanek** [comment]
V MZK se nám tato chyba nevyskytuje.

Tomcat: 8.0.39
Java: 8u112-b15
Fedoru máme taky 3.8.1, Kramerius 5.3.6


Kramerius je napojený na SOLR napřímo.

**Comment by mjtecka** [comment]
Zdravím,

narazil jsem na stejnou věc v nové instalaci; současně mám problém s importem dokumentů. Oboje padá na podobném dotazu:

image.jsp:
```Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:8080/solr/select?q=PID:"uuid:1c36fa50-dfde-49d9-be85-279881ee6c59"```

indexace z foxml (výpis v rozhraní Krameria):
```
SEVERE: Cant index. Action:reindexDoc Value: uuid:1c36fa50-dfde-49d9-be85-279881ee6c59
java.lang.Exception: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:8080/solr/select/?q=PID:&#034;uuid:1c36fa50-dfde-49d9-be85-279881ee6c59&#034;
	at cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:255)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:142)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:117)
```

Ten druhý výpis je z rohraní Krameria - místo uvozovek je tam použit numeric character reference `&#034;` - jeho přítomnost v dotazu dokáže způsobit chybu 400. Mimochodem, když otevřu fyzický soubor s chybovou hláškou na serveru, vidím tam normální uvozovky:

(výpis přímo lrErr/sterr.err)
```
SEVERE: Cant index. Action:reindexDoc Value: uuid:1c36fa50-dfde-49d9-be85-279881ee6c59
java.lang.Exception: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:8080/solr/select/?q=PID:"uuid:1c36fa50-dfde-49d9-be85-279881ee6c59"
```

Pokud spustím dotaz s normálními uvozovkami, funguje.

Je možné, že nový Tomcat přepíše v URL `"` na `&#034;` čemuž pak SOLR nerozumí? 

Tomcat 7.0.69
Java 1.8.0_131
Fedora 3.8.1
Kramerius 5.3.6 (ale stejně se choval i 5.3.4, kterým jsem ho zkoušel nahradit)

**Comment by MartinRumanek** [comment]
'&#034;' je HTML entita, to Tomcat nebude přepisovat v URL - spíš se ta URL převede do entit při zobrazování chyby v Krameriu, to ničemu nevadí. Jestli se vám to děje jen u jednoho tohoto konkrétního dokumentu (uuid:1c36fa50-dfde-49d9-be85-279881ee6c59), tak je možná chyba přímo v něm.

Pokud děláte novou instalaci, doporučuji rovnou použít SOLR 6 (který se už ale přímo do Tomcatu neinstaluje)
viz https://github.com/ceskaexpedice/kramerius/wiki/P%C5%99echod-na-novou-verzi-SOLR

**Comment by mjtecka** [comment]
Myslím, že už mám vysvětlení konzistentní s tím co jsem pozoroval:

Tomcat přestal přijímat dvojité uvozovky (**"**) v URL. Problém není v tom, že by se něco přepisovalo, ale spíš naopak v tom, že se nic nepřepisuje a lp procesy Krameria používají dotazy přímo ve formě 
`http://localhost:8080/solr/select?q=PID:"uuid:0c97c036-0a87-488f-942f-eabbd3e43c51"`
a nikoli
`http://localhost:8080/solr/select?q=PID:%22uuid:0c97c036-0a87-488f-942f-eabbd3e43c51%22`

Tomcat 8.0.30 (starší verze, než začali řešit znaky které podle RFC nepatří do URL):
```
curl -X HEAD -i  'http://localhost:8080/solr/select?q=PID:"uuid:1c36fa50-dfde-49d9-be85-279881ee6c59"'
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/xml;charset=UTF-8
Content-Length: 0
Date: Tue, 30 May 2017 15:28:13 GMT
```

Tomcat 7.0.69 (nižší verze, ale novější než Tomcat 8 výše):
```
 curl -X HEAD -i  'http://localhost:8080/solr/select?q=PID:"uuid:1c36fa50-dfde-49d9-be85-279881ee6c59"'
HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
Date: Tue, 30 May 2017 15:28:02 GMT
Connection: close
```
 
s %22 ale dotaz na Tomcatu 7.0.69 funguje:
```
curl -X HEAD -i  'http://localhost:8080/solr/select?q=PID:%22uuid:1c36fa50-dfde-49d9-be85-279881ee6c59%22'
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/xml;charset=UTF-8
Content-Length: 0
Date: Tue, 30 May 2017 15:52:01 GMT
```


- řešení které popisuje @mduda100871 prožene dotaz přes Apache, takže se uvozovky upraví (zřejmě na %22)
- použítí samostantého SOLRu to může taky vyřešit, pokud nemá nový SOLR takové striktní požadavky na znaky v URL
- teorie s `&#034;` je chybná, @MartinRumanek má pravdu :-)

Na druhou stranu tady Kramerius vytváří URL, které, jestli to dobře chápu, neodpovídají RFC a Tomcat už je nebude zpracovávat. Je otázka, jak dlouho to bude dělat standalone SOLR. Asi by stálo za to to upravit v kódu.
