### ISSUE TITLE
Hromadné mazání procesů vrací chybu 403 Forbidden

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius#476]
Dobrý den,
mám prosbu o radu. Poslední dobou se zpomalilo načítání správy procesů v administrátorském rozhraní (obyčejně trvá déle jak 3 minuty). Vše ostatní (importy, prohlížení dokumentů, mazání procesů) funguje bez zdržení tak mě napadlo, že by stálo za to promazat správu procesů zda to pomůže.

Nicméně pokud spustím mazání procesů tak se objeví status failed. Výpis z logu:

```
Jan 9, 2017 10:31:02 AM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:118)
Caused by: com.sun.jersey.api.client.UniformInterfaceException: GET http://k4.techlib.cz/search/api/v4.6/processes?offset=4173 returned a response status of 403 Forbidden
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
	at cz.incad.kramerius.processes.manages.DeleteProcesses.list(DeleteProcesses.java:75)
	at cz.incad.kramerius.processes.manages.DeleteProcesses.deleteProcesses(DeleteProcesses.java:178)
	... 5 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: DELETE http://k4.techlib.cz/search/api/v4.6/processes/bda82ded-4d15-4ce8-98d8-49891440be3a returned a response status of 500 Internal Server Error
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.delete(WebResource.java:589)
	at cz.incad.kramerius.processes.manages.DeleteProcesses.deleteProcesses(DeleteProcesses.java:186)
	... 5 more
```

Normálně bych hledal v konfiguraci kde je chyba s příst. právy. Nicméně pokud smažu proces přímo ve správě, tak vše proběhne hladce. Verze krameria: 5.2.0

Jan Dobiášovský
NTK

**Comment by pavel-stastny** [comment]
Je videt nejaka chyba v catalina.out?

**Comment by jdobiasovsky** [comment]
Tyto dvě hlášky s tím jsou nejspíše spojené. Jinak v příloze ještě celý výpis z logu pro daný proces

```
INFO: [] webapp=/solr path=/select params={rows=10000&q=parent_pid:"uuid:8964f5ed-60bc-11e3-984f-001b63bd97ba"+AND+                                                                                                                          NOT(PID:"uuid:8964f5ed-60bc-11e3-984f-001b63bd97ba")&fq=NOT(PID:uuid\:8964f5ed-60bc-11e3-984f-001b63bd97ba/@*)} hit                                                                                                                          s=0 status=0 QTime=0
SystemId Unknown; Line #6; Column #7; stylesheet requires attribute: version
[Fatal Error] :128:3: The element type "link" must be terminated by the matching end-tag "</link>".
SystemId Unknown; Line #128; Column #3; org.xml.sax.SAXParseException: The element type "link" must be terminated b                                                                                                                          y the matching end-tag "</link>".
SystemId Unknown; Line #6; Column #7; stylesheet requires attribute: version
```

A pak ještě:

```
SEVERE: ERROR: update or delete on table "processes" violates foreign key constraint "process_2_token_process_id_fk                                                                                                                          ey" on table "process_2_token"
  Detail: Key (process_id)=(2360) is still referenced from table "process_2_token".
```

[catalina_out_vypis.txt](https://github.com/ceskaexpedice/kramerius/files/696160/catalina_out_vypis.txt)

**Comment by pavel-stastny** [comment]
Nedari se nam situaci navodit.
