### ISSUE TITLE
Issue 387:	editor uživatelů - vytvoření uživatele bez vyplnění jména

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#49]
Reported by Martin.Rehanek, Aug 7, 2012
Při vytvoření nového uživatele přes rightseditor není nutné vyplnit jméno a příjmení. 
Pokud jméno chybí, editor se tváří, že uživatel vytvořen byl a je mu zaslán email obsahující vygenerované heslo. To ale nefunguje, jelikož záznam uživatele vytvořen nebyl (ověřeno v databázi) a jediná informace o tom je v logu catalina.out, který vypadá takto:
7.8.2012 11:29:00 org.apache.empire.exceptions.EmpireException log
INFO: An Error occured. Message is: The field USER_ENTITY.NAME must not be null.
7.8.2012 11:29:00 org.aplikator.server.rpc.handler.ProcessRecordsHandler execute
SEVERE: Error in processing records:
org.apache.empire.db.exceptions.FieldNotNullException: The field USER_ENTITY.NAME must not be null.
	at org.apache.empire.db.DBRowSet.updateRecord(DBRowSet.java:695)
	at org.apache.empire.db.DBRecord.update(DBRecord.java:683)
	at org.aplikator.server.persistence.empiredb.EmpireDbPersister.updateRecord(EmpireDbPersister.java:647)
	at org.aplikator.server.rpc.handler.ProcessRecordsHandler.execute(ProcessRecordsHandler.java:59)
	at org.aplikator.server.rpc.handler.ProcessRecordsHandler.execute(ProcessRecordsHandler.java:1)
	at org.aplikator.server.rpc.AplikatorServiceImpl.execute(AplikatorServiceImpl.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:563)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:554)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:421)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Unknown Source)

Pole jméno, příjmení a organizace by buď neměly být povinné, anebo by jejich vyplnění mělo být kontrolováno jak na klientovi (js v prohlížeči), tak na straně serveru a v případě chybějících povinných dat by měla uživatele informovat chybová hláška.

Ona se dokonce nekontroluje ani vyplněnost loginu (a beztak emailu). Pokud jsem vyplnil jen email, editor se tvářil, jako by uživatele vytvořil a přišel mi tento email:
Vážený uživateli, null vaše vygenerované heslo je: heWZLWLV

Aug 11, 2012 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: Accepted 
Owner: vlahoda 
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Labels: -Priority-Low Priority-Medium

**Comment by vlahoda** [comment]
Upraveno: login je povinný a jedinečný, jméno, příjmení a organizace nepovinné.
Je třeba doplnit aktualizační skript databáze - před přidáním jedinečnosti indexu pro login je potřeba smazat případné existující záznamy s duplicitním loginem.
