### ISSUE TITLE
Kramerius přistupuje na neexistující uuid:1

### ISSUE THREAD

**Issue by xburda4** [ceskaexpedice/kramerius#498]
Kramerius pristupuje na neexistujúce "http://.../fedora/get/uuid:1/RELS-EXT". To potom vyhodí FileNotFound exception. Najdôležitejšia časť stacktrace bude asi:
...
at cz.incad.kramerius.security.SecuredFedoraAccessImpl.getKrameriusModelName(SecuredFedoraAccessImpl.java:315)
	at cz.incad.kramerius.security.impl.criteria.BenevolentModelFilter.evaluateInternal(BenevolentModelFilter.java:60)
	at cz.incad.kramerius.security.impl.criteria.NegativeBenevolentModelFilter.evalute(NegativeBenevolentModelFilter.java:36)
	at cz.incad.kramerius.security.impl.RightImpl.evaluate(RightImpl.java:107)
	at cz.incad.kramerius.security.impl.DatabaseRightsManager.resolve(DatabaseRightsManager.java:261)
	at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequest.isAllowedInternalForFedoraDocuments(IsActionAllowedFromRequest.java:112)
	at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequest.isActionAllowed(IsActionAllowedFromRequest.java:81)
	at cz.incad.kramerius.security.impl.http.AbstractLoggedUserProvider.saveRightsIntoSession(AbstractLoggedUserProvider.java:123)
	at cz.incad.kramerius.security.impl.http.DbCurrentLoggedUser.tryToLogDB(DbCurrentLoggedUser.java:114)
	at cz.incad.kramerius.security.impl.http.DbCurrentLoggedUser.tryToLog(DbCurrentLoggedUser.java:86)
	at cz.incad.kramerius.security.impl.http.AbstractLoggedUserProvider.get(AbstractLoggedUserProvider.java:86)
	at cz.incad.kramerius.security.impl.http.AbstractLoggedUserProvider.get(AbstractLoggedUserProvider.java:49)
...

Asi to bude tak, že pri kontrole práv prihláseného uživateľa kramerius zavolá túto metódu https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/common/src/main/java/cz/incad/kramerius/security/impl/http/AbstractLoggedUserProvider.java#L123, ktorá odkazuje na SpecialObject https://github.com/ceskaexpedice/kramerius/blob/6d255fe3112f93104863695d46c21751f67a05b5/common/src/main/java/cz/incad/kramerius/security/SpecialObjects.java#L27, odkial sa teda zoberie "uuid:1".

**Comment by xburda4** [comment]
Rieši commit 7e40df19f00287aa1506f291cab6f8aeb659510e
