### ISSUE TITLE
Nejde stáhnout 'originál' obrázek dokumentu při velikosti nad 20 Mpix

### ISSUE THREAD

**Issue by FoxKyong** [ceskaexpedice/kramerius#499]
Když chci stáhnout obrázek - v menu 'stáhnout originál' položka, tak pokud máš obrázek vyšší rozlišení než 20 Mpix (úplně přesně, kolik to je, nevím), tak Kramerius hodí chybu:
```
500 Internal server error
```
Pokud ten zdrojový obrázek v imageserveru změnším na 20 a méně Mpix, tak obrázek již stáhnout jde.

K tomu mám další problém, proč to vlastně tak dělá a jmenuje se to 'Stáhnout originál', když originál je ten obrázek jp2, ale stáhnutí se ho snaží nějak zvláštně změnit asi, že to na tom hodí tu chybu, a na stáhnutí to nabízí vždy jpg. To pak není originál, ale už převedený obrázek do jpg z originálu jp2.

**Comment by pavel-stastny** [comment]
A v logu tomcatu se neco objevuje? 

Ad original. Stahuje to to, co je ulozeno ve streamu IMG_FULL streamu. (Coz by mel byt original  nebo pripadne co nejvernejsi kopie.)   JP2 soubory byvaji ulozeny vetsinou mimo krameria. (V rezii IIP serveru)

**Comment by FoxKyong** [comment]
Objeví se tohle:
```
INFO: [] webapp=/solr path=/select params={q=PID:"uuid:d9067301-2cb5-11e6-8bbb-90b11c419e63"} hits=1 status=0 QTime=0 
30.3.2017 15:16:24 cz.incad.Kramerius.imaging.ImageStreamsServlet doGet
SEVERE: null
cz.incad.kramerius.FedoraIOException
        at cz.incad.kramerius.impl.FedoraAccessImpl.getDataStream(FedoraAccessImpl.java:914)
        at cz.incad.kramerius.security.SecuredFedoraAccessImpl.getDataStream(SecuredFedoraAccessImpl.java:228)
        at cz.incad.Kramerius.imaging.ImageStreamsServlet$Actions$3.doPerform(ImageStreamsServlet.java:260)
        at cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet(ImageStreamsServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:465)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:394)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:299)
        at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
        at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
        at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769)
        at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)
        at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)
        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
        at java.lang.Thread.run(Thread.java:662)
```

**Comment by pavel-stastny** [comment]
Prijde mi to jako chyba pri komunikaci s fedorou (nebo pripadne IIP serverem).  Kdyz pristopite na stream primo pomoci fedory, data dostanete (http://<fedora_host>/fedora/objects/<uuid>/datastreams/IMG_FULL/content) ?

A pokud ne, zkusil bych jeste zda je podvava IIP server.

**Comment by FoxKyong** [comment]
Taky nejde. Ale tam bude možná nějaký i problém celkově u typů jp2? Já totiž tyhle obrázky neotevřu ani na počítači, kcyž je mám zkopírované ze serveru. Jdou převést pomocí ImageMagick třeba, ale otevřít na prohlídnutí už nejdou. Až když je zmenším na těch 20 Mpix. Takže se to u mě na pc chová stejně jako u Krameria, to vypadá.

**Comment by MartinRumanek** [comment]
@FoxKyong Jak je psáno nahoře JPEG2000 budeš mít v režii imageserveru, Kramerius s němi nedělá nic.

Nejspíš máš  ten JPEG2000 obrázek rozbitý (resp. některá z jeho vrstev) nebo to taky může být způsobené starší verzí imageserveru, kterou tam zřejmě máš.

**Comment by slapakovai** [comment]
@FoxKyong Prosím o zprávu, jestli problém se stažením originálu ještě přetrvává.

**Comment by FoxKyong** [comment]
Problém zatím přetrvává. Jaká je minimální verze imageserveru, která by to měla zvládat? Jinak jsem to vždy convertovat hromadně se spoustou dalších obrázků a ty jsou v pořádku. Vždy se to projeví pouze u těch konkretních, co přesahují to rozlišení.

**Comment by MartinRumanek** [comment]
@FoxKyong Můžeš ten obrázek prosím poslat do MZK?

Jinak nic jako minimální verze Imageserveru neexistuje, Kramerius na verzi není nijak závislý.

**Comment by jakubblecha** [comment]
Dobrý den,

kolega Jakub Blecha od 1.5.2017 nepracuje na FSV UK. Můžete prosím do
mailing listu zařadit na jeho místo nového kolegu Jakuba Bjačka a mne?
E-mailové adresy:
jakub.bjacek@fsv.cuni.cz
sylvie.krizova@fsv.cuni.cz

Děkuji,
S pozdravem,

Sylvie Křížová
Středisko vědeckých informací

Fakulta sociálních věd
Univerzita Karlova v Praze
Smetanovo nábř. 6, 110 01 Praha 1
Tel.: +420 222 112 250
E-mail: jakub.blecha@fsv.cuni.cz



2017-05-09 7:51 GMT+02:00 Martin Rumanek <notifications@github.com>:

**Comment by vlahoda** [comment]
Pokud se chcete přihlásit do mail listu Kramerius, použijte prosím formulář na adrese https://mailman.lib.cas.cz/mailman/listinfo/kramerius 
Pokud chcete sledovat issues zde na GitHubu, zřiďte si prosím pro Vaše adresy účty na GitHubu a přihlašte se k notifikaci o změnách v požadovaných issues.
