### ISSUE TITLE
DATASTREAM CONTROL_GROUP=R pro IMG_FULL, IMG_THUMB

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#531]
Kramerius 5.3.4
Narazil jsem na dvě situace, kdy Kramerius nenákládá korektně s datastreamy IMG_FULL a IMG_THUMB typu R (_Redirected Referenced Content_). Tenhle způsob přístupu k datastreamům je trochu šetrnější k Fedoře, protože data netečou přes Fedoru transparentně pro klienta (jako u asi častějšího E - _Externally Referenced Content_), ale klient dostane 302 redirect. A vypadá to, že s tím Kramerius neumí pracovat. 
Typy datastreamů jsou popsány na https://wiki.duraspace.org/display/FEDORA38/FOXML+Reference+Example.
 
## 1. IMG_FULL ##
pokud např. není dostupný soubor ImageProperties.xml, klienti se typicky pokouší získat celý obrázek z IMG_FULL nějak takhle:
```
/search/img?pid=uuid:54d51cde-e9fa-43e3-a69a-8d3de6703e30&stream=IMG_FULL
```
Kramerius dále zavolá 
```
/fedora/get/uuid:54d51cde-e9fa-43e3-a69a-8d3de6703e30/IMG_FULL
```
což ale v tomhle případě nevrátí 200 a samotný obrázek stránky, ale 302 a URL na obrázek
```
89.102.3.63 - - [15/Jun/2017:02:11:58 +0200] "GET /fedora/get/uuid:54d51cde-e9fa-43e3-a69a-8d3de6703e30/IMG_FULL HTTP/1.1" 302 459 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36"
```
Následně je vyhozena vyjimka:
```
15-Jun-2017 02:15:11.561 SEVERE [ajp-nio-8009-exec-24] cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet 404
 java.io.IOException: 404
	at cz.incad.kramerius.impl.FedoraAccessImpl.getImageFULL(FedoraAccessImpl.java:404)
	at cz.incad.kramerius.security.SecuredFedoraAccessImpl.getImageFULL(SecuredFedoraAccessImpl.java:96)
	at cz.incad.kramerius.impl.fedora.FedoraURLConnection.getInputStream(FedoraURLConnection.java:36)
	at java.net.URL.openStream(URL.java:1045)
	at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:80)
	at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:52)
	at cz.incad.Kramerius.AbstractImageServlet.rawImage(AbstractImageServlet.java:149)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet.access$100(ImageStreamsServlet.java:51)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet$Actions$1.doPerform(ImageStreamsServlet.java:219)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet(ImageStreamsServlet.java:150)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```
A klient dostane 500 - internal error. 
Protože řádky 400-405 v https://github.com/ceskaexpedice/kramerius/blob/master/common/src/main/java/cz/incad/kramerius/impl/FedoraAccessImpl.java
```
if (con.getResponseCode() == HttpURLConnection.HTTP_OK) {
   InputStream thumbInputStream = con.getInputStream();
   return thumbInputStream;
} else {
   throw new IOException("404");
}
```
## 2. IMG_THUMB ##
Podobná situace, ale překvapivě se to chová trochu jinak.
```
GET /search/img?pid=uuid:60c4e3a4-37db-4404-b5c2-caea8bd3e8af&stream=IMG_THUMB
```
Výsledek: 501 - not implemented 
a v logu chyba:
```
15-Jun-2017 02:37:22.197 SEVERE [ajp-nio-8009-exec-17] cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet image == null!
 java.lang.IllegalArgumentException: image == null!
	at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925)
	at javax.imageio.ImageIO.getWriter(ImageIO.java:1592)
	at javax.imageio.ImageIO.write(ImageIO.java:1578)
	at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.writeImageToStream(KrameriusImageSupport.java:141)
	at cz.incad.Kramerius.AbstractImageServlet.writeImage(AbstractImageServlet.java:159)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet.access$400(ImageStreamsServlet.java:51)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet$Actions$1.doPerform(ImageStreamsServlet.java:222)
	at cz.incad.Kramerius.imaging.ImageStreamsServlet.doGet(ImageStreamsServlet.java:150)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```
Navíc matoucí je ještě toto:
```
GET /search/img?pid=uuid:60c4e3a4-37db-4404-b5c2-caea8bd3e8af&stream=IMG_THUMB&action=GETRAW
```
Což vrátí http kód 200 ale tělo s prázdným obsahem.

## Shrnutí ##
Takže kromě toho, že se pro _Redirected Referenced Content_ nikdy nevrací obsah, tak jsou nekonzistentní http kódy a vyjimky v logu.
```
/search/img?pid=uuid:60c4e3a4-37db-4404-b5c2-caea8bd3e8af&stream=IMG_FULL
500, IOException: 404

/search/img?pid=uuid:60c4e3a4-37db-4404-b5c2-caea8bd3e8af&stream=IMG_FULL&action=GETRAW
501, NullPointerException

/search/img?pid=uuid:60c4e3a4-37db-4404-b5c2-caea8bd3e8af&stream=IMG_THUMB
501, IllegalArgumentException: image == null!

/search/img?pid=uuid:60c4e3a4-37db-4404-b5c2-caea8bd3e8af&stream=IMG_THUMB&action=GETRAW 
200, ale Content-Length:0
```

**Comment by MartinRumanek** [comment]
Kramerius si s 302 od Fedory poradí. 

Interně se používá HttpURLConnection a ten by redirecty měl následovat. Konfiguruje se to systémovou proměnnu `http.maxRedirects` defaultní hodnota je 20, takže pokud není přepsaná mělo by to fungovat.

Ještě je možné, že se ty redirecty chovají špatně při použití TLS. Nemáš náhodou Fedoru nebo ten referencovaný obsah na `https`?

**Comment by rzeh4n** [comment]
Opravdu je to v https, konkrétně proměnná _fedoraTomcatHost v configuration.properties, resp. property fedoraHost. Když to změním na http všechno funguje i s CONTROL_GROUP=R. Takže zatím budu dál provozovat Fedoru i na http, což stejně potřeba kvůli meditoru.
