### ISSUE TITLE
Kramerius 6 - nefunguje replikace

### ISSUE THREAD

**Issue by dsecik** [ceskaexpedice/kramerius#584]
#### K4 replikace
Po vyplneni a potvrdeni formulara sa proces vobec nenaplanuje.

```
line 1:3: unexpected token: null
line 1:3: expecting RPAREN, found 'null'
23-Feb-2018 12:32:25.824 WARNING [http-nio-8080-exec-5] cz.incad.Kramerius.LongRunningProcessServlet.getParamsMapping skipping param mapping pair '[]'
23-Feb-2018 12:32:38.658 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
 at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:460)
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:383)
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 at java.lang.Thread.run(Thread.java:748)
```
#### Replikace dat (Kramerius -> Kramerius)
Chcel by som sa spytat ako ma vyzerat parameter **K4 handle** a ci je mozne pomocou tohto procesu replikovat zo starsich verzii krameria. 

Pri pokuse replikovat z nasho krameria (5.3.9) K4 hadle: `https://kramerius.mzk.cz/search/ ` sa proces naplanuje, dlhodobo je v stave running ale podla logov krameria, fedory a solru sa nic nedeje. V logoch procesu je toto: 
```
Feb 23, 2018 1:19:58 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-mets-6.0.0-alpha&#039; to &#039;migration.properties&#039;
Feb 23, 2018 1:19:58 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;static-export-6.0.0-alpha&#039; to &#039;static_export.properties&#039;
Feb 23, 2018 1:19:58 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;indexer-6.0.0-alpha&#039; to &#039;indexer.properties&#039;
Feb 23, 2018 1:19:58 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;common-6.0.0-alpha&#039; to &#039;configuration.properties&#039;
Feb 23, 2018 1:19:58 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-cmdtool-6.0.0-alpha&#039; to &#039;migration.properties&#039;
Feb 23, 2018 1:19:58 PM cz.incad.kramerius.processes.starter.ProcessUpdatingChannel$StandardProcessUpdatingChannel updateName
INFO: requesting url :http://localhost:8080/search//lr?action=updateName&amp;uuid=36066af3-f8f4-4b84-88b2-467ec20b0321&amp;name=Replikace+%27https%3A%2F%2Fkramerius.mzk.cz%2Fsearch%2F%27
Feb 23, 2018 1:19:58 PM org.kramerius.replications.K4ReplicationProcess start
INFO: STARTING PHASE &#039;org.kramerius.replications.ZeroPhase&#039;
Feb 23, 2018 1:19:58 PM org.kramerius.replications.ZeroPhase validate
WARNING: Cannot replicate virtual collections; invalid version on the source [5, 3, 9]
Feb 23, 2018 1:19:58 PM org.kramerius.replications.K4ReplicationProcess phaseCompleted
INFO: PHASE &#039;org.kramerius.replications.ZeroPhase&#039; completed
Feb 23, 2018 1:19:58 PM org.kramerius.replications.K4ReplicationProcess start
INFO: STARTING PHASE &#039;org.kramerius.replications.IterateThroughIndexPhase&#039;

```

**Comment by pavel-stastny** [comment]
Dobry den, 

> **K4 replikace**
Po vyplneni a potvrdeni formulara sa proces vobec nenaplanuje.

Chyba s replikaci uz byla hlasena a bude opravena dalsi verzi. 

> **Replikace dat (Kramerius -> Kramerius)**
Chcel by som sa spytat ako ma vyzerat parameter K4 handle a ci je mozne pomocou tohto procesu replikovat zo starsich verzii krameria.

Ano, to je v poradku 

> Pri pokuse replikovat z nasho krameria (5.3.9) K4 hadle: https://kramerius.mzk.cz/search/ sa proces naplanuje, dlhodobo je v stave running ale podla logov krameria, fedory a solru sa nic nedeje. V logoch procesu je toto:

V teto casti nacita nacita data z indexu a pripravuje si seznam PIDu pro replikaci.  Muze to trvat delsi dobu v zavislosti na poctu dokumentu.

**Comment by pavel-stastny** [comment]
Ještě jsem chtěl dodat, že u tak velkého repozitáře bych nedoporučoval použít Replikaci dat Kramerius - Kramerius. Pokud provozujete Kram 6 na linuxu, pak bych doporučil standardní Import FOXML objektů. Pokud ne, vyčkejte prosím na příští verzi. Vyjde příští týden.

**Comment by zabak** [comment]
Zatím šlo o testy na malém počtu dokumentů.

**Comment by dsecik** [comment]
Dakujem za informacie, z nasej strany ide zatial len o testovanie Kram6 + fcrepo4. Vpripade Replikace Kramerius - Kramerius  nebolo cielom zreplikovat cely repozitar len otestovat tuto funkcionalitu. Predpolkadal som ze sa budu postupne replikovat jednotlive tituly s tym ze som planoval proces zastavit po zreplikovani par dokumentov, nevedel som ale ze pripravna faza bude trvat tak dlho.  Pockame teda na novu verziu.
