### ISSUE TITLE
Kramerius 6 - replikace (Kramerius -> Kramerius)

### ISSUE THREAD

**Issue by zafan** [ceskaexpedice/kramerius#602]
Dobrý den,

zjistil jsem, že nefunguje replikace Kramerius -> Kramerius, kdy se přes Krameria API ptá na Solr *:*,
kramerius poté vrátí HTML stránku "nenalezeno", replikační proces se snažní naparsovat získané XML, které je ve skutečnosti chybová HTML stránka -> exception.

## Shrnutí

* Při zahájení replikace se v pořádku dokončí nultá fáze
* První fáze se nedokončí: `org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 63; The system identifier must begin with either a single or double quote character.`

## Screenshoty debugu

**Debugovaný kód** *(i s obsahem proměnných v první fázi)*

![debug_code](https://user-images.githubusercontent.com/3747619/40613656-bb62e63e-627f-11e8-8042-50d342cf0a4c.png)

**Obsah proměnných** *(první fáze)*

![debug_variables](https://user-images.githubusercontent.com/3747619/40614086-802834a0-6281-11e8-810e-79fbb859303a.png)

**Exception**

![debug_exception](https://user-images.githubusercontent.com/3747619/40614100-89b05d4a-6281-11e8-8c3e-5119a19a5c1c.png)

**Comment by xermak00** [comment]
Ještě doplním, že, pokud spravně chapu, API se ptá na Solr s použitím strankování pomoci **start** a **rows**, což způsobí velký problem s rychlostí replikace při obrovském množství dat (které zrovna máme), a bylo by dobře kdyby se proces při strankování využival cursor je-li to možně.

**Comment by zafan** [comment]
## Shrnutí
Replikace je **nutné** zadávat ve tvaru **http(s)://<adresa>/search/** nikoliv *http(s)://<adresa>/search/handle/*

**Comment by zafan** [comment]
Replikace stále padá a tohle je bohužel to jediné, co jsem z toho schopný dostat.

```
ecting ALPHA, DIGIT, MINUS or DOT
org.kramerius.replications.PhaseException: cz.incad.kramerius.ProcessSubtreeException: cz.incad.kramerius.utils.pid.LexerException: expecting ALPHA, DIGIT, MINUS or DOT
	at org.kramerius.replications.ThirdPhase.start(ThirdPhase.java:92)
	at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:117)
	at org.kramerius.replications.FedoraDataMigrationProcess.replications(FedoraDataMigrationProcess.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:116)
Caused by: cz.incad.kramerius.ProcessSubtreeException: cz.incad.kramerius.utils.pid.LexerException: expecting ALPHA, DIGIT, MINUS or DOT
	at cz.incad.kramerius.fedora.AbstractFedoraAccess.processSubtree(AbstractFedoraAccess.java:176)
	at org.kramerius.consistency.Consistency.checkConsitency(Consistency.java:69)
	at org.kramerius.replications.ThirdPhase.start(ThirdPhase.java:70)
	... 7 more
Caused by: cz.incad.kramerius.utils.pid.LexerException: expecting ALPHA, DIGIT, MINUS or DOT
	at cz.incad.kramerius.utils.pid.PIDParser.objectId(PIDParser.java:195)
	at cz.incad.kramerius.utils.pid.PIDParser.namespaceId(PIDParser.java:168)
	at cz.incad.kramerius.utils.pid.PIDParser.objectPid(PIDParser.java:97)
	at cz.incad.kramerius.fedora.AbstractFedoraAccess.makeSureObjectPid(AbstractFedoraAccess.java:57)
	at cz.incad.kramerius.fedora.AbstractFedoraAccess.processSubtree(AbstractFedoraAccess.java:159)
	... 9 more

May 30, 2018 11:12:56 AM org.kramerius.replications.K4ReplicationProcess phaseFailed
INFO: PHASE &#039;org.kramerius.replications.ThirdPhase&#039; completed
May 30, 2018 11:12:56 AM cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:116)
Caused by: java.lang.RuntimeException: org.kramerius.replications.PhaseException: cz.incad.kramerius.ProcessSubtreeException: cz.incad.kramerius.utils.pid.LexerException: expecting ALPHA, DIGIT, MINUS or DOT
	at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:124)
	at org.kramerius.replications.FedoraDataMigrationProcess.replications(FedoraDataMigrationProcess.java:33)
	... 5 more
Caused by: org.kramerius.replications.PhaseException: cz.incad.kramerius.ProcessSubtreeException: cz.incad.kramerius.utils.pid.LexerException: expecting ALPHA, DIGIT, MINUS or DOT
	at org.kramerius.replications.ThirdPhase.start(ThirdPhase.java:92)
	at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:117)
	... 6 more
Caused by: cz.incad.kramerius.ProcessSubtreeException: cz.incad.kramerius.utils.pid.LexerException: expecting ALPHA, DIGIT, MINUS or DOT
	at cz.incad.kramerius.fedora.AbstractFedoraAccess.processSubtree(AbstractFedoraAccess.java:176)
	at org.kramerius.consistency.Consistency.checkConsitency(Consistency.java:69)
	at org.kramerius.replications.ThirdPhase.start(ThirdPhase.java:70)
	... 7 more
Caused by: cz.incad.kramerius.utils.pid.LexerException: expecting ALPHA, DIGIT, MINUS or DOT
	at cz.incad.kramerius.utils.pid.PIDParser.objectId(PIDParser.java:195)
	at cz.incad.kramerius.utils.pid.PIDParser.namespaceId(PIDParser.java:168)
	at cz.incad.kramerius.utils.pid.PIDParser.objectPid(PIDParser.java:97)
	at cz.incad.kramerius.fedora.AbstractFedoraAccess.makeSureObjectPid(AbstractFedoraAccess.java:57)
	at cz.incad.kramerius.fedora.AbstractFedoraAccess.processSubtree(AbstractFedoraAccess.java:159)
	... 9 more
```

**Comment by pavel-stastny** [comment]
Muzete nejak zasdilet titul na kterem to pada ?

**Comment by zafan** [comment]
Padá to jak na celém periodiku, tak na celé stránce.

**->** Titul resp. stránku odesílám emailem.

**Comment by pavel-stastny** [comment]
Tyka se Fedory 4 , uz neaktualni.  Zaviram
