### ISSUE TITLE
K6 - Padající indexace přes fedoru jako servlet container

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius#609]
Dobrý den,
zkoušíme jak nám funguje fedora 4 přes servlet místo té one-click standalone verze a narážíme na problém při indexaci.

Celý proces proběhne, soubory jsou vidět jak ve fedoře, tak v menu indexace dokumentů. Ale jakmile se spustí reindex tak proces spadne s následující chybou:

```
Jul 19, 2018 10:06:24 AM cz.incad.kramerius.indexer.FedoraOperations getFoxmlFromPid
SEVERE: Error getting object
java.io.IOException: pid &#039;uuid:a17105e1-f03c-453e-a0ef-502ac39b8387&#039; not found
	at cz.incad.kramerius.fedora.impl.Fedora4AccessImpl.getFoxml(Fedora4AccessImpl.java:360)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:85)
	at cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:253)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:171)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:126)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:121)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:112)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:85)
	at cz.incad.kramerius.indexer.Main.main(Main.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:120)

Jul 19, 2018 10:06:24 AM cz.incad.kramerius.indexer.SolrOperations reindexDoc
SEVERE: Error reindexing doc uuid:a17105e1-f03c-453e-a0ef-502ac39b8387 with: java.lang.Exception: Fedora Object uuid:a17105e1-f03c-453e-a0ef-502ac39b8387 not found. 
Jul 19, 2018 10:06:24 AM cz.incad.kramerius.indexer.SolrOperations updateIndex
SEVERE: Cant index. Action:reindexDoc Value: uuid:a17105e1-f03c-453e-a0ef-502ac39b8387
java.lang.Exception: java.lang.Exception: Fedora Object uuid:a17105e1-f03c-453e-a0ef-502ac39b8387 not found. 
	at cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:284)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:171)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:126)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:121)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:112)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:85)
	at cz.incad.kramerius.indexer.Main.main(Main.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.Exception: Fedora Object uuid:a17105e1-f03c-453e-a0ef-502ac39b8387 not found. 
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:88)
	at cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:253)
	... 11 more
Caused by: java.io.IOException: pid &#039;uuid:a17105e1-f03c-453e-a0ef-502ac39b8387&#039; not found
	at cz.incad.kramerius.fedora.impl.Fedora4AccessImpl.getFoxml(Fedora4AccessImpl.java:360)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:85)
	... 12 more

Jul 19, 2018 10:06:24 AM cz.incad.kramerius.indexer.Indexer update
SEVERE: Update failed
java.lang.Exception: java.lang.Exception: java.lang.Exception: Fedora Object uuid:a17105e1-f03c-453e-a0ef-502ac39b8387 not found. 
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:197)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:126)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:121)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:112)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:85)
	at cz.incad.kramerius.indexer.Main.main(Main.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramer
```

`configuration.properties` mám nastavené takto: 
```
## Use this if you want to use fedora 4 instance
fedora4Host=http://kramerius2.ntkcz.cz:8080/fedora

#Search core - point to SOLR
solrHost=http://kramerius2.ntkcz.cz:8983/solr/kramerius

#Processing core
processingSolrHost=http://kramerius2.ntkcz.cz:8983/solr/processing

_fedoraTomcatHost=http://kramerius2.ntkcz.cz:8080/
```

V případě že mám fedoru spuštěnou přes standalone s následující konfigurací tak problém není, je možné že tam dělá nepořádek ten context /fedora když se volá reindexace?
```
## Use this if you want to use fedora 4 instance
fedora4Host=http://kramerius2.ntkcz.cz:8081

#Search core - point to SOLR
solrHost=http://kramerius2.ntkcz.cz:8983/solr/kramerius

#Processing core
processingSolrHost=http://kramerius2.ntkcz.cz:8983/solr/processing

_fedoraTomcatHost=http://kramerius2.ntkcz.cz:8080/
```

**Comment by pavel-stastny** [comment]
Dobry den, 

kontext by nemel delat problem.  Muzete vyzkouset zapnout na tomcatu access log a podivat se jake dotazy prichazi pri indexaci ?

**Comment by jdobiasovsky** [comment]
```
10.0.1.43 - dobiasj [13/Aug/2018:12:51:18 +0200] "GET /search/lr?action=start&def=reindex&out=text&params=fromKrameriusModel,uuid:d0ceaa1a-9918-4df5-bc13-7acb7435268f,[Mechanika]:%20[Rukopisn%C3%BD%20soubor%20z%C4%8D%C3%A1sti%20kolorovan%C3%BDch%20list%C5%AF]&_=1534157478869 HTTP/1.1" 200 16 FA1D1C28BA0B83A43C3B05F0027640FF 35 ?action=start&def=reindex&out=text&params=fromKrameriusModel,uuid:d0ceaa1a-9918-4df5-bc13-7acb7435268f,[Mechanika]:%20[Rukopisn%C3%BD%20soubor%20z%C4%8D%C3%A1sti%20kolorovan%C3%BDch%20list%C5%AF]&_=1534157478869 -
10.0.8.54 - - [13/Aug/2018:12:51:21 +0200] "GET //search//lr?action=updatePID&uuid=823eaf35-edcd-4097-99a6-4eb1060a0476&pid=29962 HTTP/1.1" 200 - 8926602F4F314DAD6B756FE301F5675D 13 ?action=updatePID&uuid=823eaf35-edcd-4097-99a6-4eb1060a0476&pid=29962 -
10.0.8.54 - - [13/Aug/2018:12:51:21 +0200] "GET //search//lr?action=updateName&uuid=823eaf35-edcd-4097-99a6-4eb1060a0476&name=Indexace+dokumentu%3A+%5BMechanika%5D%3A+%5BRukopisn%C3%BD+soubor+z%C4%8D%C3%A1sti+kolorovan%C3%BDch+list%C5%AF%5D HTTP/1.1" 200 - 8F321345669EB6DAB426E888FD765209 3 ?action=updateName&uuid=823eaf35-edcd-4097-99a6-4eb1060a0476&name=Indexace+dokumentu%3A+%5BMechanika%5D%3A+%5BRukopisn%C3%BD+soubor+z%C4%8D%C3%A1sti+kolorovan%C3%BDch+list%C5%AF%5D -
10.0.8.54 - - [13/Aug/2018:12:51:23 +0200] "HEAD /fedora/rest/data/d0c/eaa/1a9/918/4df/5bc/137/acb/743/526/8f HTTP/1.1" 401 - - 1  -
10.0.8.54 - - [13/Aug/2018:12:51:23 +0200] "GET //search//lr?action=updateStatus&uuid=823eaf35-edcd-4097-99a6-4eb1060a0476&state=FAILED HTTP/1.1" 200 - 3A427E0A30EA29249F017D9D2DA2B71F 47 ?action=updateStatus&uuid=823eaf35-edcd-4097-99a6-4eb1060a0476&state=FAILED -
10.0.8.54 - - [13/Aug/2018:12:51:23 +0200] "GET //search//lr?action=closeToken&uuid=823eaf35-edcd-4097-99a6-4eb1060a0476 HTTP/1.1" 200 - F13D8E85E7673030D15ED0AA8FFFFDEE 7 ?action=closeToken&uuid=823eaf35-edcd-4097-99a6-4eb1060a0476 -

```

Už to tam vidím, skáče tam 401, ale na fedoře jsem zatím autorizaci nenastavoval. Nícméně koukám že když jsem přihlášený v krameriovi tak mě to na kramerius1.ntkcz.cz:8081/fedora ani nepustí, takže chyba bude u nás v konfiguraci. Děkuji
