### ISSUE TITLE
Nefunkční import z NDK METS formátu ve verzi 5.4.1 revize: 3389

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#616]
Dobrý den,

ve verzi 5.4.1 (revize 3389) mi nefunguje reindexace po importu dat ve formátu NDK METS.

Výpis z logu ve správě procesů:

Standardní výstup 
'/home/kramerius/.kramerius4/lp/862ccfbe-f6b7-4bd5-9c76-12c45c63a248/lrOut/stout.out'

```rOperations.postData(SolrOperations.java:701)
    at 
cz.incad.kramerius.indexer.SolrOperations.indexDoc(SolrOperations.java:541)
    at 
cz.incad.kramerius.indexer.SolrOperations.indexByPid(SolrOperations.java:470)
    ... 13 more

Jun 21, 2018 11:54:12 AM cz.incad.kramerius.indexer.Indexer update
SEVERE: Update failed
java.lang.Exception: java.lang.Exception: java.lang.Exception: 
java.lang.Exception: Solr has throw an error. Check tomcat log. 
java.io.IOException: Server returned HTTP response code: 400 for URL: 
http://localhost:8983/solr/kramerius/update
    at 
cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:187)
    at 
cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:51)
    at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:118)
    at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:112)
    at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:103)
    at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:76)
    at cz.incad.kramerius.indexer.Main.main(Main.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at 
cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)
Caused by: java.lang.Exception: java.lang.Exception: 
java.lang.Exception: Solr has throw an error. Check tomcat log. 
java.io.IOException: Server returned HTTP response code: 400 for URL: 
http://localhost:8983/solr/kramerius/update
    at 
cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:274)
    at 
cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:161)
    ... 11 more
Caused by: java.lang.Exception: java.lang.Exception: Solr has throw an 
error. Check tomcat log. java.io.IOException: Server returned HTTP 
response code: 400 for URL: http://localhost:8983/solr/kramerius/update
    at 
cz.incad.kramerius.indexer.SolrOperations.indexByPid(SolrOperations.java:500)
    at 
cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:271)
    ... 12 more
Caused by: java.lang.Exception: Solr has throw an error. Check tomcat 
log. java.io.IOException: Server returned HTTP response code: 400 for 
URL: http://localhost:8983/solr/kramerius/update
    at 
cz.incad.kramerius.indexer.SolrOperations.postData(SolrOperations.java:701)
    at 
cz.incad.kramerius.indexer.SolrOperations.indexDoc(SolrOperations.java:541)
    at 
cz.incad.kramerius.indexer.SolrOperations.indexByPid(SolrOperations.java:470)
    ... 13 more

Jun 21, 2018 11:54:12 AM cz.incad.kramerius.indexer.Indexer run
SEVERE: Run failed
java.lang.Exception: Index process failed
    at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:87)
    at cz.incad.kramerius.indexer.Main.main(Main.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at 
cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)

Jun 21, 2018 11:54:12 AM 
cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at 
cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)
Caused by: java.lang.Exception: java.lang.Exception: Index process 
failed
    at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:96)
    at cz.incad.kramerius.indexer.Main.main(Main.java:47)
    ... 5 more
Caused by: java.lang.Exception: Index process failed
    at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:87)
    ... 6 more
```

Chybový výstup 
'/home/kramerius/.kramerius4/lp/862ccfbe-f6b7-4bd5-9c76-12c45c63a248/lrErr/sterr.err'

```Jun 21, 2018 11:54:12 AM cz.incad.kramerius.indexer.SolrOperations 
indexByPid
SEVERE: Error indexing document 
uuid:f765b113-6a05-4653-8d01-a50f715ea407
java.lang.Exception: Solr has throw an error. Check tomcat log. 
java.io.IOException: Server returned HTTP response code: 400 for URL: 
http://localhost:8983/solr/kramerius/update
    at 
cz.incad.kramerius.indexer.SolrOperations.postData(SolrOperations.java:701)
    at 
cz.incad.kramerius.indexer.SolrOperations.indexDoc(SolrOperations.java:541)
    at 
cz.incad.kramerius.indexer.SolrOperations.indexByPid(SolrOperations.java:470)
    at 
cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:271)
    at 
cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:161)
    at 
cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:51)
    at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:118)
    at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:112)
    at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:103)
    at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:76)
    at cz.incad.kramerius.indexer.Main.main(Main.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at 
cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)

Jun 21, 2018 11:54:12 AM cz.incad.kramerius.indexer.SolrOperations 
reindexDoc
SEVERE: Error reindexing doc uuid:f765b113-6a05-4653-8d01-a50f715ea407 
with: java.lang.Exception: java.lang.Exception: Solr has throw an error. 
Check tomcat log. java.io.IOException: Server returned HTTP response 
code: 400 for URL: http://localhost:8983/solr/kramerius/update
Jun 21, 2018 11:54:12 AM cz.incad.kramerius.indexer.SolrOperations 
updateIndex
SEVERE: Cant index. Action:reindexDoc Value: 
uuid:ac863ca3-5f4f-47a3-8d03-fa567531f293;uuid:f765b113-6a05-4653-8d01-a50f715ea407;uuid:39592bfa-0949-434b-a59c-5aeeb62fc145;uuid:e5db62d5-7b36-4784-a9aa-0edc62a1dc22;uuid:a4aac57d-2992-40f3-8009-53edc24f89b5;uuid:c0bcc876-bf27-4eb0-ae91-91a8e3b17bd9;uuid:0fa655af-3f8a-452c-89b9-43afa4f4d92c;uuid:df21928e-56d8-409e-8a2d-d907f305c172;uuid:a1da0faa-6bdf-4859-b327-b0aebc97fdd4;uuid:45d2d881-f862-4112-8e47-e1f8ed57c1c2;uuid:f0765a68-245b-4cd5-b282-1dac6b7881c9;uuid:d805e714-50a2-413a-a425-adffe26d3455;uuid:00ebc3b1-8d1e-441d-8cfb-88e3a9e0dc17;uuid:cd097b2e-0963-48fd-9290-ec97bea32952
java.lang.Exception: java.lang.Exception: java.lang.Exception: Solr has 
throw an error. Check tomcat log. java.io.IOException: Server returned 
HTTP response code: 400 for URL: 
http://localhost:8983/solr/kramerius/update
    at 
cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:274)
    at 
cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:161)
    at 
cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:51)
    at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:118)
    at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:112)
    at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:103)
    at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:76)
    at cz.incad.kramerius.indexer.Main.main(Main.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at 
cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)
Caused by: java.lang.Exception: java.lang.Exception: Solr has throw an 
error. Check tomcat log. java.io.IOException: Server returned HTTP 
response code: 400 for URL: http://localhost:8983/solr/kramerius/update
    at 
cz.incad.kramerius.indexer.SolrOperations.indexByPid(SolrOperations.java:500)
    at cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations
```

Přikládám odkaz na PSP, které zkouším importovat a kompletní logy: 
https://drive.google.com/file/d/1SD0b-Sz_LCStdAqwIuBuRPiOdXq8qTvA/view?usp=sharing

Budu vděčný za pomoc s odhalením problému.

**Comment by pavel-stastny** [comment]
Dobry den, 

zkusim importovat. Nicemene ted od boku me napada, v novejsich verzich byly pridany do schematu pole pro indexovani geografickych nazvu a geosouradnic.    Nemuze to byt tim, ze neni updatovane schema v solru ?

**Comment by svetlym** [comment]
Na nastavení Solru jsem nic neměnil a ani jsem nikde nenarazil na informaci, že by bylo třeba něco takového dělat a jak se to dělá.

Můžete mě, prosím, nasměrovat na návod?

**Comment by pavel-stastny** [comment]
https://github.com/ceskaexpedice/kramerius/wiki/Instalace#obnoven%C3%AD-sch%C3%A9matu-v-solru

**Comment by svetlym** [comment]
Zdá se, že to pomohlo. Děkuju za pomoc.
