### ISSUE TITLE
Fedora-3.8.1 patch

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#651]
Zdravím,

čas od času, zcela náhodně se nám stává, že při ingestu objektů do Fedory, vypadne výjimka, příklad:
```Led 31, 2019 4:48:14 ODP. org.kramerius.Import visitAllDirsAndFiles
SEVERE: Error when ingesting PID: uuid:e0a92af5-c74e-41ba-86b0-1fa5f6345063, java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: Error creating replication job: The requested object uuid:e0a92af5-c74e-41ba-86b0-1fa5f6345063 doesn&#039;t exist in the registry.
Led 31, 2019 4:48:14 ODP. cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: Error creating replication job: The requested object uuid:e0a92af5-c74e-41ba-86b0-1fa5f6345063 doesn&#039;t exist in the registry.
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:310)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:240)
	at org.kramerius.Import.ingest(Import.java:128)
	at org.kramerius.Import.main(Import.java:95)
	at org.kramerius.imports.ParametrizedImport.process(ParametrizedImport.java:72)
	... 5 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: Error creating replication job: The requested object uuid:e0a92af5-c74e-41ba-86b0-1fa5f6345063 doesn&#039;t exist in the registry.
	at org.kramerius.Import.ingest(Import.java:423)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:305)
	... 9 more
Caused by: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: Error creating replication job: The requested object uuid:e0a92af5-c74e-41ba-86b0-1fa5f6345063 doesn&#039;t exist in the registry.
	at org.kramerius.Import.ingest(Import.java:397)
	at org.kramerius.Import.ingest(Import.java:420)
	... 10 more
Caused by: javax.xml.ws.soap.SOAPFaultException:  Caused by: Error creating replication job: The requested object uuid:e0a92af5-c74e-41ba-86b0-1fa5f6345063 doesn&#039;t exist in the registry.
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy49.ingest(Unknown Source)
	at org.kramerius.Import.ingest(Import.java:354)
	... 11 more
```

Výjimka je vyvolána/ošetřena zde:
https://github.com/fcrepo3/fcrepo/blob/master/fcrepo-server/src/main/java/org/fcrepo/server/storage/DefaultDOManager.java#L1412-L1420

Pokud se havarovaný importní proces spustí znovu (bez jakýchkoliv úprav/změn v digitálním objektu, na kterém to havarovalo), tak už většinou doběhne bez problému do konce.

Někdy (zcela náhodně) se ale stane, že zhavaruje opět "o kousek dál" na úplně jiném digitálním objektu. Opakované spuštění importního procesu buď opět proběhne dále bez problému, nebo to zase havaruje jinde atd.

Výše uvedené chování ukazuje na možný problém se synchronizací (souběhem?) procesů. Upravil jsem příslušnou třídu `DefaultDOManager` se snahou eliminovat uvedené problematické chování.

V příloze:
[fedora-3.8.1-patch.zip](https://github.com/ceskaexpedice/kramerius/files/2821497/fedora-3.8.1-patch.zip)
se nachází originální zdrojový kód třídy `DefaultDOManager`, upravený zdrojový kód a patch.

Dále jsou tam obsažené přeložené třídy, které lze použít bez nutnosti kompilace - je jen potřeba jimi nahradit originální třídy zabalené v knihovně `fcrepo-server-3.8.1.jar`, která se většinou (podle instalace) nachází v adresáři `$CATALINA_BASE/webapps/fedora/WEB-INF/lib`.

Vše samozřejmě provádět při zastavené aplikaci. Jeden z možných postupů např. zde:
https://stackoverflow.com/questions/1667153/updating-class-file-in-jar

Úprava je platná pouze pro Fedoru 3.8.1 na Jave 8!

Patch jsem zatím nasadil na testovací server, následně po nějakém čase ho zkusím nasadit na ostrou instanci. Pokud má někdo podobný problém, může také testovat - na vlastní nebezpečí samozřejmě :)

MD

**Comment by pavelkocourek** [comment]
@mduda100871 Je to Martine ještě relevantní?
