### ISSUE TITLE
Havarující ingest do Fedory a následující komplikace s nekonzistencí

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#664]
Zdravím,

narazili jsme na jeden celkem nepříjemný problém při ingestech objektů do Fedory, který způsobí nekonzistenci mezi obsahem repozitáře a indexy Fedory, potažmo i Solru.

Jak se to projevuje:

v KNAV importujeme do Krameria mimo "klasickou digitalizaci"  i články v PDF, kde součástí metadatového popisu u článků jsou často i tzv. abstrakty, což v našem případě bývají poměrně dlouhé texty/textové řetězce. Ty jsou dle NDK standardu mapovány do datastreamu DC do pole "dc:description".

Nyní se začaly objevovat při importu do Krameria následující výjimky - příklad:
```
SEVERE: Error when ingesting PID: uuid:63e6f59d-0749-4b41-5dc1-1c78cbe18da9, java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: Unable to add or modify object uuid:63e6f59d-0749-4b41-5dc1-1c78cbe18da9 (commit canceled)
Bře 27, 2019 8:37:47 ODP. cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: Unable to add or modify object uuid:63e6f59d-0749-4b41-5dc1-1c78cbe18da9 (commit canceled)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:310)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:240)
	at org.kramerius.Import.ingest(Import.java:128)
	at org.kramerius.Import.main(Import.java:95)
	at org.kramerius.imports.ParametrizedImport.process(ParametrizedImport.java:72)
	... 5 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: Unable to add or modify object uuid:63e6f59d-0749-4b41-5dc1-1c78cbe18da9 (commit canceled)
	at org.kramerius.Import.ingest(Import.java:423)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:305)
	... 9 more
Caused by: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: Unable to add or modify object uuid:63e6f59d-0749-4b41-5dc1-1c78cbe18da9 (commit canceled)
	at org.kramerius.Import.ingest(Import.java:397)
	at org.kramerius.Import.ingest(Import.java:420)
	... 10 more
Caused by: javax.xml.ws.soap.SOAPFaultException:  Caused by: Unable to add or modify object uuid:63e6f59d-0749-4b41-5dc1-1c78cbe18da9 (commit canceled)
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy49.ingest(Unknown Source)
	at org.kramerius.Import.ingest(Import.java:354)
	... 11 more
```
V logu databáze je u výše vyvolané výjimky následující chybový záznam:

![db-01](https://user-images.githubusercontent.com/8750622/55232402-bffff100-5225-11e9-9962-63bb5cc7f612.png)

Po přepnutí logování databáze do debugovacího režimu se ukázal celý problém - Fedora (modul trippi) ukládá do resource indexu obsah jednotlivých DC elementů (dc:title, dc:type, dc:description atd.), příklad:

![db-02](https://user-images.githubusercontent.com/8750622/55232821-ee320080-5226-11e9-8ebf-fdfda34d3a38.png)

`riTriples-3.8.1=# SELECT * FROM t22 LIMIT 10;`

![db-03](https://user-images.githubusercontent.com/8750622/55232891-1faacc00-5227-11e9-86fc-25b45ed2119b.png)

kde výše uvedený výpis příkazu SELECT ukazuje konkrétní uložení elementu `dc:description` v tabulce `t22`.

Problém tedy spočívá v tom, že element `dc:description` (namapovaný abstrakt) je přílš velký a tudíž přeteče pole `o`, v tomto konkrétním případě u tabulky `t22`.

Bohužel implementace trippi evidentně nijak neošetřuje toto přetečení (např automatickým "oříznutím" řetězce na rozumnou délku), což, a to je velmi nepříjmené, vede k celkem zásadní nekonzistenci v repozitáři, protože Fedora nepodporuje transakce. V druhém indexu Fedory, v tabulce `dofields` totiž zůstane záznam o objektu, že byl naingestován korektně.

Opakované spuštění importu pak na první pohled proběhne třeba už dobře (pokud nespadne na nějakém dalším objektu s příliš velkým `dc:description` - už se nám také stalo), nicméně na pozadí už zůstane nekonzistentní resource index a to má dále za následek to, že se i v Solr indexu nevygeneruje korektně obsah pole `pid_path`.

Výsledkem je úplně rozbitá logická struktura titulu - v našem případě zůstanou články jako samostatné entity bez vazeb na vyšší úrovně.

Pokud byly importovány data přímo ve formátu FOXML, tak náprava stavu/vyčištění repozitáře je sice pracné, ale lze to naskriptovat, protože jsou k dispozici identifikátory uuid. Pokud se to ale stane u balíčků NDK (probíhá přidělení uuid identifikátoru Krameriem při konverzi do FOXML), tak je mnohem obtížnější.

Závěr - je potřeba už ve výrobě (ProArc) ošetřit délku polí mapovaných do DC a případně je zkrátit na povolenou maximální délku 2712 znaků (viz log databáze), nebo spíše o něco méně.

MD

**Comment by zabak** [comment]
@mduda100871 je to ještě relevantní?

**Comment by pavel-stastny** [comment]
Uzavírám, v případě potřeby @mduda100871   je možno znovu otevřít.
