### ISSUE TITLE
Nevytvoření Virtualni sbírky 

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#694]
Dobrý den,
nedaří se nám vytvořit Virtualní sbírku ve verzi 5.3.6. Stejny problem jsme meli i v nižší verzi.
Kdyz vyplnime nazev sbirky a dame ji vytvorit, objevi se jen prazdne okno s textem cekejte prosim.
Je to problem verze Krameria nebo nas?
V kterem logu muzeme zjistit vice informaci?

Dekuji

**Comment by pavel-stastny** [comment]
Dobry den, zkuste se podivat do catalina.log

**Comment by matyasbajger** [comment]
Při otevření menu „Administrace virtuálních sbírek" v Krameriu se catalina logu vždy objeví:

WARNING: Could not get virtual collection for  vc:78f38907-c639-40e8-88ed-78cc6b1e2ccc: cz.incad.kramerius.virtualcollections.CollectionException: java.io.FileNotFoundException: http://localhost:9080/fedora/

Pokud se pokouším objekt vc prohlédnout skrze Web interface Fedory, tak mi hlásí: Could not retrieve object 'vc:78f38907-c639-40e8-88ed-78cc6b1e2ccc' from the repository. Either the object does not exist, or you do not have permission to view it.

Při založení nové virtuální sbírky (odeslání formuláře s jejími cze/eng názvy), kdy WUI skončí hláškou "Prosím, čekejte..." již catalina neloguje nic.

Vypadá to na nějakého ducha, jen částečně uložené info o objektu.

Díky za pomoc!

**Comment by pavel-stastny** [comment]
V logu krameria neni zadna hlaska ?

**Comment by matyasbajger** [comment]
Opakovane se zde opakuje:

Sep 25, 2019 1:28:25 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet AccessServlet threw exception
org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: vc:78f38907-c639-40e8-88ed-78cc6b1e2ccc
        at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorage.retrieve(AkubraLowlevelStorage.java:393)
        at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorage.retrieveObject(AkubraLowlevelStorage.java:161)
        at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorageModule.retrieveObject(AkubraLowlevelStorageModule.java:80)
        at org.fcrepo.server.storage.DefaultDOManager.getReader(DefaultDOManager.java:648)
        at org.fcrepo.server.access.DefaultAccess.getDatastreamDissemination(DefaultAccess.java:1111)
        at org.fcrepo.server.access.FedoraAccessServlet.getDatastreamDissemination(FedoraAccessServlet.java:609)
        at org.fcrepo.server.access.FedoraAccessServlet.doGet(FedoraAccessServlet.java:459)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:368)
        at org.fcrepo.server.security.jaas.AuthFilterJAAS.doFilter(AuthFilterJAAS.java:330)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:109)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:169)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:394)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:299)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:745)

**Comment by pavel-stastny** [comment]
Myslim, ze tohle to je az dusledek. Slo by vycistit log, zkusit zalozit sbirku a pak poslat obsah logu ? 

Diky

**Comment by matyasbajger** [comment]
Logy jsem smazal, restartnul cely stroj a tataz chyba je v localhost logu stale dookola. Dnes v 0-7 hodin celkem 500x. Podle localhost_access_logu se neco pokousi onu podivnou virt. sbirku dookola volat (v prumeru kazdou minutu):
127.0.0.1 - - [02/Oct/2019:06:43:24 +0200] "GET /fedora/get/vc:78f38907-c639-40e8-88ed-78cc6b1e2ccc/DC HTTP/1.1" 404 665

fedora.log k tomu:
INFO 2019-10-02 06:58:23.247 [http-9080-31] (FedoraAccessServlet) Got request: http://localhost:9080/fedora/get/vc:78f38907-c639-40e8-88ed-78cc6b1e2ccc/DC
ERROR 2019-10-02 06:58:23.249 [http-9080-31] (FedoraAccessServlet) Object or datastream not found for request: http://localhost:9080/fedora/get/vc:78f38907-c639-40e8-88ed-78cc6b1e2ccc/DC (actionLabel=Access)
org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: vc:78f38907-c639-40e8-88ed-78cc6b1e2ccc
[root@camea2 logs]# less fedora.log
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:394) [catalina-6.0.24.jar:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [catalina-6.0.24.jar:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:299) [catalina-6.0.24.jar:na]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857) [tomcat-coyote-6.0.24.jar:na]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588) [tomcat-coyote-6.0.24.jar:na]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489) [tomcat-coyote-6.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

**Comment by pavel-stastny** [comment]
Ten odkaz na sbirku se bohuzem musi odebrat z indexu a z foxml.   Je nekde ten kramerius z venku viditelny ?

**Comment by matyasbajger** [comment]
http://kramerius.svkos.cz

V datastore fedory /home/kramerius/fedora/data/objectStore/ je podle filesystemu/grep skutecne asi 7700x objekt obsahujici vazbu na tuto problemovou sbirku:
<rdf:isMemberOfCollection rdf:resource="info:fedora/vc:78f38907-c639-40e8-88ed-78cc6b1e2ccc"/>

Napr. objekty
uuid:a3bab510-e361-11e0-b123-0013d398622b
uuid:02698dc0-f965-11e0-81cf-0013d398622b
uuid:956081c0-af2a-11dd-abdf-0013d398622b

Jak to nejlepe hromadne ze vsech 7 tisic odstranit? Diky!!

**Comment by zabak** [comment]
@matyasbajger je to ještě relevantní otázka? Pro nové sbírky není relevantní, navrhuji zavřít.
