### ISSUE TITLE
DNNT: Opakujuci sa problem FLAGS ARE NOT SET

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#699]
Opakovane sa vyskytuje tato systemova chyba. Osobne si myslim, ze proste je to kvoli exception u diel bez flagu DNNT.

```
SEVERE: These flags are not set : [cz.incad.kramerius.security.impl.criteria.PDFDNNTFlag]
cz.incad.kramerius.security.impl.criteria.CriteriaPrecoditionException: These flags are not set : [cz.incad.kramerius.security.impl.criteria.PDFDNNTFlag]
at cz.incad.kramerius.security.impl.criteria.utils.CriteriaDNNTUtils.checkContainsCriterium(CriteriaDNNTUtils.java:163)
at cz.incad.kramerius.security.impl.criteria.utils.CriteriaDNNTUtils.checkContainsCriteriumPDFDNNT(CriteriaDNNTUtils.java:145)
at cz.incad.kramerius.security.impl.criteria.ReadDNNTFlagIPFiltered.checkPrecodition(ReadDNNTFlagIPFiltered.java:48)
at cz.incad.kramerius.security.impl.RightImpl.evaluate(RightImpl.java:118)
at cz.incad.kramerius.security.impl.DatabaseRightsManager.resolve(DatabaseRightsManager.java:250)
```

**Comment by pavel-stastny** [comment]
Ne, to je pravama... musi se nastavit i pro generovani PDF a tisk.  Viz:  https://github.com/ceskaexpedice/kramerius/wiki/DNNT#pr%C3%A1va
