### ISSUE TITLE
Cannot load relations: null

### ISSUE THREAD

**Issue by ser789654** [ceskaexpedice/kramerius#701]
Fedora 3.8.1
Solr 6.3.0 samostatne
Tomcat 7
postgre 12
------------------------
Zdravim,

snazim se lokalne rozjet kramerius-5.4.2.(windows10). Spusteni tomcatu bez chyby, jakmile se zaloguju tak mi to zobrazi jenom header a jinak prazdnou stranku, chyba v tomcat konzoli:

SEVERE: null
java.io.IOException: Cannot load relations: null
        at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:64)
        at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.fetchRelations(GetKrameriusObjectQueryHandler.java:161)
        at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.execute(GetKrameriusObjectQueryHandler.java:95)
        at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.execute(GetKrameriusObjectQueryHandler.java:64)
        at net.customware.gwt.dispatch.server.AbstractDispatch.doExecute(AbstractDispatch.java:67)
        at net.customware.gwt.dispatch.server.AbstractDispatch.execute(AbstractDispatch.java:57)
        at net.customware.gwt.dispatch.server.standard.AbstractStandardDispatchServlet.execute(AbstractStandardDispatchServlet.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:548)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
        at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:321)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:319)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: cz.incad.kramerius.utils.pid.LexerException: Expecting '%3A' or ':' but got eoi
        at cz.incad.kramerius.impl.FedoraAccessImpl.getDataStream(FedoraAccessImpl.java:948)
        at cz.incad.kramerius.relation.RelationUtils.getDataStream(RelationUtils.java:59)
        at cz.incad.kramerius.relation.RelationUtils.getRelsExt(RelationUtils.java:51)
        at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:61)
        ... 42 more
Caused by: cz.incad.kramerius.utils.pid.LexerException: Expecting '%3A' or ':' but got eoi
        at cz.incad.kramerius.utils.pid.PIDParser.matchDoubleDot(PIDParser.java:148)
        at cz.incad.kramerius.utils.pid.PIDParser.objectPid(PIDParser.java:100)
        at cz.incad.kramerius.impl.FedoraAccessImpl.makeSureObjectPid(FedoraAccessImpl.java:136)
        at cz.incad.kramerius.impl.FedoraAccessImpl.getDataStream(FedoraAccessImpl.java:921)
        ... 45 more

**Comment by pavel-stastny** [comment]
Zdravim, podle stacktrace to spis vypada jako chyba z editoru stranek.  Aby k tomu slo rict vic, je treba vedet pri jake udalosti chyba nastava.

**Comment by daniel-adamek** [comment]
Dojde k tomu hned po zalogovani, kdy me to ma presmerovat na domovskou stranku

**Comment by zabak** [comment]
@daniel-adamek povedlo se to na těch windowsech rozjet? Normální je provozovat Kramerius na linuxu, takže s tím asi nikdo neporadí...

**Comment by filak** [comment]
To je stará vesta, vyvolává to nevalidní řetězec PID (UUID), což může mít několik příčin
- viz např. https://github.com/ceskaexpedice/kramerius/issues/129

Zřejmě jste něco přehlédnul při instalaci/konfiguraci...

Jinak níže uvedená kombinace komponent funguje na Windows normálně:

SOLR 7.7.2
PostreSQL 12
Java AdoptOpenJDK 1.8
Tomcat 8.5 
Fedora Commons 3.8
Kramerius 5.5

Je třeba ale ošetřit v Tomcat server.xml - URIEncoding a relaxedQueryChars

             <Connector ... URIEncoding="UTF-8" relaxedQueryChars="{}\"/>

**Comment by pavel-stastny** [comment]
@ser789654   Tato chyba již asi nepůjde reprodukovat. Issue uzavřu ale v případě stejné chyby na K7 je možno znovu otevřít.
