### ISSUE TITLE
Replikace K6 repo -> repo

### ISSUE THREAD

**Issue by fstepanovsky** [ceskaexpedice/kramerius#710]
Dobrý den,
při testování jsme narazili na to, že migrace padá na nedostatku paměti (s kurzorem).

Log: 
```
Nov 15, 2019 11:56:55 AM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;static-export-6.1.0-alpha&#039; to &#039;static_export.properties&#039;
Nov 15, 2019 11:56:55 AM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;indexer-6.1.0-alpha&#039; to &#039;indexer.properties&#039;
Nov 15, 2019 11:56:55 AM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-mets-6.1.0-alpha&#039; to &#039;migration.properties&#039;
Nov 15, 2019 11:56:55 AM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-cmdtool-6.1.0-alpha&#039; to &#039;migration.properties&#039;
Nov 15, 2019 11:56:55 AM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;common-6.1.0-alpha&#039; to &#039;configuration.properties&#039;
Nov 15, 2019 11:56:55 AM cz.incad.kramerius.processes.starter.ProcessUpdatingChannel$StandardProcessUpdatingChannel updateName
INFO: requesting url :http://kramerius6:8080/search//lr?action=updateName&amp;uuid=4b9fb348-23b5-416e-a2bf-16043cc1cdbb&amp;name=Replikace+%27http%3A%2F%2Fkramerius.infra.mzk.cz%2Fsearch%2F%27
Nov 15, 2019 11:56:55 AM org.kramerius.replications.K4ReplicationProcess start
INFO: STARTING PHASE &#039;org.kramerius.replications.ZeroPhase&#039;
Nov 15, 2019 11:56:55 AM org.kramerius.replications.K4ReplicationProcess phaseCompleted
INFO: PHASE &#039;org.kramerius.replications.ZeroPhase&#039; completed
Nov 15, 2019 11:56:55 AM org.kramerius.replications.K4ReplicationProcess start
INFO: STARTING PHASE &#039;org.kramerius.replications.IterateThroughIndexPhase&#039;
Nov 15, 2019 11:56:55 AM org.kramerius.replications.IterateThroughIndexPhase start
INFO: Using cursor
Nov 16, 2019 12:04:38 AM cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:116)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.apache.xerces.dom.DeferredDocumentImpl.getNodeObject(Unknown Source)
	at org.apache.xerces.dom.DeferredDocumentImpl.synchronizeChildren(Unknown Source)
	at org.apache.xerces.dom.DeferredElementImpl.synchronizeChildren(Unknown Source)
	at org.apache.xerces.dom.ParentNode.getChildNodes(Unknown Source)
	at cz.incad.kramerius.utils.XMLUtils.findElement(XMLUtils.java:305)
	at org.kramerius.replications.IterateThroughIndexPhase.nextCursor(IterateThroughIndexPhase.java:124)
	at org.kramerius.replications.IterateThroughIndexPhase.cursorPids(IterateThroughIndexPhase.java:77)
	at org.kramerius.replications.IterateThroughIndexPhase.start(IterateThroughIndexPhase.java:46)
	at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:117)
	at org.kramerius.replications.FedoraDataMigrationProcess.replications(FedoraDataMigrationProcess.java:44)
	... 5 more
```

**Comment by pavel-stastny** [comment]
Dobry den, 

zkuste nastavit vice pameti procesu migrace (data_migration)

**Comment by JanMeritus** [comment]
Dobry den,

@pavel-stastny je pre tento proces nastavena nejaka optimalizace heapu a uziti pameti?

**Comment by pavel-stastny** [comment]
@JanMeritus  Nerozumim...   Ale obecne.  Spoustene procesy jsou samostatne procesy, ktere maji samostatne nastaveni heapu, promennych atd...  Kazdy proces je mozne v tomto smyslu predefinovat v souboru `~/lp.xml`

**Comment by JanMeritus** [comment]
@pavel-stastny jestli sa da optimalizovat/nastavit tak, aby vice pameti nepotreboval

**Comment by pavel-stastny** [comment]
@JanMeritus Nemyslim, ze by ta vyjimka byla zpusobena nejakym memory leakem.  Spis to na me pusobi, ze to defaultni nastaveni procesu je nedostatecne.  

@fstepanovsky  Muzete zkusit zvetsit pamet a pustit proces znovu. Pokud to pobezi bez problemu, dame to do defaultnich nastaveni.

**Comment by pavel-stastny** [comment]
@fstepanovsky  Jak jsme se bavili po telefonu, bylo by v `lp.xml` mozno nadefinovat neco podobneho? 


```
<process>
        <id>data_migration</id>
        <description>Repository to repository migration </description>
        <mainClass>org.kramerius.replications.FedoraDataMigrationProcess</mainClass>
        <standardOs>lrOut</standardOs>
        <errOs>lrErr</errOs>
        <securedaction>import</securedaction>
        <javaProcessParameters>-Xmx3072‬m -Xms1024m</javaProcessParameters>
        <templates>
            <input class="org.kramerius.replications.input.DataMigrationInputTemplate"></input>
			<output class="org.kramerius.replications.output.DataMigrationOutputTemplate"></output>
        </templates>
    </process>

```

Pričemž řádek `javaProcessParameters`  je důležitý.  

Díky a s pozdravem 

Pavel Šťastný

**Comment by pavel-stastny** [comment]
@fstepanovsky  Jinak default nastavení pro proces migrace je vidět zde: 
https://github.com/ceskaexpedice/kramerius/blob/akubra/shared/common/src/main/java/cz/incad/kramerius/processes/res/lp.st#L535-L548

**Comment by fstepanovsky** [comment]
Dobrý den,

@pavel-stastny trochu se to protáhlo, běželo to déle, než jsem myslel, paměť jsem navíšil pomocí `-Xmx` na 5072.
Připsali jsme si logování do toho procesu a nesporně za to může to, že se všechna uuid postupně (po 1000) načítají do paměti a aprox. 60 000 000 uuid už je v RAMce znát, podle mých výpočtů, co jsem počítal, tak na samotná uuid je třeba více než 8 GB paměti, což vlastně viz log, kde 5 GB nestačilo na 21 095 000.

přidávám zase kousek logu pro ilustraci, než to padlo na paměti:
```
Nov 30, 2019 3:48:30 AM org.kramerius.replications.IterateThroughIndexPhase cursorPids
INFO: Fetched pid count (retvals): 21095000
Nov 30, 2019 3:48:30 AM org.kramerius.replications.IterateThroughIndexPhase cursorPids
INFO: Free memory (bytes): 13206368
Nov 30, 2019 3:55:50 AM cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:116)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.apache.xerces.dom.DeferredDocumentImpl.getNodeObject(Unknown Source)
	at org.apache.xerces.dom.DeferredDocumentImpl.synchronizeChildren(Unknown Source)
	at org.apache.xerces.dom.DeferredElementImpl.synchronizeChildren(Unknown Source)
	at org.apache.xerces.dom.ParentNode.getChildNodes(Unknown Source)
	at cz.incad.kramerius.utils.XMLUtils.findElement(XMLUtils.java:305)
	at org.kramerius.replications.IterateThroughIndexPhase.nextCursor(IterateThroughIndexPhase.java:133)
	at org.kramerius.replications.IterateThroughIndexPhase.cursorPids(IterateThroughIndexPhase.java:79)
	at org.kramerius.replications.IterateThroughIndexPhase.start(IterateThroughIndexPhase.java:48)
	at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:117)
	at org.kramerius.replications.FedoraDataMigrationProcess.replications(FedoraDataMigrationProcess.java:44)
```

**Comment by pavel-stastny** [comment]
Díky za info.  Podívám se na to a dám vědět.

**Comment by vlahoda** [comment]
@fstepanovsky Vami zminovany proces je urcen k replikaci jednotlivych titulu mezi vzdalenymi ulozisti, nikoli k migraci celeho uloziste. Pro migraci celeho uloziste je urcen novy nastroj migration, ktery je soucasti distribuce Krameria 7.

**Comment by fstepanovsky** [comment]
@vlahoda toho jsem si vědom, jen jsem se špatně vyjádřil, onou migrací myslím Replikaci celého repozitáře, která je neřízená a replikuje se celý repozitář (Kramerius) do Krameria, z kterého byla replikace zadána.
Tato replikace byla součástí K6 alpha, proto jsme ji také testovali. 🙃

Pokud bude metoda [cursorPids](https://github.com/ceskaexpedice/kramerius/blob/master/processes/data-migration/src/main/java/org/kramerius/replications/IterateThroughIndexPhase.java#L66) a [pagingPids](https://github.com/ceskaexpedice/kramerius/blob/master/processes/data-migration/src/main/java/org/kramerius/replications/IterateThroughIndexPhase.java#L93) někdy na něco obdobně velkého používána, doporučuji jí ošetřit proti velkému množství dat - předpokládám, že dat bude už jen přibývat.

Součástí K7 už tato funkce není, proto je další řešení issue bezpředmětné.
