### ISSUE TITLE
Testování K7 - synchronizační chyba během replikace/importu

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#719]
Při importu nebo replikaci do K7 více dokumentů současně v procesech občas vzníká synchronizační (předpokládám) chyba typu

```
Jan 23, 2020 1:42:27 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: akubrasync [dev] [3.11.2] Authenticated with server [192.168.208.4]:5701, server version:3.11.2 Local address: /127.0.0.1:42284
Jan 23, 2020 1:42:27 PM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: akubrasync [dev] [3.11.2] 

Members [1] {
	Member [192.168.208.4]:5701 - f19ddfc4-5bf3-4dfb-a35c-4d15b8d871d6
}

Jan 23, 2020 1:42:27 PM com.hazelcast.core.LifecycleService
INFO: akubrasync [dev] [3.11.2] HazelcastClient 3.11.2 (20190216 - e302506) is CLIENT_CONNECTED
Jan 23, 2020 1:42:27 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: akubrasync [dev] [3.11.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jan 23, 2020 1:42:27 PM com.hazelcast.client.spi.ClientListenerService
SEVERE: akubrasync [dev] [3.11.2] akubrasync.event-5 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor@6b9ad8dd
java.lang.NullPointerException
	at cz.incad.kramerius.fedora.om.impl.AkubraDOManager$1.onMessage(AkubraDOManager.java:84)
	at com.hazelcast.client.proxy.ClientTopicProxy$TopicItemHandler.handleTopicEventV10(ClientTopicProxy.java:89)
	at com.hazelcast.client.impl.protocol.codec.TopicAddMessageListenerCodec$AbstractEventHandler.handle(TopicAddMessageListenerCodec.java:147)
	at com.hazelcast.client.proxy.ClientTopicProxy$TopicItemHandler.handle(ClientTopicProxy.java:77)
	at com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor.run(AbstractClientListenerService.java:368)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)

Jan 23, 2020 1:42:27 PM com.hazelcast.client.spi.ClientListenerService
SEVERE: akubrasync [dev] [3.11.2] akubrasync.event-5 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor@6ad3f85d
java.lang.NullPointerException
	at cz.incad.kramerius.fedora.om.impl.AkubraDOManager$1.onMessage(AkubraDOManager.java:84)
	at com.hazelcast.client.proxy.ClientTopicProxy$TopicItemHandler.handleTopicEventV10(ClientTopicProxy.java:89)
	at com.hazelcast.client.impl.protocol.codec.TopicAddMessageListenerCodec$AbstractEventHandler.handle(TopicAddMessageListenerCodec.java:147)
	at com.hazelcast.client.proxy.ClientTopicProxy$TopicItemHandler.handle(ClientTopicProxy.java:77)
	at com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor.run(AbstractClientListenerService.java:368)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)

Jan 23, 2020 1:42:27 PM org.ehcache.core.EhcacheManager createCache
INFO: Cache &#039;DigitalObjectCache&#039; created in EhcacheManager.
Jan 23, 2020 1:42:28 PM cz.incad.kramerius.indexer.FedoraOperations getFoxmlFromPid
INFO: getFoxmlFromPid pid=uuid:00039a15-bbdf-4d0e-b4f8-ef2951ff738a
```

Chyba vzníká v [AkubraDOManager.java](https://github.com/ceskaexpedice/kramerius/blob/master/shared/common/src/main/java/cz/incad/kramerius/fedora/om/impl/AkubraDOManager.java#L84) při pokusu vymazat něco z cache,

```java
cacheInvalidator.addMessageListener(new MessageListener<String>() {
            @Override
            public void onMessage(Message<String> message) {
                objectCache.remove(message.getMessageObject());
            }
 });
```
přičemž vypadá že import/replikace doběhne bez problemů, ale v logach je pak červeno.

**Comment by vlahoda** [comment]
Pridal jsem na to misto hlidani null objektu. Neni mi ale vubec jasne proc by ty objekty mohly byt null. Hazelcast by nemel odesilat prazdne zpravy a objectCache muze byt null jedine, kdyby se nepodarilo spravne inicializovat datove uloziste - v tom pripade by ale nemel import vubec fungovat. @xermak00 - neni v logu Krameria nebo nektereho z tech importnich procesu na zacatku zaznamenana nejaka IOException tykajici se inicializace datastore?

**Comment by xermak00** [comment]
Děkuju, otestuju to. V logach níc jiného není, u těch procesů, kde vyskočí exception to vypadá takhle https://gist.github.com/xermak00/6651c1155f32f64a436a3765038c8c91 , ostatní (z těch paralelně běžicích) níc nemájí.

**Comment by vlahoda** [comment]
Diky, uz je mi to jasne - chyba vznikala kvuli nekorektnimu poradi inicializace cache (injectovana jako singleton pres Guice) a hazelcast listeneru(staticky inicializovany), projevovalo se to opravdu jen pri inicializaci uloziste a byl to tedy vlastne "plany poplach". Ten fix 0849e39 to resi, logy uz nebudou zbytecne cervene, necham si to tu ale otevrene a to poradi inicializace prilezitostne vylepsim.
