### ISSUE TITLE
K5.4.2 - generování PDF neproběhne

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#739]
V logu pak je:
SEVERE [http-nio-55300-exec-147] cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter Can't find resource for bundle java.util.PropertyResourceBundle, key pdf.fp.publisherDates
	java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key pdf.fp.publisherDates
		at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
		at java.util.ResourceBundle.getObject(ResourceBundle.java:444)
		at java.util.ResourceBundle.getString(ResourceBundle.java:407)
		at cz.incad.kramerius.pdf.impl.FirstPagePDFServiceImpl.templateSelection(FirstPagePDFServiceImpl.java:225)
		at cz.incad.kramerius.pdf.impl.FirstPagePDFServiceImpl.selection(FirstPagePDFServiceImpl.java:138)
		at cz.incad.kramerius.rest.api.k5.client.pdf.AbstractPDFResource.selection(AbstractPDFResource.java:175)
		at cz.incad.kramerius.rest.api.k5.client.pdf.PDFResource.selection(PDFResource.java:274)
...

Do labels... props jsem ten klíč doplnil, ale chyba se objevuje pořád...

**Comment by vlahoda** [comment]
Problem nedokazu reprodukovat. Ten klic v defaultnim bundle base.properties je, generovani PDF funguje, prosel jsem i nekolik instalaci s verzi 5.4.2 uvedenych na https://registr.digitalniknihovna.cz,  vsude OK.

**Comment by filak** [comment]
No právě, v 5.3.4 nám to funguje taky. Ta hláška je asi jen kouřová clona... Budu to dál zkoumat.

**Comment by filak** [comment]
Nebude tou šablonou template_static_export.0.1.xslt ? Nebo případně nějakým podobným ?

Ono totiž asi nechybí ten klíč v bundle, ale v tom templatu...

Monografie normálně do pdf exportovat jdou, ale periodika nejdou. Zajímavé taky je, že když k uuid co nejde exportovat přidám uuid stránky, co jde exportovat, tak se vyexportují obě:

http://.../search/api/v5.0/pdf/selection?pids=uuid:f526cb99-e82e-11e8-b547-d485646517a0,uuid:c1ef2790-d3cb-11dc-a222-000d606f5dc6&pageType=TEXT&format=A4

Stránky pouze z periodika však havarují...

**Comment by pavel-stastny** [comment]
Ahoj, nejlepší bude, když pošleš konkrétní titul na kterém to havaruje.  (Třeba mailem)

**Comment by filak** [comment]
Dělá to u všech periodik, co jsem zkoušel...

01-Mar-2020 13:30:01.723 SEVERE [ajp-nio-55310-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [/search] threw exception [java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key pdf.fp.publisherDates] with root cause
	java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key pdf.fp.publisherDates
		at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
		at java.util.ResourceBundle.getObject(ResourceBundle.java:444)
		at java.util.ResourceBundle.getString(ResourceBundle.java:407)
		at cz.incad.kramerius.pdf.impl.FirstPagePDFServiceImpl.templateSelection(FirstPagePDFServiceImpl.java:225)
		at cz.incad.kramerius.pdf.impl.FirstPagePDFServiceImpl.selection(FirstPagePDFServiceImpl.java:138)
		at cz.incad.kramerius.rest.api.k5.client.pdf.AbstractPDFResource.selection(AbstractPDFResource.java:175)
		at cz.incad.kramerius.rest.api.k5.client.pdf.PDFResource.selection(PDFResource.java:274)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
		at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
		at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
		at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
		at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
		at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
		at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
		at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
		at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
		at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
		at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
		at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
		at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
		at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
		at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
		at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
		at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
		at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
		at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
		at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
		at cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:482)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)

**Comment by filak** [comment]
Jak už jsem psal, v K5.3.4 to projde, v K5.4.2 projdou jen monografie nebo monografie+periodikum, srovnej:

Stránka periodika - **v 5.4.2 neprojde**:
https://kramerius.medvik.cz/search/api/v5.0/pdf/selection?pids=uuid:5297927d-9d8e-11e5-b034-d485646517a0

Stránka periodika+monografie - v 5.4.2 projde:
https://kramerius.medvik.cz/search/api/v5.0/pdf/selection?pids=uuid:5297927d-9d8e-11e5-b034-d485646517a0,uuid:c1ef2790-d3cb-11dc-a222-000d606f5dc6

Stránka monografie - v 5.4.2 projde:
https://kramerius.medvik.cz/search/api/v5.0/pdf/selection?pids=uuid:c1ef2790-d3cb-11dc-a222-000d606f5dc6

**Comment by filak** [comment]
Například z ČDK pro stejnou stránku:
https://cdk.lib.cas.cz/search/api/v5.0/pdf/selection?pids=uuid:5297927d-9d8e-11e5-b034-d485646517a0&language=cs
- vyleze:
Hlavní název: Věstník českých lékařů
Vydavatel: Ústřední jednota československých lékařů
**Vydáváno v letech:** 1921-1933, 1921, 1.1.1921        _[= pdf.fp.publisherDates]_
Čísla ročníků: 33, 1
Čísla výtisků: 33, 1
Datum vydání čísla: 1.1.1921
Identifikátor ISSN: 0231-5009
Stránka: [1]

**Comment by filak** [comment]
Se mi zdá, že by problém mohl být někde tady: 
https://github.com/ceskaexpedice/kramerius/blob/48a4003e0bc87e04be4faa11573594efd12a7264/shared/common/src/main/java/cz/incad/kramerius/pdf/impl/FirstPagePDFServiceImpl.java#L223

Vidím tam dotaz na SOLR:
https://github.com/ceskaexpedice/kramerius/blob/48a4003e0bc87e04be4faa11573594efd12a7264/shared/common/src/main/java/cz/incad/kramerius/pdf/impl/FirstPagePDFServiceImpl.java#L125

Tak nevím, jestli tu není třeba souvislost s tím, že jsem to zaindexoval (SOLR v7.7.2) podle schématu z https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0.0-beta1

**Comment by pavel-stastny** [comment]
Posli mi ten balik FOXML, ja to u sebe vyzkousim.

**Comment by vlahoda** [comment]
@filak 

> Se mi zdá, že by problém mohl být někde tady:

Asi jsi to odhalil dobre a Pavel si vsimnul, ze ten chybejici klic byl doplneny v tomto commitu:
https://github.com/ceskaexpedice/kramerius/pull/646/commits/26210099e4809186a8ce338467f7ee6139b79a16

Takze v aktualni verzi uz je to vyresene.

**Comment by filak** [comment]
No ale i když jsem ten klíč do labels....props doplnil, tak to stejně pořád dává stejnou chybu...

A kdy tedy bude nějaká 5.4.3 verze, která vyřeší toto https://github.com/ceskaexpedice/kramerius/issues/739 a https://github.com/ceskaexpedice/kramerius/issues/738 ?

**Comment by filak** [comment]
@pavel-stastny FOXML jsem ti poslal mailem.

**Comment by vlahoda** [comment]
> No ale i když jsem ten klíč do labels....props doplnil, tak to stejně pořád dává stejnou chybu...
> 
> A kdy tedy bude nějaká 5.4.3 verze, která vyřeší toto #739 a #738 ?

PDF generator pouziva lokalizacni soubor base.properties, bylo by potreba pridat ten klic tam.
Novou verzi pripravime snad tento tyden, chceme najednou vydat posledni K5 i prvni K7.
Kdyby to spechalo vic, staci pouzit prikaz `gradle :search:clean :search:build`.
