### ISSUE TITLE
Problém s replikací

### ISSUE THREAD

**Issue by kvetjo** [ceskaexpedice/kramerius#775]
Zdravím všechny, 

obracím se na vás s problém, který se týká replikace monografií. Získali jsme balíky k replikaci, nicméně Kramerius je nedokázal naimportovat. Proto jsme následně zkusili replikaci se vzorovým SIP balíčkem dostupným na stránkách NDK (https://old.ndk.cz/standardy-digitalizace/metadata) u kterého bych předpokládal zdárný import, bohužel výsledek byl stejný. Pokaždé v logu hlásí tuto chybovou hlášku:

`Oct 30, 2020 3:15:04 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.RuntimeException: org.kramerius.importmets.valueobj.ServiceException: org.kramerius.importmets.valueobj.ServiceException: Unsupported div type in logical structure: PAGE
	at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:75)
	... 5 more
Caused by: org.kramerius.importmets.valueobj.ServiceException: org.kramerius.importmets.valueobj.ServiceException: Unsupported div type in logical structure: PAGE
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.convert(MetsPeriodicalConvertor.java:65)
	at org.kramerius.importmets.MetsConvertor.convertOneDirectory(MetsConvertor.java:325)
	at org.kramerius.importmets.MetsConvertor.convert(MetsConvertor.java:191)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:115)
	at org.kramerius.importmets.MetsConvertor.main(MetsConvertor.java:62)
	at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:73)
	... 5 more
Caused by: org.kramerius.importmets.valueobj.ServiceException: Unsupported div type in logical structure: PAGE
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.mapModel(MetsPeriodicalConvertor.java:371)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.processDiv(MetsPeriodicalConvertor.java:297)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.processDiv(MetsPeriodicalConvertor.java:340)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.processDiv(MetsPeriodicalConvertor.java:280)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.processStructMap(MetsPeriodicalConvertor.java:169)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.convert(MetsPeriodicalConvertor.java:60)
	... 10 more
`

Bylo by možné chybu prověřit, budu rád za každou radu či informaci kde může být problém, 

Díky,
Jonáš Květ

**Comment by vlahoda** [comment]
Jakou verzi Krameria pouzivate? Podle chyboveho vypisu se snazite importovat balicky podle nove specifikace, obsahujici MODS a DC elementy s identifikatory pro jednotlive stranky. Ty umi importovat az Kramerius v aktualni verzi 5.5.0.

**Comment by kvetjo** [comment]
Používeme 5.4.2. 
Zkusíme s novou verzí. Díky moc za pomoc
