### ISSUE TITLE
Problém s označením dokumentů DNNT labelem (5.4.7)

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#792]
Proces s označením DNNT labelem končí statusem Warning. Chybovou hlášku posílám níže. Když se podívám do schématu SOLR - chybí tam pole "dnnt-labels". Je potřeba ho vytvořit?

`Exception in thread &#034;Thread-2&#034; com.sun.jersey.api.client.UniformInterfaceException: GET http://solrIP:8983/solr/kramerius/select?q=%28pid_path%3A%28%22uuid%3A7784a340-b72e-11e8-bbaa-005056827e52%22%29+-dnnt-labels%3A%5B*+TO+*%5D%29+%7C%7C+%28pid_path%3A%28%22uuid%3A7784a340-b72e-11e8-bbaa-005056827e52%22%29+NOT+dnnt-labels%3Adnnto%29&amp;rows=100&amp;cursorMark=*&amp;sort=PID+asc&amp;fl=PID returned a response status of 400 Bad Request
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
	at cz.incad.kramerius.services.IterationUtils.executeQuery(IterationUtils.java:238)
	at cz.incad.kramerius.services.IterationUtils.pidsCursorQuery(IterationUtils.java:136)
	at cz.incad.kramerius.services.IterationUtils.cursorIteration(IterationUtils.java:50)
	at cz.incad.kramerius.workers.DNNTWorker.fetchAllPids(DNNTWorker.java:96)
	at cz.incad.kramerius.workers.DNNTWorker.run(DNNTWorker.java:152)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by pavel-stastny** [comment]
Jo, jo... musí se updatovat schéma solru.    https://github.com/ceskaexpedice/kramerius/blob/dnnt/installation/solr-6.x/kramerius/conf/managed-schema#L567.  

Přidám do popisu instalace.
