### ISSUE TITLE
Proces označení DNNT zamrzl jako running (5.4.7)

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#795]
Proces označení DNNT s labelem zamrzl jako running (viz screen). Již 40minut je ve stavu running a od té doby neproběhl žádný zápis do logu. Níže přikládám log procesu.

[stout.out.txt](https://github.com/ceskaexpedice/kramerius/files/5955008/stout.out.txt)

![Snímek z 2021-02-10 01-18-07](https://user-images.githubusercontent.com/33415849/107446205-379b4880-6b3e-11eb-9e9b-991a155c8c24.png)

**Comment by pavel-stastny** [comment]
Ve standardnim vypisu procesu v terminalu (ps -Af) se objevuje ?

**Comment by anton-svetlosak** [comment]
@pavel-stastny @jahhoo Zbežne som sa pozrel na DNNTWorker.java. Problém može byť v metóde commit https://github.com/ceskaexpedice/kramerius/blob/f3cf49f776e764d3d29e1f0a1d9a147f199258c5/processes/dnntflag/src/main/java/cz/incad/kramerius/DNNTWorker.java#L120 , ktorá je mimo try, cactch bloku. Commit v SOLR niekedy trvá dlho (minuty), viac ako default timeout pri http volaní 30 sec. Predpokladám, že to spadlo na timeout alebo na inú chybu pri commite, bolo to mimo try catch, tak sa chyba nezalogovala a nedošlo k ukončeniu procesu v Krameriu - nezavovala se await metoda (this.barrier.await()).

**Comment by pavel-stastny** [comment]
@anton-svetlosak  To by mohlo byt ono.  Ted se sice vola jiny proces ale toto tam zustalo stejne.  Diky.

**Comment by jahhoo** [comment]
Poslední spuštění dávky odznačení DNNT doběhlo s Warningem:



```
`Exception in thread &#034;Thread-20&#034; javax.xml.ws.soap.SOAPFaultException: java.util.ConcurrentModificationException
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy38.getRelationships(Unknown Source)
	at cz.incad.kramerius.workers.DNNTWorker.changeDNNTInFOXML(DNNTWorker.java:212)
	at cz.incad.kramerius.workers.DNNTWorkerFlag.changeFOXML(DNNTWorkerFlag.java:45)
	at cz.incad.kramerius.workers.DNNTWorker.run(DNNTWorker.java:150)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread &#034;Thread-218&#034; javax.xml.ws.soap.SOAPFaultException: java.util.ConcurrentModificationException
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy38.purgeRelationship(Unknown Source)
	at cz.incad.kramerius.workers.DNNTWorker.changeDNNTInFOXML(DNNTWorker.java:216)
	at cz.incad.kramerius.workers.DNNTWorkerFlag.changeFOXML(DNNTWorkerFlag.java:45)
	at cz.incad.kramerius.workers.DNNTWorker.run(DNNTWorker.java:150)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread &#034;Thread-357&#034; javax.xml.ws.soap.SOAPFaultException: java.util.ConcurrentModificationException
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy38.getRelationships(Unknown Source)
	at cz.incad.kramerius.workers.DNNTWorker.changeDNNTInFOXML(DNNTWorker.java:212)
	at cz.incad.kramerius.workers.DNNTWorkerFlag.changeFOXML(DNNTWorkerFlag.java:45)
	at cz.incad.kramerius.workers.DNNTWorker.run(DNNTWorker.java:150)
	at java.lang.Thread.run(Thread.java:748)
Úno 10, 2021 3:03:49 ODP. cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: system error file contains errors
cz.incad.kramerius.processes.WarningException: system error file contains errors
	at cz.incad.kramerius.processes.impl.ProcessStarter.checkErrorFile(ProcessStarter.java:185)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:127)
```
`
