### ISSUE TITLE
[K5] NullPointerException při importu FOXML souborů do Krameria

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius#816]
**Celý výpis lrOut/stout.out:**
```
c435-8adc-4028-a997-9c7eb131fbc4
Apr 02, 2021 1:49:00 PM org.kramerius.Import ingest
INFO: Ingested:uuid:d5c1c435-8adc-4028-a997-9c7eb131fbc4 in 40ms, count:49
Apr 02, 2021 1:49:00 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:d8a1087c-578b-43d8-b850-7fb5e178c1a8
Apr 02, 2021 1:49:00 PM org.kramerius.Import ingest
INFO: Ingested:uuid:d8a1087c-578b-43d8-b850-7fb5e178c1a8 in 38ms, count:50
Apr 02, 2021 1:49:00 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:db907001-c873-4ca9-909d-4d34279035fb
Apr 02, 2021 1:49:00 PM org.kramerius.Import ingest
INFO: Ingested:uuid:db907001-c873-4ca9-909d-4d34279035fb in 29ms, count:51
Apr 02, 2021 1:49:00 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:de92106b-bd79-4ce2-9043-df3fd62c875f
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:de92106b-bd79-4ce2-9043-df3fd62c875f in 37ms, count:52
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:df34f872-c9db-4034-884d-c74448ba6e77
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:df34f872-c9db-4034-884d-c74448ba6e77 in 34ms, count:53
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:e24312f0-f83a-4c0c-87be-6ae1cccb1208
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:e24312f0-f83a-4c0c-87be-6ae1cccb1208 in 32ms, count:54
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:e41bdd3d-62d4-4916-9901-a7be90613fcd
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:e41bdd3d-62d4-4916-9901-a7be90613fcd in 32ms, count:55
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:e4e809d0-6e75-4a9c-bcf8-234cec80e773
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:e4e809d0-6e75-4a9c-bcf8-234cec80e773 in 38ms, count:56
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:e8f58ced-7631-45de-b77e-feae41e05af4
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:e8f58ced-7631-45de-b77e-feae41e05af4 in 34ms, count:57
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:e9898ac4-bf80-4e2a-a60e-3ae6cfd696f9
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:e9898ac4-bf80-4e2a-a60e-3ae6cfd696f9 in 40ms, count:58
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:ea67a22c-6d57-4933-b34b-20278bb6baff
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:ea67a22c-6d57-4933-b34b-20278bb6baff in 30ms, count:59
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:ecb7b0e4-59fb-4a50-9cf3-387a386b055e
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:ecb7b0e4-59fb-4a50-9cf3-387a386b055e in 33ms, count:60
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Merging with existing object uuid:ecc519de-ae95-43ee-9d3a-35585d66b646
Apr 02, 2021 1:49:01 PM org.kramerius.Import ingest
INFO: Ingested:uuid:ecc519de-ae95-43ee-9d3a-35585d66b646 in 33ms, count:61
Apr 02, 2021 1:49:01 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.NullPointerException
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:229)
	at org.kramerius.Import.visitAllDirsAndFiles(Import.java:240)
	at org.kramerius.Import.ingest(Import.java:128)
	at org.kramerius.Import.main(Import.java:95)
	at org.kramerius.imports.ParametrizedImport.process(ParametrizedImport.java:72)
	... 5 more
```

Fedora neměla žádný problém (jen INFO výpisy).

**Popis:**
Snažím se do [svého Kraméria](https://backend.ds-coil.uibk.ac.at/search/) naimportovat nějaká díla z MZK Kramréria a mám problém s importem, vypadá to, že někde něco chybí, ale moc nevím co. FOXML  soubory jsem exportoval přes K4-tools a importuji je přes GUI. Již dříve jsem se snažil [naimportovat dílo](https://github.com/moravianlibrary/s2i-kramerius/blob/master/krameriusinit/foxmlinit.tar), co bylo exportováno kdysi dávno a to se naimportovalo bez problémů.

Jsem si jistý, že jsem nepodal dostatek informací, ale opravdu nevím, co se děje, tak se prosím ptejte.

**Comment by vlahoda** [comment]
To vypada na nejaky problem s adresarovou strukturou toho importniho adresare nebo s pristupovymi pravy k souborum/adresarum v nem. Importni proces prochazi ten importni adresar rekurzivne a vola se tam toto:
```
       if (importFile.isDirectory()) {
            File[] children = importFile.listFiles();
```
Podle toho stacktrace odhaduji, ze metoda listFiles na nekterem adresari vraci hodnotu null. A v dokumentaci te funkce se uvadi:  Returns null if this abstract pathname does not denote a directory, or if an I/O error occurs.
Directory to ale zjevne je, jinak by se ten kod vubec nevolal. Takze zrejme nastal zminovany I/O error pri pokusu o cteni adresare. Pokud ten stacktrace neobsahuje zadne dalsi podrobnosti, zkontrolujte prosim strukturu importniho adresare, jestli v nem nejsou nejake skryte podadresare apod.

**Comment by SPXcz** [comment]
Opravdu byla chyba ve vymezení práv, je potřeba rwx rx rx. Moc díky!
