### ISSUE TITLE
getSolrDataInternal - chyba zakódování URL

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#822]
Kramerius 5.4.8 nám vrací chyby:

```
[2021-04-14 11:04:38,181] SEVERE [cz.incad.kramerius.auth.thirdparty.ExtAuthFilter doFilter] () - Illegal character in query at index 184: http://10.x.x.x:8983/solr/kramerius/select?hl.snippets=10&q=parent_pid%3A%22uuid%3Ade56a110-a995-11e7-ae0a-005056827e52%22+AND+text_ocr%3Apata+&hl=true&hl.simple.post=%3C%3C&fl=PID& frydecký architekti*=&hl.fragsize=1&hl.fl=text_ocr&rows=20&hl.simple.pre=%3E%3E&wt=json
java.lang.IllegalArgumentException: Illegal character in query at index 184: http://10.x.x.x:8983/solr/kramerius/select?hl.snippets=10&q=parent_pid%3A%22uuid%3Ade56a110-a995-11e7-ae0a-005056827e52%22+AND+text_ocr%3Apata+&hl=true&hl.simple.post=%3C%3C&fl=PID& frydecký architekti*=&hl.fragsize=1&hl.fl=text_ocr&rows=20&hl.simple.pre=%3E%3E&wt=json
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at cz.incad.kramerius.utils.solr.SolrUtils.getSolrDataInternal(SolrUtils.java:279)
	at cz.incad.kramerius.impl.SolrAccessImpl.request(SolrAccessImpl.java:223)
	at cz.incad.kramerius.rest.api.k5.client.search.SearchResource.getEntityJSON(SearchResource.java:214)
	at cz.incad.kramerius.rest.api.k5.client.search.SearchResource.selectJSON(SearchResource.java:192)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
	at cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:270)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in query at index 184: http://10.x.x.x:8983/solr/kramerius/select?hl.snippets=10&q=parent_pid%3A%22uuid%3Ade56a110-a995-11e7-ae0a-005056827e52%22+AND+text_ocr%3Apata+&hl=true&hl.simple.post=%3C%3C&fl=PID& frydecký architekti*=&hl.fragsize=1&hl.fl=text_ocr&rows=20&hl.simple.pre=%3E%3E&wt=json
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 60 more
```

Dle analýzy naší podpory:

Pravdepodobne se jedna o chybu, ze cast te uri neni zakodovana: http://10.x.x.x:8983/solr/kramerius/select?hl.snippets=10&q=parent_pid%3A%22uuid%3Ade56a110-a995-11e7-ae0a-005056827e52%22+AND+text_ocr%3Apata+&hl=true&hl.simple.post=%3C%3C&fl=PID& frydecký architekti*=&hl.fragsize=1&hl.fl=text_ocr&rows=20&hl.simple.pre=%3E%3E&wt=json

Podle logu se jedna o metodu getSolrDataInternal

**Comment by zabak** [comment]
Předpokládám, že v K7 toto nenastává...?
