### ISSUE TITLE
K5.6.0 - nefunguje poslední fáze replikace

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#828]
Při replikaci díla padá poslední fáze replikace, spouštění indexace.

```
May 04, 2021 4:20:36 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: com.google.inject.CreationException: Guice creation errors:
1) No implementation for cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=database) was bound.
  while locating cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=database)
    for field at cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs.databaseAccessLog(AggregatedAccessLogs.java:24)
  while locating cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs
    for parameter 1 at cz.incad.kramerius.impl.FedoraAccessImpl.&lt;init&gt;(FedoraAccessImpl.java:72)
  at org.kramerius.consistency.Consistency$_Module.configure(Consistency.java:203)
2) No implementation for cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=database) was bound.
  while locating cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=database)
    for field at cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs.databaseAccessLog(AggregatedAccessLogs.java:24)
  at org.kramerius.consistency.Consistency$_Module.configure(Consistency.java:204)
3) No implementation for cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=dnnt) was bound.
  while locating cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=dnnt)
    for field at cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs.dnntAccessLog(AggregatedAccessLogs.java:24)
  while locating cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs
    for parameter 1 at cz.incad.kramerius.impl.FedoraAccessImpl.&lt;init&gt;(FedoraAccessImpl.java:72)
  at org.kramerius.consistency.Consistency$_Module.configure(Consistency.java:203)
4) No implementation for cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=dnnt) was bound.
  while locating cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=dnnt)
    for field at cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs.dnntAccessLog(AggregatedAccessLogs.java:24)
  at org.kramerius.consistency.Consistency$_Module.configure(Consistency.java:204)
4 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.kramerius.replications.ThirdPhase.start(ThirdPhase.java:64)
	at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:132)
	at org.kramerius.replications.K4ReplicationProcess.replications(K4ReplicationProcess.java:86)
	... 5 more
```
Vypadá jako cyklická závislost mezi komponenty v _org.kramerius.consistency.Consistency.\_Module_

**Comment by kazooo** [comment]
Nefunguje i import
```
May 05, 2021 3:21:29 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: com.google.inject.CreationException: Guice creation errors:
1) No implementation for cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=database) was bound.
  while locating cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=database)
    for field at cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs.databaseAccessLog(AggregatedAccessLogs.java:24)
  at org.kramerius.ImportModule.configure(Import.java:677)
2) No implementation for cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=dnnt) was bound.
  while locating cz.incad.kramerius.statistics.StatisticsAccessLog annotated with @com.google.inject.name.Named(value=dnnt)
    for field at cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs.dnntAccessLog(AggregatedAccessLogs.java:24)
  at org.kramerius.ImportModule.configure(Import.java:677)
2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.kramerius.Import.ingest(Import.java:102)
	at org.kramerius.Import.main(Import.java:96)
	at org.kramerius.imports.ParametrizedImport.process(ParametrizedImport.java:72)
	... 5 more
```
Zkusil jsem odstranit chybu samostatně, ale v Guice se dobře neorientuju a vypadá to na větší opravy.
Prosím o urgentní vyřešení, děkuju.

**Comment by kazooo** [comment]
@pavel-stastny děkuju za opravu, už nepadá na této chybě, ale vypadá že ThirdPhase v replikaci nemá přístupové údaje Fedory
```INFO: Ingested:uuid:f30ad85a-a582-4c25-b43d-cdb7ff6bbbf9 in 24ms, count:37
May 18, 2021 8:20:36 AM org.kramerius.replications.K4ReplicationProcess phaseCompleted
INFO: PHASE &#039;org.kramerius.replications.SecondPhase&#039; completed
May 18, 2021 8:20:36 AM org.kramerius.replications.K4ReplicationProcess start
INFO: STARTING PHASE &#039;org.kramerius.replications.ThirdPhase&#039;
May 18, 2021 8:20:36 AM org.kramerius.replications.ThirdPhase$Paths pathEmitted
INFO: emitted path &#039;&#039;uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23&#039;&#039;
May 18, 2021 8:20:36 AM org.kramerius.replications.ThirdPhase$Paths pathEmitted
INFO: changed path is uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23
May 18, 2021 8:20:36 AM org.kramerius.replications.ThirdPhase start
INFO:  found root is uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23
May 18, 2021 8:20:37 AM cz.incad.kramerius.utils.RESTHelper inputStream
SEVERE: http://fedora:8080/fedora/get/uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23/RELS-EXT returned status code 403
May 18, 2021 8:20:37 AM cz.incad.kramerius.impl.FedoraAccessImpl processSubtree
WARNING: could not read root RELS-EXT, skipping object  (uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23):java.io.IOException: Server returned HTTP response code: 403 for URL: http://fedora:8080/fedora/get/uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23/RELS-EXT
May 18, 2021 8:20:37 AM cz.incad.kramerius.utils.RESTHelper inputStream
SEVERE: http://fedora:8080/fedora/get/uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23/RELS-EXT returned status code 403
May 18, 2021 8:20:37 AM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.NullPointerException
	at org.kramerius.consistency.Consistency$TreeProcess.skipBranch(Consistency.java:144)
	at cz.incad.kramerius.impl.FedoraAccessImpl.processSubtree(FedoraAccessImpl.java:832)
	at org.kramerius.consistency.Consistency.checkConsitency(Consistency.java:78)
	at org.kramerius.replications.ThirdPhase.start(ThirdPhase.java:66)
	at org.kramerius.replications.K4ReplicationProcess.start(K4ReplicationProcess.java:132)
	at org.kramerius.replications.K4ReplicationProcess.replications(K4ReplicationProcess.java:86)
	... 5 more
```
Stejný problém u importu
```
INFO: Indexer initialized
May 18, 2021 8:35:10 AM cz.incad.kramerius.indexer.Indexer run
INFO: Current index time: 5/18/21 8:35 AM
May 18, 2021 8:35:10 AM cz.incad.kramerius.indexer.Indexer update
INFO: Update index...
May 18, 2021 8:35:10 AM cz.incad.kramerius.indexer.FedoraOperations updateIndex
INFO: updateIndex action=reindexDoc value=uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23
May 18, 2021 8:35:10 AM cz.incad.kramerius.indexer.FedoraOperations getFoxmlFromPid
INFO: getFoxmlFromPid pid=uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23
May 18, 2021 8:35:11 AM cz.incad.kramerius.indexer.FedoraOperations getFoxmlFromPid
SEVERE: Error getting object
javax.xml.ws.soap.SOAPFaultException: Authorization Denied Caused by: 
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:140)
	at com.sun.proxy.$Proxy32.export(Unknown Source)
	at cz.incad.kramerius.indexer.FedoraOperations.getFoxmlFromPid(FedoraOperations.java:68)
	at cz.incad.kramerius.indexer.SolrOperations.reindexDoc(SolrOperations.java:248)
	at cz.incad.kramerius.indexer.SolrOperations.updateIndex(SolrOperations.java:166)
	at cz.incad.kramerius.indexer.FedoraOperations.updateIndex(FedoraOperations.java:50)
	at cz.incad.kramerius.indexer.Indexer.updateIndex(Indexer.java:118)
	at cz.incad.kramerius.indexer.Indexer.doUpdate(Indexer.java:112)
	at cz.incad.kramerius.indexer.Indexer.update(Indexer.java:103)
	at cz.incad.kramerius.indexer.Indexer.run(Indexer.java:76)
	at cz.incad.kramerius.indexer.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)
```
