### ISSUE TITLE
Problém s právy administrátora - 5.7.0

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#837]
Po upgrade na 5.7.0 - pokud jsem přihlášen jako administrátor chybí všechny funkce ve "více..." 

![Snímek z 2021-06-10 14-46-55](https://user-images.githubusercontent.com/33415849/121527631-e5d6d200-c9fa-11eb-9d37-f107fc0631a3.png)

**Comment by pavel-stastny** [comment]
@jahhoo Slo by, treba mailem, poslat vypis prav z tabulky `right_entity `(konkretne pravo `display_admin_menu`)?  A druha otakzka, konzole prohlizece ukazuje nejake chyby ?

**Comment by jahhoo** [comment]
Upgradováno na oficiálně vydanou verzi. Stále se nic nezobrazuje. Konzole je OK

![Snímek z 2021-06-13 21-23-59](https://user-images.githubusercontent.com/33415849/121819505-bbe90e00-cc8d-11eb-9a72-1e09878328ea.png)


```
select * from right_entity where action='display_admin_menu';
 right_id | update_timestamp |  uuid  |       action       | rights_crit | user_id | group_id | fixed_priority 
----------+------------------+--------+--------------------+-------------+---------+----------+----------------
       20 |                  | uuid:1 | display_admin_menu |             |         |        2 |               
       60 |                  | uuid:1 | display_admin_menu |             |         |        6 |          

```

```

select * from user_group_mapping;
 group_id |    gname     | personal_admin_id | user_id 
----------+--------------+-------------------+---------
        2 | k4_admins    |                   |       1
        2 | k4_admins    |                   |       2
        1 | common_users |                 2 |       2
        2 | k4_admins    |                   |       3
        2 | k4_admins    |                   |       1
        6 | obsah_admin  |                 1 |       5
        6 | obsah_admin  |                 1 |       6
        6 | obsah_admin  |                 1 |       7
        6 | obsah_admin  |                 1 |       3
        3 | public_users |                -1 |       9
        3 | public_users |                -1 |      10
        2 | k4_admins    |                   |       8
```

Uživatel pod kterým se přihlašuji má ID "1"

**Comment by jahhoo** [comment]
@pavel-stastny  Nemůže být problém tady?

```
16:16:46.513 [http-bio-8080-exec-35] DEBUG o.j.r.core.SynchronousDispatcher - PathInfo: /aplikatorService/getPage/UserView:Users_table
TID: [2021-06-15 16:16:46,513] INFO [org.aplikator.server.persistence.empiredb.EmpireDbPersister getRecords] () - GETPAGE Query: SELECT t1.USER_ID, t1.LOGINNAME, t1.NAME, t1.SURNAME
FROM USER_ENTITY t1
ORDER BY t1.LOGINNAME
LIMIT 15 OFFSET 18660
16:16:46.514 [http-bio-8080-exec-35] DEBUG org.apache.empire.db.DBDatabase - Executing: SELECT t1.USER_ID, t1.LOGINNAME, t1.NAME, t1.SURNAME
FROM USER_ENTITY t1
ORDER BY t1.LOGINNAME
LIMIT 15 OFFSET 18660
16:16:46.530 [http-bio-8080-exec-35] DEBUG org.apache.empire.db.DBDatabase - executeQuery successful in 16 ms
TID: [2021-06-15 16:16:46,530] INFO [org.aplikator.server.persistence.empiredb.EmpireDbPersister getRecords] () - executed in 17 ms
TID: [2021-06-15 16:16:46,532] SEVERE [cz.incad.kramerius.utils.database.JDBCQueryTemplate executeQuery] () - ERROR: relation "labels_entity" does not exist
  Pozice: 210
org.postgresql.util.PSQLException: ERROR: relation "labels_entity" does not exist
  Pozice: 210
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at cz.incad.kramerius.utils.database.JDBCQueryTemplate.executeQuery(JDBCQueryTemplate.java:83)
	at cz.incad.kramerius.security.impl.DatabaseRightsManager.findRights(DatabaseRightsManager.java:246)
	at cz.incad.kramerius.security.impl.DatabaseRightsManager.resolve(DatabaseRightsManager.java:276)
	at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequest.isAllowedInternalForFedoraDocuments(IsActionAllowedFromRequest.java:97)
	at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequestCached.isAllowedInternalForFedoraDocuments(IsActionAllowedFromRequestCached.java:101)
	at cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequest.isActionAllowed(IsActionAllowedFromRequest.java:58)
	at cz.incad.kramerius.rest.api.k5.client.item.decorators.DNNTDecorator$1.acceptElement(DNNTDecorator.java:93)
	at cz.incad.kramerius.utils.XMLUtils.findElement(XMLUtils.java:300)
	at cz.incad.kramerius.rest.api.k5.client.item.decorators.DNNTDecorator.decorate(DNNTDecorator.java:83)
	at cz.incad.kramerius.rest.api.k5.client.utils.JSONUtils.pidAndModelDesc(JSONUtils.java:58)
	at cz.incad.kramerius.rest.api.k5.client.item.ItemResource.basic(ItemResource.java:565)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
	at cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.XSSFilter.doFilter(XSSFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:270)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by pavel-stastny** [comment]
@jahhoo Jo, to je ono.  Pri startu se nevytvorila tabulka labels_entity.  Jaka verze postgresu to je ? A neobjevovala se vyjimka jiz pri startu (ze nemuze vytvorit tabulky nebo index ?)

**Comment by jahhoo** [comment]
@pavel-stastny PostgreSQL 9.2.24. Žádné upozornění se nezobrazilo. Kramerius se na první pohled tváří normálně.

**Comment by pavel-stastny** [comment]
Verze 9.2 nepodporovala syntax  `CREATE SEQUENCE IF NOT EXISTS`.  Pri startu vybihala vyjimka  chyba sql syntaxe.
