### ISSUE TITLE
Proces generování statistik - 5.7.1

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#848]
Spustil jsem proces generování statistik, ale je jen ve stavu PLANNED
![Snímek z 2021-06-29 15-29-19](https://user-images.githubusercontent.com/33415849/123808051-b1b34a80-d8f0-11eb-8c91-c2a8db901506.png)

![Snímek z 2021-06-29 15-29-28](https://user-images.githubusercontent.com/33415849/123808058-b415a480-d8f0-11eb-8dd9-d0a38a57a84e.png)

Logy:
```
SEVERE [cz.incad.kramerius.statistics.accesslogs.database.DatabaseStatisticsAccessLogImpl reportAccess] () - Unable to find server array type for provided name TEXT.
org.postgresql.util.PSQLException: Unable to find server array type for provided name TEXT.
	at org.postgresql.jdbc4.AbstractJdbc4Connection.createArrayOf(AbstractJdbc4Connection.java:83)
	at org.postgresql.jdbc4.Jdbc4Connection.createArrayOf(Jdbc4Connection.java:21)
	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.createArrayOf(DelegatingConnection.java:560)
	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.createArrayOf(DelegatingConnection.java:560)
	at cz.incad.kramerius.utils.database.JDBCUpdateTemplate.setParam(JDBCUpdateTemplate.java:181)
	at cz.incad.kramerius.utils.database.JDBCUpdateTemplate.executeUpdate(JDBCUpdateTemplate.java:79)
	at cz.incad.kramerius.statistics.accesslogs.database.DatabaseStatisticsAccessLogImpl$InsertDetail.executeJDBCCommand(DatabaseStatisticsAccessLogImpl.java:441)
	at cz.incad.kramerius.utils.database.JDBCTransactionTemplate.updateWithTransaction(JDBCTransactionTemplate.java:119)
	at cz.incad.kramerius.utils.database.JDBCTransactionTemplate.updateWithTransaction(JDBCTransactionTemplate.java:89)
	at cz.incad.kramerius.statistics.accesslogs.database.DatabaseStatisticsAccessLogImpl.reportAccess(DatabaseStatisticsAccessLogImpl.java:206)
	at cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs.reportAccess(AggregatedAccessLogs.java:29)
	at cz.incad.Kramerius.imaging.ZoomifyServlet.reportAccess(ZoomifyServlet.java:370)
	at cz.incad.Kramerius.imaging.ZoomifyServlet.renderXMLDescriptor(ZoomifyServlet.java:165)
	at cz.incad.Kramerius.imaging.ZoomifyServlet.doGet(ZoomifyServlet.java:134)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.XSSFilter.doFilter(XSSFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:270)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

TID: [2021-06-29 16:55:24,285] SEVERE [cz.incad.kramerius.statistics.accesslogs.database.DatabaseStatisticsAccessLogImpl reportAccess] () - Unable to find server array type for provided name TEXT.
org.postgresql.util.PSQLException: Unable to find server array type for provided name TEXT.
	at org.postgresql.jdbc4.AbstractJdbc4Connection.createArrayOf(AbstractJdbc4Connection.java:83)
	at org.postgresql.jdbc4.Jdbc4Connection.createArrayOf(Jdbc4Connection.java:21)
	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.createArrayOf(DelegatingConnection.java:560)
	at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.createArrayOf(DelegatingConnection.java:560)
	at cz.incad.kramerius.utils.database.JDBCUpdateTemplate.setParam(JDBCUpdateTemplate.java:181)
	at cz.incad.kramerius.utils.database.JDBCUpdateTemplate.executeUpdate(JDBCUpdateTemplate.java:79)
	at cz.incad.kramerius.statistics.accesslogs.database.DatabaseStatisticsAccessLogImpl$InsertDetail.executeJDBCCommand(DatabaseStatisticsAccessLogImpl.java:441)
	at cz.incad.kramerius.utils.database.JDBCTransactionTemplate.updateWithTransaction(JDBCTransactionTemplate.java:119)
	at cz.incad.kramerius.utils.database.JDBCTransactionTemplate.updateWithTransaction(JDBCTransactionTemplate.java:89)
	at cz.incad.kramerius.statistics.accesslogs.database.DatabaseStatisticsAccessLogImpl.reportAccess(DatabaseStatisticsAccessLogImpl.java:206)
	at cz.incad.kramerius.statistics.accesslogs.AggregatedAccessLogs.reportAccess(AggregatedAccessLogs.java:29)
	at cz.incad.Kramerius.imaging.ZoomifyServlet.reportAccess(ZoomifyServlet.java:370)
	at cz.incad.Kramerius.imaging.ZoomifyServlet.renderXMLDescriptor(ZoomifyServlet.java:165)
	at cz.incad.Kramerius.imaging.ZoomifyServlet.doGet(ZoomifyServlet.java:134)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.XSSFilter.doFilter(XSSFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:270)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by pavel-stastny** [comment]
@jahhoo jaka je to verze postgresu ?

**Comment by jahhoo** [comment]
@pavel-stastny PostgreSQL 9.2.24

**Comment by anton-svetlosak** [comment]
@pavel-stastny @jahhoo myslim, ze sa jedna o problem so schedulerom. Hned po starte tomcatu sa v logu nachadza hlaska
```
INFO [cz.incad.kramerius.processes.impl.ProcessSchedulerImpl shutdown] () - canceling process scheduler
```

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o reakciu ci je to vo verzi 5.7.2 opraveno

**Comment by pavel-stastny** [comment]
@JanMeritus Ano, proces do lp.st pridan, nicmene lze resit i konfiguraci.  (Pridanim procesu do `~/.kramerius4/lp.xml`). Neni nutno mit novy build

**Comment by jahhoo** [comment]
@pavel-stastny je nějaké doporučení, jak optimalizovat tomcat, aby to generovalo spolehlivě statistiky?

![Snímek z 2021-07-13 11-01-42](https://user-images.githubusercontent.com/33415849/125423855-b235e232-5c51-487a-923f-42991e77f9a8.png)

**Comment by JanMeritus** [comment]
@pavel-stastny ahoj, aj s 4G to umira na 20 dni z mesice leden, kazdy den generuje cca 20-30 min strojovyho casu, 7h trvalo 20 dnu. Reseni neni moc spolehlivy pro vetsi instance.

**Comment by pavel-stastny** [comment]
@JanMeritus Ahoj, pamet se da resit ale strojovy cas u zaznamu, ktere nemaji vsechny polozky v db (musi se doptavat fedory : publishers, isbn, atd..), to zkratit uplne nejde.  Proces jde spustit s promennou `nkp.logs.disablefedoraaccess=true` , ktera zapricini, ze vse jede ciste z db.  Muzes pak porovnat cas straveny obohacovanim dat z fedory.

**Comment by JanMeritus** [comment]
@pavel-stastny ani se 4G/512 pameti to neprechadzi a nekde v strede to havaruje na heapu. Jak to tedy resit? Pokud to nejde zrychlit tak aby to bylo aspon spolehlivy
