### ISSUE TITLE
Spouštění procesu "setpublic" přes API

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#856]
Zdravím,

přestalo mi fungovat spouštění procesu "setpublic" přes API a netuším, čím by to mohlo být. Používám příkaz:

curl -u login:heslo -H "Content-Type: application/json" -d '{"parameters":["uuid:001dc090-83fc-11dd-8af9-000d606f5dc6"]}' -X POST http://192.168.192.74:8080/search/api/v4.6/processes?def=setpublic

dřív fungoval, ale teď proces spadne s chybou:

```
Jul 19, 2021 3:22:44 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at cz.incad.kramerius.service.impl.PolicyServiceImpl.main(PolicyServiceImpl.java:206)
	... 5 more
```

Aktuálně provozujeme Kraméria verze 5.5.0

**Comment by vlahoda** [comment]
U tohoto procesu pribyl jeste treti boolean parametr, hodnota true znamena, ze se viditelnost  public nastavi pouze pro zvolenou uroven stromu dokumentu, hodnota false znamena nastaveni i pro vsechny podrizene uzly dokumentu.

**Comment by svetlym** [comment]
Děkuju za rychlou a informativní odpověď. Už to funguje, zavírám issue.

**Comment by kazooo** [comment]
Zdravim, @vlahoda plati to stejne i pro "setprivate" process? Je to popsane nekde v dokumentaci?

**Comment by vlahoda** [comment]
@kazoo Ano, plati, to je stejny proces, lisi se hodnotou prvniho parametru. Zmena byla implementovana 3.3.2020 jako patch z KNAV, bylo pri tom upraveno volani z admin GUI, ale souhrnna dokumentace k parametrum procesu vlastne nikde na wiki neni.
