### ISSUE TITLE
Chyba při spouštění Kraméria

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#857]
Zdravím,

Kramérius normálně naběhne, při startu ale vypisuje do logu následující chybu:

```
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/home/kramerius/fedora/tomcat/webapps/search/WEB-INF/lib/stax-ex-2.0.1.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:136)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:59)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:208)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:118)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2058)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1934)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1900)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1885)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1317)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:876)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:374)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5378)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Aktualizoval jsem na verzi 5.7.2, ale dělal to i ve starších verzích. Jak to můžu opravit?

**Comment by vlahoda** [comment]
Jakou verzi Tomcatu a Javy pouzivate?

**Comment by svetlym** [comment]
Server version: Apache Tomcat/7.0.55
openjdk version "1.8.0_292"

**Comment by vlahoda** [comment]
Zkuste prosim upgradovat Tomcat, bud na aktualni verzi z vetve 7 (7.0.109) nebo z 8.5 ( 8.5.68). Zrejme to je chyba v Tomcatu a byla opravena ve verzi 7.0.76
