### ISSUE TITLE
Testování K7 - import více uuid:

### ISSUE THREAD

**Issue by hlavacekrene** [ceskaexpedice/kramerius#897]
Při importování, poud se importuje více kořenů z import adresáře (více jak 15, ale ani ta patnácka nemusí být pravidlem), 
tak se zobrazí "Varování" a to znamená, že ne všechny kořenové uuid: se z import adresáře naimportují, některé se náhodně vynechají.

Jun 14, 2022 7:57:10 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from 'indexer-7.0.2' to 'indexer.properties'
Jun 14, 2022 7:57:10 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from 'import-mets-7.0.2' to 'migration.properties'
Jun 14, 2022 7:57:10 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from 'import-cmdtool-7.0.2' to 'migration.properties'
Jun 14, 2022 7:57:10 PM cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from 'common-7.0.2' to 'configuration.properties'
Jun 14, 2022 7:57:10 PM cz.incad.kramerius.processes.starter.ProcessUpdatingChannel$StandardProcessUpdatingChannel updatePID
INFO: requesting url: http://localhost:8080/search//lr?action=updatePID&uuid=680f239d-20ee-473a-aaca-fe2be0d33e8e&pid=3496
Jun 14, 2022 7:57:12 PM com.hazelcast.client.HazelcastClient
INFO: akubrasync [dev] [3.11.2] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
Jun 14, 2022 7:57:12 PM com.hazelcast.core.LifecycleService
INFO: akubrasync [dev] [3.11.2] HazelcastClient 3.11.2 (20190216 - e302506) is STARTING
Jun 14, 2022 7:57:12 PM com.hazelcast.client.spi.ClientInvocationService
INFO: akubrasync [dev] [3.11.2] Running with 2 response threads
Jun 14, 2022 7:57:12 PM com.hazelcast.core.LifecycleService
INFO: akubrasync [dev] [3.11.2] HazelcastClient 3.11.2 (20190216 - e302506) is STARTED
Jun 14, 2022 7:57:12 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: akubrasync [dev] [3.11.2] Trying to connect to [127.0.0.1]:5701 as owner member
Jun 14, 2022 7:57:12 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: akubrasync [dev] [3.11.2] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:60549->/127.0.0.1:5701}, remoteEndpoint=[10.0.16.11]:5701, lastReadTime=2022-06-14 19:57:12.472, lastWriteTime=2022-06-14 19:57:12.470, closedTime=never, connected server version=3.11.2} as owner with principal ClientPrincipal{uuid='cd84d1ac-86ed-43ec-9c82-7b3d15c12ad9', ownerUuid='e401d508-bc49-4f93-8f0c-b8b752e6be69'}
Jun 14, 2022 7:57:12 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: akubrasync [dev] [3.11.2] Authenticated with server [10.0.16.11]:5701, server version:3.11.2 Local address: /127.0.0.1:60549
Jun 14, 2022 7:57:12 PM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: akubrasync [dev] [3.11.2]
Members [1] {
Member [10.0.16.11]:5701 - e401d508-bc49-4f93-8f0c-b8b752e6be69
}
Jun 14, 2022 7:57:12 PM com.hazelcast.core.LifecycleService
INFO: akubrasync [dev] [3.11.2] HazelcastClient 3.11.2 (20190216 - e302506) is CLIENT_CONNECTED
Jun 14, 2022 7:57:12 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: akubrasync [dev] [3.11.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jun 14, 2022 7:57:12 PM org.ehcache.core.EhcacheManager createCache
INFO: Cache 'DigitalObjectCache' created in EhcacheManager.
Jun 14, 2022 7:57:12 PM cz.incad.kramerius.processes.starter.ProcessUpdatingChannel$StandardProcessUpdatingChannel updateName
INFO: requesting url: http://localhost:8080/search//lr?action=updateName&uuid=680f239d-20ee-473a-aaca-fe2be0d33e8e&name=Import+FOXML+z+%2Fhome%2Fkramerius%2F.kramerius4%2Fimport%2Ffoxml-batch-examples%2Fmap+
Jun 14, 2022 7:57:13 PM org.kramerius.Import main
INFO: import dir: /home/kramerius/.kramerius4/import/foxml-batch-examples/map
Jun 14, 2022 7:57:13 PM org.kramerius.Import main
INFO: start indexer: true
Jun 14, 2022 7:57:13 PM org.kramerius.Import run
INFO: INGEST - url:http://localhost:8080/fedora user:fedoraAdmin importRoot:/home/kramerius/.kramerius4/import/foxml-batch-examples/map
Jun 14, 2022 7:57:13 PM org.kramerius.Import run
INFO: INGEST updateExisting: false
Jun 14, 2022 7:57:13 PM org.kramerius.Import ingest
INFO: Ingested:uuid:ddda1e78-6c14-4e75-8a24-f5839557f23b in 245ms, count:1
Jun 14, 2022 7:57:13 PM org.kramerius.Import ingest
INFO: Ingested:uuid:eb2f99ca-b1fe-4e5d-a4c9-1a0b8e7f1870 in 78ms, count:2
Jun 14, 2022 7:57:13 PM org.kramerius.Import ingest
....
.. pokračování normálního logu
....
Jun 14, 2022 7:57:17 PM org.kramerius.Import run
INFO: FINISHED INGESTION IN 4.923s, processed 62 files
Jun 14, 2022 7:57:17 PM org.kramerius.Import run
INFO: NO MERGED OBJECTS FOR RELATIONS SORTING FOUND.
Jun 14, 2022 7:57:17 PM org.kramerius.Import run
INFO: Waiting for soft commit :1000 s
Jun 14, 2022 7:57:24 PM org.kramerius.Import run
WARNING: POST http://localhost:8080/search/api/admin/v7.0/processes returned a response status of 500 Internal Server Error: {"error":"error scheduling new process"}
java.lang.RuntimeException: POST http://localhost:8080/search/api/admin/v7.0/processes returned a response status of 500 Internal Server Error: {"error":"error scheduling new process"}
at cz.incad.kramerius.processes.new_api.IndexationScheduler.scheduleIndexation(IndexationScheduler.java:51)
at org.kramerius.Import.run(Import.java:233)
at org.kramerius.Import.main(Import.java:133)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:125)
Caused by: com.sun.jersey.api.client.UniformInterfaceException: POST http://localhost:8080/search/api/admin/v7.0/processes returned a response status of 500 Internal Server Error
at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)
at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:560)
at cz.incad.kramerius.processes.new_api.IndexationScheduler.scheduleIndexation(IndexationScheduler.java:37)
... 7 more
Jun 14, 2022 7:57:24 PM org.kramerius.Import run
INFO: NO CONVOLUTES FOR INDEXING FOUND.
Jun 14, 2022 7:57:25 PM cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: system error file contains errors
cz.incad.kramerius.processes.WarningException: system error file contains errors
at cz.incad.kramerius.processes.starter.ProcessStarter.checkErrorFile(ProcessStarter.java:187)
at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:128)
Jun 14, 2022 7:57:25 PM cz.incad.kramerius.processes.starter.ProcessUpdatingChannel$StandardProcessUpdatingChannel updateStatus
INFO: requesting url: http://localhost:8080/search//lr?action=updateStatus&uuid=680f239d-20ee-473a-aaca-fe2be0d33e8e&state=WARNING

podívejte se sem:
(https://admin.k7-test.mzk.cz/processes/289805)

Na podobnou chybu v minulosti upoznornoval Aleksei
https://github.com/ceskaexpedice/kramerius/issues/719
--------------

Potom ještě existuje další náhodný druh chyby, když je uuid: opět více jak těch 15, tak se sice podaří všechno naimportovat, ale při indexaci se u některé může ukázat jako chyba. Podle logu, by tam ale chyba byt neměla. Když se dané uuid zreindexuje znovu, je všechno ok.
podívejte se sem:
https://admin.k7-test.mzk.cz/processes/289782

**Comment by vlahoda** [comment]
Toto s chybou #719 zrejme nesouvisi.

Proces hlasi, ze pri jeho spousteni server vratil Internal Server Error a v logu tomcatu je v odpovidajicim case toto:

14-Jun-2022 19:57:24.465 SEVERE [http-nio-8080-exec-2] cz.incad.kramerius.processes.impl.DatabaseProcessManager.registerLongRunningProcess ERROR: duplicate key value violate
s unique constraint "process_batch_pkey"
  Detail: Key (batch_token)=(60a1ef7a-12cf-4066-9d0f-d5666fad96d6) already exists.
  Where: SQL statement "INSERT into process_batch
    SELECT
        processes.token AS batch_token,
        batch_state(processes.status) AS batch_state,
        count(*) AS process_count,
        min(processes.process_id) AS first_process_id,
        min(processes.status) AS first_process_state,
        min(processes.uuid) AS first_process_uuid,
        min(processes.defid) AS first_process_defid,
        min(processes.name) AS first_process_name,
        min(processes.planned) AS planned,
        min(processes.started) AS started,
        max(processes.finished) AS finished,
        min(processes.owner_id) AS owner_id,
        min(processes.owner_name) AS owner_name
      FROM
        processes
      WHERE
        processes.token=rec.token
      GROUP BY
        processes.token
      ORDER BY
 first_process_id DESC"
PL/pgSQL function refresh_process_batch() line 17 at SQL příkaz
        org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "process_batch_pkey"
  Detail: Key (batch_token)=(60a1ef7a-12cf-4066-9d0f-d5666fad96d6) already exists.
  Where: SQL statement "INSERT into process_batch
    SELECT
        processes.token AS batch_token,
        batch_state(processes.status) AS batch_state,
        count(*) AS process_count,
        min(processes.process_id) AS first_process_id,
        min(processes.status) AS first_process_state,
        min(processes.uuid) AS first_process_uuid,
        min(processes.defid) AS first_process_defid,
        min(processes.name) AS first_process_name,
        min(processes.planned) AS planned,
        min(processes.started) AS started,
        max(processes.finished) AS finished,
        min(processes.owner_id) AS owner_id,
        min(processes.owner_name) AS owner_name
      FROM
        processes
      WHERE
        processes.token=rec.token
      GROUP BY
        processes.token
      ORDER BY
        first_process_id DESC"
PL/pgSQL function refresh_process_batch() line 17 at SQL příkaz
                at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
                at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
                at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
                at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
                at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
                at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
                at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
                at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
                at cz.incad.kramerius.processes.database.ProcessDatabaseUtils.registerProcess(ProcessDatabaseUtils.java:144)
                at cz.incad.kramerius.processes.impl.DatabaseProcessManager.registerLongRunningProcess(DatabaseProcessManager.java:126)
                at cz.incad.kramerius.processes.impl.AbstractLRProcessImpl.planMe(AbstractLRProcessImpl.java:130)
                at cz.incad.kramerius.rest.apiNew.admin.v70.ProcessSchedulingHelper.scheduleProcess(ProcessSchedulingHelper.java:79)
                at cz.incad.kramerius.rest.apiNew.admin.v70.processes.ProcessResource.scheduleProcess(ProcessResource.java:642)
                at cz.incad.kramerius.rest.apiNew.admin.v70.processes.ProcessResource.scheduleProcess(ProcessResource.java:617)
                at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
                at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
                at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
                at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
                at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
                at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
                at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
                at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
                at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
                at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
                at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
                at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
                at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
                at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
                at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
 at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
                at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
                at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
                at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
                at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.kramerius.keycloak.KrameriusKeycloakFilter.doFilter(KrameriusKeycloakFilter.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:25)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
                at cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.Kramerius.XSSFilter.doFilter(XSSFilter.java:36)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:750)
14-Jun-2022 19:57:24.467 SEVERE [http-nio-8080-exec-2] com.sun.jersey.spi.container.ContainerResponse.logException Mapped exception to response: 500 (Internal Server Error)
        cz.incad.kramerius.rest.apiNew.exceptions.InternalErrorException
                at cz.incad.kramerius.rest.apiNew.admin.v70.ProcessSchedulingHelper.scheduleProcess(ProcessSchedulingHelper.java:81)
                at cz.incad.kramerius.rest.apiNew.admin.v70.processes.ProcessResource.scheduleProcess(ProcessResource.java:642)
                at cz.incad.kramerius.rest.apiNew.admin.v70.processes.ProcessResource.scheduleProcess(ProcessResource.java:617)
                at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
                at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
                at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
                at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
                at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
                at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
                at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
                at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
 at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
                at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
                at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
                at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
                at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
                at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
                at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
                at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
                at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
                at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
                at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.kramerius.keycloak.KrameriusKeycloakFilter.doFilter(KrameriusKeycloakFilter.java:189)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:25)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
                at cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at cz.incad.Kramerius.XSSFilter.doFilter(XSSFilter.java:36)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:750)


Tedy nejaky neporadek v tabulce procesu. @pavel-stastny  - chyba v datech nebo v kodu?

**Comment by pavel-stastny** [comment]
@vlahoda Pravděpodobně souvisí s #909  a storovanou PL/pgSQL procedurou refresh_process_batch.  Poprosil bych @rzeh4n.

**Comment by pavel-stastny** [comment]
@hlavacekrene Problém je ve SQL proceduře, která generuje id pro spouštění v dávce.  Jako workaround doporučujeme nastavit počet aktivních procesů na jeden: 

`processQueue.activeProcess=1 `
