### ISSUE TITLE
Nefunkční stahování pdf

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#901]
Dobrý den,

nefunguje nám stahování pdf. V logu Tomcatu jsou chyby, ale netuším, co je způsobuje:

```
Jun 27, 2022 2:47:28 PM cz.knav.pdf.PdfTextUnderImage registerFontDirectories
INFO: registred fonts 3
Jun 27, 2022 2:47:29 PM cz.incad.kramerius.rest.api.k5.client.pdf.PDFResource selection
SEVERE: Premature EOF
java.io.IOException: Premature EOF
	at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:257)
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3451)
	at javax.imageio.stream.FileCacheImageInputStream.readUntil(FileCacheImageInputStream.java:142)
	at javax.imageio.stream.FileCacheImageInputStream.read(FileCacheImageInputStream.java:187)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInputData(JPEGImageReader.java:312)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1255)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1058)
	at javax.imageio.ImageIO.read(ImageIO.java:1462)
	at javax.imageio.ImageIO.read(ImageIO.java:1357)
	at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:83)
	at cz.incad.kramerius.utils.imgs.KrameriusImageSupport.readImage(KrameriusImageSupport.java:52)
	at cz.incad.kramerius.pdf.impl.SimplePDFServiceImpl.template(SimplePDFServiceImpl.java:164)
	at cz.incad.kramerius.pdf.impl.SimplePDFServiceImpl.pdf(SimplePDFServiceImpl.java:93)
	at cz.incad.kramerius.rest.api.k5.client.pdf.AbstractPDFResource.selection(AbstractPDFResource.java:170)
	at cz.incad.kramerius.rest.api.k5.client.pdf.PDFResource.selection(PDFResource.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
	at cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.XSSFilter.doFilter(XSSFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:312)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Jun 27, 2022 2:47:29 PM com.sun.jersey.spi.container.ContainerResponse logException
SEVERE: Mapped exception to response: 500 (Internal Server Error)
cz.incad.kramerius.rest.api.exceptions.GenericApplicationException
	at cz.incad.kramerius.rest.api.k5.client.pdf.PDFResource.selection(PDFResource.java:295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
	at cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.XSSFilter.doFilter(XSSFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:312)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

V čem by mohl bejt problém?

**Comment by pavel-stastny** [comment]
@svetlym To vypadá, jakoby mu fedora předčasně zavřela stream  s obrázkem při generování PDF.  Vyzkoušel bych generovat jednostránkové pdf a pokud selže, tak přimo z fedory stáhnout samotný obrázek.

**Comment by svetlym** [comment]
Zkoušel jsem upgradovat na jádro verze 5.8.0, jestli problém nezmizí - a nezmizel. Předtím jsem ale omylem nainstaloval starší verzi 5.5.0, a v tý se pdfko vygenerovalo bez problémů.

**Comment by pavel-stastny** [comment]
@svetlym  Tam je problém, že ten stream se vždy nějak usekne.  Snažím se dívat na některé volné tituly: 

https://kramerius4.mlp.cz/search/img?uuid=uuid:24bd7190-2317-11e0-8341-0030487be43a&stream=IMG_FULL&action=GETRAW

https://kramerius4.mlp.cz/search/img?uuid=uuid:24EAF230-81F6-11E0-9124-0030487BE43A&stream=IMG_FULL&action=GETRAW

https://kramerius4.mlp.cz/search/img?uuid=uuid:24F21E20-81F6-11E0-B475-0030487BE43A&stream=IMG_FULL&action=GETRAW

a vždy mi to končí v části obrázku.  Nedokážu říct, zda to dělá o všech ale pro generování pdf pak stačí jedna taková stránka.

**Comment by svetlym** [comment]
To, že nám stahování pdfek funguje ve verzi 5.5.0, se nakonec nepotvrdilo. Zřejmě je to opravdu o náhodě a když jsem ji zkoušel, zrovna to zafugnovalo.

**Comment by svetlym** [comment]
> @svetlym Tam je problém, že ten stream se vždy nějak usekne.

Potvrzuju, taky mi to zobrazuje jen části obrázků. Přitom ale při procházení dokumentů v Kramériovi se to nestává. Při generování pdfek se používá jinej dotaz na imageserver než při prohlížení?

S imageserverem jsem už dlouho nic nedělali, ale to, že nefunguje stahování pdf, nám čtenáři začali hlásit teprve nedávno. Ani konfigurace Kraméria se dlouho neměnila, jen občas probíhá update Ubuntu, na kterym běží.

**Comment by pavel-stastny** [comment]
> Potvrzuju, taky mi to zobrazuje jen části obrázků. Přitom ale při procházení dokumentů v Kramériovi se to nestává. Při generování pdfek se používá jinej dotaz na imageserver než při prohlížení?

Při prohlížení se dotazjí jenom jednotlivé dlaždice z IIP serveru.  Při zobrazení plného obrázku se využívá stream IMG_FULL a teď záleží na tom, jak jsou pořízena data.  Může to být tak, že IMG_FULL je jenom odkaz do IIP serveru nebo to může být tak, že je celý obrázek uložený ve fedoře.

**Comment by svetlym** [comment]
Obrázky jsou u nás všechny na imageserver.mlp.cz, ve fedoře jsou jen foxml.

**Comment by svetlym** [comment]
Aha, docker sežral všechno místo na systémovym disku imageserveru. Předpokládám, že to bude tím.

**Comment by svetlym** [comment]
Bylo to opravdu tím, děkuju za přivedení na správnou stopu. Zavírám issue.
