### ISSUE TITLE
Synchronizace se SDNNT

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius#919]
Zkoušel jsem spustit na jádře 5.8.1 proces synchronizace se SDNNT, ale vždy to selže.

Jako SDNNT instanci jsem použil testovací SDNNT, jak se píše v dokumentaci: `https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/changes`. 

Podle výstupu se Kramerius dostal k tomu, že si stáhnul seznam, ale potom proces spadne na výjimce:  _Caused by: org.json.JSONException: A JSONObject text must begin with &#039;{&#039; at 1 [character 2 line 1]._

Celý chybový výstup:
```
Lis 01, 2022 12:45:58 ODP. cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: org.json.JSONException: A JSONObject text must begin with &#039;{&#039; at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.&lt;init&gt;(JSONObject.java:194)
	at org.json.JSONObject.&lt;init&gt;(JSONObject.java:321)
	at cz.inovatika.sdnnt.utils.SDNNTCheckUtils.checkAgainstSolr(SDNNTCheckUtils.java:48)
	at cz.inovatika.sdnnt.utils.SDNNTCheckUtils.checkAgainstSolrIsLicensePresent(SDNNTCheckUtils.java:83)
	at cz.inovatika.sdnnt.SDNNTCheck.batchFormatAndLicense(SDNNTCheck.java:154)
	at cz.inovatika.sdnnt.SDNNTCheck.process(SDNNTCheck.java:74)
	at cz.inovatika.sdnnt.ParametrizedSDNNTCheck.check(ParametrizedSDNNTCheck.java:63)
	... 5 more
```
[Standardní výstup](https://github.com/ceskaexpedice/kramerius/files/9910099/2385491c-47a6-4705-8290-adf8a4428e1b_stout.txt)

můžu poprosit o vysvětlení, co dělám špatně nebo kde je chyba? 

Děkuji

**Comment by pavel-stastny** [comment]
@kerschfilip Vyzkoušejte, prosím, s adresou krameria **https**://kramerius.lib.cas.cz/search

**Comment by kerschfilip** [comment]
@pavel-stastny prosím o prověření aktuálního fungování synchronizace se SDNNT. Nějak se mi to nedaří spustit ani proti testovací verzi ani proti ostré. Díky.

proti ostré verzi:
```
Úno 15, 2023 9:12:04 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;static-export-5.8.3&#039; to &#039;static_export.properties&#039;
Úno 15, 2023 9:12:04 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-mets-5.8.3&#039; to &#039;migration.properties&#039;
Úno 15, 2023 9:12:04 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;indexer-5.8.3&#039; to &#039;indexer.properties&#039;
Úno 15, 2023 9:12:04 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-cmdtool-5.8.3&#039; to &#039;migration.properties&#039;
Úno 15, 2023 9:12:04 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;common-5.8.3&#039; to &#039;configuration.properties&#039;
Úno 15, 2023 9:12:05 DOP. cz.incad.kramerius.processes.impl.ProcessStarter updateName
INFO: requesting url :https://kramerius.lib.cas.cz/search//lr?action=updateName&amp;uuid=3d69c606-2d1c-45da-9454-38b9c23de413&amp;name=Syncrhonizace+s+https%3A%2F%2Fkramerius.lib.cas.cz%2Fsearch++%3C-%3E+https%3A%2F%2Fsdnnt.nkp.cz%2Fsdnnt%2Fapi%2Fv1.0%2Flists%2Fchanges
Úno 15, 2023 9:12:05 DOP. cz.inovatika.sdnnt.ParametrizedSDNNTCheck check
INFO: Sdnnt endpoint :https://sdnnt.nkp.cz/sdnnt/api/v1.0/lists/changes
Úno 15, 2023 9:12:05 DOP. cz.inovatika.sdnnt.ParametrizedSDNNTCheck check
INFO: Kramerius instance :https://kramerius.lib.cas.cz/search
Úno 15, 2023 9:12:05 DOP. cz.inovatika.sdnnt.ParametrizedSDNNTCheck check
INFO: Output folder :/home/kramerius/.kramerius4/import-dnnt
Úno 15, 2023 9:12:05 DOP. cz.inovatika.sdnnt.SDNNTCheck process
INFO: Connecting sdnnt list and iterating serials 
Úno 15, 2023 9:12:05 DOP. cz.inovatika.sdnnt.SDNNTCheck iterateSDNNTFormat
INFO: SDNNT changes endpoint is https://sdnnt.nkp.cz/sdnnt/api/v1.0/lists/changes
Úno 15, 2023 9:12:08 DOP. cz.inovatika.sdnnt.SDNNTCheck process
INFO: Connecting sdnnt list and iterating books 
Úno 15, 2023 9:12:08 DOP. cz.inovatika.sdnnt.SDNNTCheck iterateSDNNTFormat
INFO: SDNNT changes endpoint is https://sdnnt.nkp.cz/sdnnt/api/v1.0/lists/changes
Úno 15, 2023 9:12:24 DOP. cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: org.json.JSONException: JSONObject[&#034;license&#034;] not found.
	at org.json.JSONObject.get(JSONObject.java:473)
	at org.json.JSONObject.getString(JSONObject.java:654)
	at cz.inovatika.sdnnt.SDNNTCheck.iterateSDNNTFormat(SDNNTCheck.java:271)
	at cz.inovatika.sdnnt.SDNNTCheck.process(SDNNTCheck.java:64)
	at cz.inovatika.sdnnt.ParametrizedSDNNTCheck.check(ParametrizedSDNNTCheck.java:63)
```

proti testovací verzi:
```
Úno 15, 2023 9:14:34 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;static-export-5.8.3&#039; to &#039;static_export.properties&#039;
Úno 15, 2023 9:14:34 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-mets-5.8.3&#039; to &#039;migration.properties&#039;
Úno 15, 2023 9:14:34 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;indexer-5.8.3&#039; to &#039;indexer.properties&#039;
Úno 15, 2023 9:14:34 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-cmdtool-5.8.3&#039; to &#039;migration.properties&#039;
Úno 15, 2023 9:14:34 DOP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;common-5.8.3&#039; to &#039;configuration.properties&#039;
Úno 15, 2023 9:14:35 DOP. cz.incad.kramerius.processes.impl.ProcessStarter updateName
INFO: requesting url :https://kramerius.lib.cas.cz/search//lr?action=updateName&amp;uuid=f4361335-442c-4d50-9340-476da8750979&amp;name=Syncrhonizace+s+https%3A%2F%2Fkramerius.lib.cas.cz%2Fsearch++%3C-%3E+https%3A%2F%2Fsdnnt-test.nkp.cz%2Fsdnnt%2Fapi%2Fv1.0%2Flists%2Fchanges
Úno 15, 2023 9:14:35 DOP. cz.inovatika.sdnnt.ParametrizedSDNNTCheck check
INFO: Sdnnt endpoint :https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/changes
Úno 15, 2023 9:14:35 DOP. cz.inovatika.sdnnt.ParametrizedSDNNTCheck check
INFO: Kramerius instance :https://kramerius.lib.cas.cz/search
Úno 15, 2023 9:14:35 DOP. cz.inovatika.sdnnt.ParametrizedSDNNTCheck check
INFO: Output folder :/home/kramerius/.kramerius4/import-dnnt
Úno 15, 2023 9:14:35 DOP. cz.inovatika.sdnnt.SDNNTCheck process
INFO: Connecting sdnnt list and iterating serials 
Úno 15, 2023 9:14:35 DOP. cz.inovatika.sdnnt.SDNNTCheck iterateSDNNTFormat
INFO: SDNNT changes endpoint is https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/changes
Úno 15, 2023 9:14:37 DOP. cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: org.json.JSONException: JSONObject[&#034;pid&#034;] not found.
	at org.json.JSONObject.get(JSONObject.java:473)
	at org.json.JSONObject.getString(JSONObject.java:654)
	at cz.inovatika.sdnnt.SDNNTCheck.iterateSDNNTFormat(SDNNTCheck.java:260)
	at cz.inovatika.sdnnt.SDNNTCheck.process(SDNNTCheck.java:62)
	at cz.inovatika.sdnnt.ParametrizedSDNNTCheck.check(ParametrizedSDNNTCheck.java:63)
	... 5 more
```

Moc díky!

**Comment by pavel-stastny** [comment]
@kerschfilip Vyda se nova verze, ktera bude obsahovat podobny dialog jako v K7.

**Comment by pavel-stastny** [comment]
Postup stejný jako v K7.  Nejdříve musí být nadefinované konfigurační proměnné: 
```
sdnnt.check.local.api = https://kramerius.lib.cas.cz/search/api/v5.0   - odkaz na lokální instanci
sdnnt.check.acronym=knav  - akronym knihovny, koresponduje s registrem krameriu
```

Poté je potřeba spustit synchornizaci: 

![image](https://github.com/ceskaexpedice/kramerius/assets/675753/2b0690b6-a4b7-4d1e-bce8-92736d495ff5)

A nakonec akceptovat výsledek synchornizace: 

![image](https://github.com/ceskaexpedice/kramerius/assets/675753/c40a43cd-d644-4d0b-ac77-77554058915d)

![image](https://github.com/ceskaexpedice/kramerius/assets/675753/e8c87123-dca7-4b42-88ca-f47ca97b0a75)

**Comment by mduda100871** [comment]
Dvě poznámky:

- Výše zmíněné property je potřeba uložit do konfiguračního souboru `configuration.properties` jinak se nenačtou.

- Solr schéma je jen pro Sol-8, lze použít i pro Solr-6, resp. bylo by možné případně vydat schéma i pro Solr-6?

MD

**Comment by mduda100871** [comment]
Je potřeba vydat opravný patch pro Solr-6.

MD

**Comment by kerschfilip** [comment]
@pavel-stastny rozdíly oproti SDNNT obsahují i dokumenty, které mají v Krameriovi _policy:public_. Je to vidět i na tvém screenshotu, kde to chce, aby se pro "Československý časopis historický" nastavil label `dnnto`, ačkoli ho máme v Krameriovi odemčený. Stejně tak i pro monografie. 

Myslel jsem, že jsme se na schůzkách domluvili, že to _public_ díla bude ignorovat. Nebo mám ten výsledek rozdílu aplikovat i tak? Přidávat dnnt k veřejným dílům mi přijde zvláštní, tak nevím... Díky
