### ISSUE TITLE
Chyba při importu zvukového dokumentu

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#922]
Dobrý den,

pokus o import zvukového dokumentu vytvořeného v Proarcu podle nového standardu selhal s následující chybou (kramérius verze verze 5.7.2):

```
Nov 14, 2022 5:19:35 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.RuntimeException: org.kramerius.importmets.valueobj.ServiceException: org.kramerius.importmets.valueobj.ServiceException: Unknown fileGrp: MC_AUDIOGRP
	at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:75)
	... 5 more
Caused by: org.kramerius.importmets.valueobj.ServiceException: org.kramerius.importmets.valueobj.ServiceException: Unknown fileGrp: MC_AUDIOGRP
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.convert(MetsPeriodicalConvertor.java:62)
	at org.kramerius.importmets.MetsConvertor.convertOneDirectory(MetsConvertor.java:325)
	at org.kramerius.importmets.MetsConvertor.convert(MetsConvertor.java:191)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:115)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:111)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:111)
	at org.kramerius.importmets.MetsConvertor.checkAndConvertDirectory(MetsConvertor.java:111)
	at org.kramerius.importmets.MetsConvertor.main(MetsConvertor.java:62)
	at org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport.process(ParametrizedMetsNKDImport.java:73)
	... 5 more
Caused by: org.kramerius.importmets.valueobj.ServiceException: Unknown fileGrp: MC_AUDIOGRP
	at org.kramerius.importmets.convertor.BaseConvertor.getFileType(BaseConvertor.java:870)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.loadFileMap(MetsPeriodicalConvertor.java:148)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.convert(MetsPeriodicalConvertor.java:56)
	... 13 more
```

Změnilo se něco v konfiguraci importu zvukových dokumentů? Nedaří se mi to na wiki najít.

**Comment by pavel-stastny** [comment]
@svetlym Je Issue stále platné ?

**Comment by svetlym** [comment]
@pavel-stastny: Přešli jsme na K7, takže pravděpodobně ne.
