### ISSUE TITLE
Chybny regex v IP filtru zrejme blokuje cele vyhodnoceni autorizacnich kriterii

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#932]
Po zadani chybneho regexu do kriteria IP filtru se prestaly zobrazovat stranky v K7 a udajne se neda ani prihlasit do admin aplikace.  

V logu tomcatu  je toto:
```
cz.incad.kramerius.rest.apiNew.client.v70.ItemsResource.getInfo Dangling meta character '*' near index 0
*
^
	java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*
^
		at java.base/java.util.regex.Pattern.error(Unknown Source)
		at java.base/java.util.regex.Pattern.sequence(Unknown Source)
		at java.base/java.util.regex.Pattern.expr(Unknown Source)
		at java.base/java.util.regex.Pattern.compile(Unknown Source)
		at java.base/java.util.regex.Pattern.<init>(Unknown Source)
		at java.base/java.util.regex.Pattern.compile(Unknown Source)
		at java.base/java.util.regex.Pattern.matches(Unknown Source)
		at java.base/java.lang.String.matches(Unknown Source)
		at cz.incad.kramerius.security.impl.criteria.utils.CriteriaIPAddrUtils.matchIPAddresses(CriteriaIPAddrUtils.java:26)
		at cz.incad.kramerius.security.impl.criteria.utils.CriteriaIPAddrUtils.matchIPAddresses(CriteriaIPAddrUtils.java:14)
		at cz.incad.kramerius.security.impl.criteria.DefaultIPAddressFilter.evalute(DefaultIPAddressFilter.java:36)
		at cz.incad.kramerius.security.impl.RightImpl.evaluate(RightImpl.java:118)
		at cz.incad.kramerius.security.impl.DatabaseRightsManager.resolve(DatabaseRightsManager.java:256)
		at cz.incad.kramerius.security.impl.http.RightsResolverFromRequest.isAllowedInternalForFedoraDocuments(RightsResolverFromRequest.java:99)
		at cz.incad.kramerius.security.impl.http.RightsResolverFromRequest.isActionAllowed(RightsResolverFromRequest.java:60)
		at cz.incad.kramerius.rest.apiNew.client.v70.utils.ProvidedLicensesUtils.extractLicensesProvidingAccess(ProvidedLicensesUtils.java:49)
		at cz.incad.kramerius.rest.apiNew.client.v70.ItemsResource.getInfo(ItemsResource.java:150)

```

a nasledne server vraci chybu 500:
```
05-Jan-2023 15:24:22.081 SEVERE [http-nio-8080-exec-13] com.sun.jersey.spi.container.ContainerResponse.logException Mapped exception to response: 500 (Internal Server Error)
	cz.incad.kramerius.rest.apiNew.exceptions.InternalErrorException: HTTP 500 Internal Server Error
		at cz.incad.kramerius.rest.apiNew.client.v70.ItemsResource.getInfo(ItemsResource.java:156)
```

@pavel-stastny Zrejme tedy jedno chybne kriterium zablokuje cely retezec autorizace?

**Comment by pavel-stastny** [comment]
Opraveno komitem e97d18b1327f3038f7b7b18c84e411074e1176b9
