### ISSUE TITLE
Ve verzi Krameria 5.8 nefunguje OAI

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#938]
Zrejme problem nekompatibilni knihovny s JDK11:
16-Feb-2023 07:30:44.246 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [oaiServlet] in context with path [/search] threw exception [javax.servlet.ServletException: Servlet execution threw an exception] with root cause
        java.lang.NoSuchMethodError: 'org.codehaus.stax2.ri.EmptyIterator org.codehaus.stax2.ri.EmptyIterator.getInstance()'
                at com.ctc.wstx.evt.CompactStartElement.getAttributes(CompactStartElement.java:94)
                at org.codehaus.stax2.ri.Stax2EventWriterImpl.add(Stax2EventWriterImpl.java:107)
                at org.codehaus.stax2.ri.Stax2EventWriterImpl.add(Stax2EventWriterImpl.java:175)
                at cz.incad.Kramerius.oai.DrKrameriusV4Writer.generateBiblio(DrKrameriusV4Writer.java:132)
                at cz.incad.Kramerius.oai.DrKrameriusV4Writer.generateRecord(DrKrameriusV4Writer.java:163)
                at cz.incad.Kramerius.oai.DrKrameriusV4Writer.generate(DrKrameriusV4Writer.java:195)
                at cz.incad.Kramerius.oai.DrKrameriusV4Writer.writeResponse(DrKrameriusV4Writer.java:120)
                at cz.incad.Kramerius.oai.DrKrameriusV4Writer.fetchContent(DrKrameriusV4Writer.java:112)
                at cz.incad.Kramerius.oai.DrKrameriusV4Writer.getContent(DrKrameriusV4Writer.java:96)
                at cz.incad.Kramerius.oai.OaiServlet.sendResponse(OaiServlet.java:169)
                at cz.incad.Kramerius.oai.OaiServlet.doGet(OaiServlet.java:111)

**Comment by pavel-stastny** [comment]
S implementaci OAI se poítalo v K7 a je to řešeno v rámci #1034
