### ISSUE TITLE
NPE v IIIF servletu K7

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#951]
V logu tomcatu se casto vyskytuje tohle:

 SEVERE [http-nio-8080-exec-191] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [iiifServlet] in context with path [/search] threw exception [javax.servlet.ServletException: java.lang.NullPointerException] with root cause
        java.lang.NullPointerException
                at cz.incad.kramerius.utils.RelsExtHelper.getRelsExtTilesUrl(RelsExtHelper.java:64)
                at cz.incad.kramerius.rest.api.k5.client.item.utils.IIIFUtils.iiifImageEndpoint(IIIFUtils.java:14)
                at cz.incad.Kramerius.imaging.IiifServlet.doGet(IiifServlet.java:90)

**Comment by pavel-stastny** [comment]
Je v logu videt i pid u ktereho se to vyskytuje ?
