### ISSUE TITLE
K7 / Proces pridávania licencie zmaže RELS-EXT datastream

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius#994]
Ahoj,
asi tretí krát sa nám v MZK stalo, že niektorým dokumentom po behu procesu pridávania licencie, zmizol datastream RELS-EXT z FOXML.
Stáva sa to ozaj len výnimočne, neviem pri akých podmienkach. A zatiaľ nemáme nastavené ukladanie logov procesov na trvalé úložisko. Z toho dôvodu sa mi ani raz nepodarilo získať log z inkriminovaného procesu.
Čo sa týka logov Kraméria, tie sú k dispozícií, ale denný log má 595M, takže mi ho tu nejde uploadnúť, ale môžem ho poslať ak treba.
Tu je [zoznam konkrétnych dokumentov](https://docs.google.com/spreadsheets/d/17ASTa8kCxPg-YRd7fJdilkGwUhiYu0eOvVfY8dpUAFo/edit?usp=sharing). Prešiel som foxml všetkých dokumentov, ktoré majú v K7 nastavenú nejakú licenciu a našiel som nekonzistentých len tých 11 z 01.08. a zvyšných 58 z utorka 05.09.
Tie chyby z 05.09. budú z jedného z procesov 770974 - 770979 v našom Kramériu. Ale ako píšem POD Kraméria sa odvtedy bohužiaľ reštartoval, takže logy procesov nie sú k dispozícií.

Momentálne u nás riešime ukladanie logov procesov na trvalé úložisko, keď to bude vyriešené, tak sa hádam dozvieme viac. Zatiaľ skúsim túto chybu nejak zreplikovať. Ak zistím niečo viac tak to tu napíšem. 

Róbert, MZK - OSDD

**Comment by vlahoda** [comment]
Ahoj, prosim o info - je mozne, ze bezelo paralelne vic procesu, ktere soucasne modifikovaly licence ze stejneho periodika nebo ze stejneho rocniku (u ktereho pak chybi ten RELS-EXT stream) ?

**Comment by r2it-git** [comment]
Áno, bežalo viacero paralelných procesov a je veľmi pravdepodobné, že niekde nastali súčasné modifikácie licencií ročníkov z rovnakého periodika. 

Pidy boli rozdelené náhodne medzi viacero procesov. Doplnil som to do [toho dokumentu](https://docs.google.com/spreadsheets/d/17ASTa8kCxPg-YRd7fJdilkGwUhiYu0eOvVfY8dpUAFo/edit?usp=sharing) do sheetu "pids, ktorym bola pridavana licencia naraz" konkrétne pidy. Ale jednalo sa o 564 ročníkov z 22 periodík, rozdelených po 100 do 6tich procesov.

**Comment by r2it-git** [comment]
Pozerám, že tam je jedno periodikum iba s jedným ročníkom https://www.digitalniknihovna.cz/mzk/periodical/uuid:bd94bdf0-92c0-11eb-871e-005056827e51

**Comment by vlahoda** [comment]
Diky za potvrzeni, to bude zrejme podobny problem, jako pred casem pri vytvareni sbirek - tedy chybejici zamky pro paralelni zpracovani. Zkontroluji to a opravim.

**Comment by r2it-git** [comment]
Ahoj,
dnes sa to stalo znova na 21 pidoch. Pri všetkých pidoch nastala tá istá chyba:
`SEVERE: Cannot delete relations for streamId RELS-EXT
cz.incad.kramerius.fedora.om.RepositoryException: Cannot delete relations for streamId RELS-EXT
	at cz.incad.kramerius.fedora.om.impl.AkubraObject.deleteStream(AkubraObject.java:174)
	at cz.incad.kramerius.repository.RepositoryApiImpl.updateInlineXmlDatastream(RepositoryApiImpl.java:381)
	at cz.incad.kramerius.repository.KrameriusRepositoryApiImpl.updateRelsExt(KrameriusRepositoryApiImpl.java:246)
	at cz.incad.kramerius.SetLicenseProcess.addRelsExtRelationAfterNormalization(SetLicenseProcess.java:263)
	at cz.incad.kramerius.SetLicenseProcess.addLicense(SetLicenseProcess.java:169)
	at cz.incad.kramerius.SetLicenseProcess.main(SetLicenseProcess.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:129)
Caused by: org.apache.solr.client.solrj.SolrServerException: IOException occurred when talking to server at: http://solr.k7-solr.svc.cluster.local:8983/solr/processing
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:695)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:266)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248)
	at org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrClient.request(ConcurrentUpdateSolrClient.java:506)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)`

pidy: [missing_rels_pids.txt](https://github.com/ceskaexpedice/kramerius/files/13031057/missing_rels_pids.txt)
proces out: [805764_out.txt](https://github.com/ceskaexpedice/kramerius/files/13031061/805764_out.txt)
proces err: [805764_err.txt](https://github.com/ceskaexpedice/kramerius/files/13031064/805764_err.txt)

Róbert, MZK - OSDD

**Comment by vlahoda** [comment]
@r2it-git - diky za ty logy, uz vidim, co se tam deje a opravim kod tak, aby nedochazelo k tomu likvidovani streamu RELS-EXT. Skutecna pricina problemu je ale nejaka chyba v sitove komunikaci - proces se snazil zapisovat do SOLR indexu na adrese http://solr.k7-solr.svc.cluster.local:8983/solr/processing a nepodarilo se mu otevrit socket s chybou: java.net.BindException: Cannot assign requested address. Bylo by dobre najit pricinu tohoto chovani, protoze i kdyz upravim kod tak, aby se choval korektneji, bude ten proces dal padat.

**Comment by vlahoda** [comment]
Ve verzi 7.0.31 je kod procesu upraven tak, ze chyby processing indexu jsou jen logovany, ale zapis novych dat do FOXML v repository by mel normalne probehnout. Proces skonci ve stavu WARNING.
